const RACES={Mensch:{bonus:{str:2,agi:2,int:2},passive:'Anpassungsfähigkeit',effect:'Permanent +10% XP-Gewinn',icon:'🧑',desc:'Ausgeglichen und anpassungsfähig.'},Elf:{bonus:{agi:4,int:2},passive:'Arkaner Reflex',effect:'+5% Ausweichen, +3% Krit-Chance',icon:'🧝',desc:'Schnell, präzise und arkan begabt.'},Zwerg:{bonus:{str:4,hp:20},passive:'Steinblut',effect:'Permanent +15% Rüstungswert',icon:'⛏️',desc:'Zäh und stark, gebaut für lange Kämpfe.'},Ork:{bonus:{str:5,agi:1},passive:'Blutrausch',effect:'+25% Schaden gegen Gegner unter 30% HP',icon:'👹',desc:'Brutale Kraft und unerbittlicher Angriff.'},Nachtläufer:{bonus:{agi:4,int:2},passive:'Schattenschritt',effect:'+5% Life-Steal, erster Schlag kritisch',icon:'🌙',desc:'Ein lautloser Jäger zwischen Schatten und Magie.'},Drachengeborener:{bonus:{str:3,int:3},passive:'Drachenatem',effect:'10% Chance auf Elementarbrand über 3 Runden',icon:'🐉',desc:'Träger uralter drakonischer Macht.'}};
const CLASSES={Krieger:{primary:'STR',res:'Wut',skill:'Schildwall',role:'Tank',icon:'🛡️',desc:'Robuster Frontkämpfer mit Schildwall und Wut.'},Magier:{primary:'INT',res:'Mana',skill:'Arkaner Meteor',role:'Burst',icon:'🔮',desc:'Magischer Burst-Schaden mit teilweiser Rüstungsignorierung.'},Druide:{primary:'Hybrid',res:'Naturfokus',skill:'Gestaltwechsel',role:'Hybrid',icon:'🌿',desc:'Wechselt zwischen Bär, Katze und Mensch.'},Waldläufer:{primary:'AGI',res:'Energie',skill:'Pfeilhagel',role:'Fernkampf',icon:'🏹',desc:'Hohe Angriffsfrequenz und Ausweichen.'},Hexenmeister:{primary:'INT/AGI',res:'Seelenfragmente',skill:'Seelenentzug',role:'Debuff',icon:'🕯️',desc:'Flüche, Debuffs und Life-Steal.'},Totenbeschwörer:{primary:'INT/STR',res:'Todesessenz',skill:'Skelett-Diener',role:'Beschwörer',icon:'💀',desc:'Beschwört Skelett-Diener, die Schaden abfangen.'}};
const BG={'Tavernen-Stammgast':{effect:'+15% Abenteuerlust-Effizienz',desc:'Du kennst jeden Winkel der Taverne.',icon:'🍺'},'Gefallener Adeliger':{effect:'+10% Gold aus allen Quellen',desc:'Alte Titel, neue Schulden und ein Händchen für Geschäfte.',icon:'👑'},'Runenschmied-Lehrling':{effect:'+10% Erfolgschance beim Aufwerten',desc:'Du hast die ersten Geheimnisse der Runenschmiede gelernt.',icon:'🔨'},'Schatten-Ausreißer':{effect:'+5% Beute-Glück',desc:'Du hast gelernt, dort Beute zu finden, wo andere nichts sehen.',icon:'🗝️'}};
const BASE={str:8,agi:8,int:8,hp:120};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let S=window.ARCANE_APP_STATE?.load?.()||{screen:'home',name:'Aventurier',race:'Mensch',cls:'Krieger',bg:'Tavernen-Stammgast',lvl:1,xp:0,gold:120,al:100,maxAl:100,hp:120,maxHp:120,str:8,agi:8,int:8,items:[{name:'Rostiges Schwert',slot:'Haupthand',power:4,rarity:'common'}],eq:{},invCap:15,forgeDust:0,essence:0,souls:0,keys:0,quests:0,wins:0,arena:0,skills:['Hieb','Schildwall','Mächtiger Schlag'],combat:null,log:['Willkommen in der Arcane Tavern.']};
function save(){return window.ARCANE_APP_STATE?.save?.(S)??false}
function xpNeed(){return Math.floor(80*Math.pow(1.16,S.lvl-1))}
function unlock(l){return S.lvl>=l?'':' 🔒 ab Stufe '+l}
function gainXP(n){S.xp+=n;let up=0;while(S.xp>=xpNeed()){S.xp-=xpNeed();S.lvl++;up++;S.maxHp+=10;S.hp=S.maxHp;S.str++;S.agi++;S.int++}return up}
function log(x){S.log.unshift(x);S.log=S.log.slice(0,14)}
function toast(t){alert(t)}
function quest(type){if(S.al<=0)return toast('Keine Abenteuerlust mehr.');let cost=type==='risk'?28:type==='event'?18:12;S.al=Math.max(0,S.al-cost);let xp=Math.floor(24+S.lvl*7),gold=Math.floor((type==='risk'?95:35)+Math.random()*45);if(type==='event'){let stat=['str','agi','int'][Math.floor(Math.random()*3)],ok=S[stat]>=S.lvl+7;gold=ok?gold*2:Math.floor(gold*.4);log(`Event-Quest: ${stat.toUpperCase()}-Check ${ok?'erfolgreich':'fehlgeschlagen'}.`)}S.gold+=gold;let up=gainXP(xp);S.quests++;if(Math.random()<.22&&S.items.length<S.invCap)S.items.push({name:'Abenteuer-Beute',slot:['Ring','Gürtel','Stiefel'][Math.floor(Math.random()*3)],power:2+S.lvl,rarity:Math.random()<.75?'magic':'rare'});log(`Quest abgeschlossen: +${gold} Gold, +${xp} XP${up?' — Level Up!':''}`);render()}
function startCombat(kind='dungeon'){if(kind==='dungeon'&&S.lvl<10)return toast('Dungeons werden erst ab Stufe 10 freigeschaltet.');let hp=kind==='arena'?80+S.lvl*12:90+S.lvl*18;S.combat={kind,enemy:'Schattenbestie',ehp:hp,max:hp,round:0};S.screen='combat';render()}
function fight(){let c=S.combat;if(!c)return;let dmg=Math.max(1,Math.floor((S.str+S.agi+S.int)/3+4+Math.random()*10));if(S.cls==='Magier')dmg+=8;if(S.cls==='Waldläufer')dmg+=4;c.ehp-=dmg;c.round++;log(`Du triffst für ${dmg} Schaden.`);if(c.ehp<=0){let reward=45+S.lvl*12;S.gold+=reward;gainXP(45+S.lvl*8);if(c.kind==='arena'){S.wins++;S.arena+=12}else{S.essence+=Math.random()<.25?1:0;if(Math.random()<.3)S.keys++}log(`Sieg! +${reward} Gold.`);S.combat=null;S.screen='home';render();return}let edmg=Math.max(2,Math.floor(8+S.lvl*2+Math.random()*7));if(S.cls==='Krieger')edmg=Math.floor(edmg*.8);S.hp-=edmg;log(`Die Schattenbestie verursacht ${edmg} Schaden.`);if(S.hp<=0){S.hp=Math.floor(S.maxHp*.35);S.gold=Math.max(0,S.gold-20);log('Du wurdest besiegt und wachst in der Taverne auf. -20 Gold.');S.combat=null;S.screen='home'}render()}
function forge(){if(S.lvl<5)return toast('Die Ahnen-Schmiede wird ab Stufe 5 freigeschaltet.');if(S.gold<80)return toast('80 Gold benötigt.');S.gold-=80;S.forgeDust+=5;let up=Math.random()<.8;log(up?'Schmiede: Aufwertung gelungen.':'Schmiede: Aufwertung fehlgeschlagen.');if(up)S.items[0].power++;render()}
function salvage(){let n=S.items.filter(x=>x.name!=='Rostiges Schwert').length;if(!n)return toast('Keine Beute zum Verwerten.');S.items=S.items.slice(0,1);S.forgeDust+=n*3;log(`Auto-Verwerten: ${n} Items → ${n*3} Staub.`);render()}
function offline(){let last=+localStorage.getItem('arcaneLast')||Date.now(),h=Math.min(12,(Date.now()-last)/3600000);if(h>.03){let g=Math.floor(h*18),x=Math.floor(h*10);S.gold+=g;gainXP(x);log(`Wachdienst: ${h.toFixed(1)}h offline → +${g} Gold, +${x} XP.`)}localStorage.setItem('arcaneLast',Date.now())}
function reset(){if(confirm('Beta-Spielstand wirklich löschen?')){localStorage.removeItem('arcaneBeta');location.reload()}}
function tab(name){S.screen=name;render()}
function charStats(){let r=RACES[S.race],b=CLASSES[S.cls];let st={...BASE};Object.entries(r.bonus).forEach(([k,v])=>st[k]=(st[k]||0)+v);return st}
function synergy(){let r=S.race,c=S.cls;const strong={Mensch:['Krieger','Druide'],Elf:['Magier','Waldläufer'],Zwerg:['Krieger','Totenbeschwörer'],Ork:['Krieger','Waldläufer'],Nachtläufer:['Hexenmeister','Waldläufer'],Drachengeborener:['Magier','Totenbeschwörer']};if(strong[r]?.includes(c))return {level:'Sehr hoch',text:'Diese Kombination unterstützt die Kernwerte und Spielweise besonders stark.'};return {level:'Solide',text:'Diese Kombination ist voll spielbar und bietet eine ausgewogene Mischung.'}}
function chooseRace(v){S.race=v;render()}
function chooseClass(v){S.cls=v;render()}
function chooseBg(v){S.bg=v;render()}
function setName(v){S.name=v.slice(0,24)||'Aventurier'}
function createHero(){if(!S.name.trim())return toast('Bitte gib deinem Helden einen Namen.');S.screen='home';log(`Held erstellt: ${S.name} — ${S.race}, ${S.cls}, ${S.bg}.`);render()}
function resetCharacter(){S.name='Aventurier';S.race='Mensch';S.cls='Krieger';S.bg='Tavernen-Stammgast';render()}
function render(){save();document.getElementById('app').innerHTML=`<header><div class="top"><div class="brand">🍺 Arcane Tavern & Quest <span class="small">BETA</span></div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span><span class="pill">⚡ ${S.al}/${S.maxAl}</span><span class="pill">🜂 ${S.souls}</span></div></div></header><main>${S.screen==='home'?home():S.screen==='char'?char():S.screen==='inv'?inv():S.screen==='forge'?forgeView():S.screen==='arena'?arena():S.screen==='combat'?combat():home()}</main><nav class="tabs">${[['home','🍺','Taverne'],['char','🧙','Held'],['inv','🎒','Rucksack'],['forge','🔨','Schmiede'],['arena','⚔️','Arena']].map(x=>`<button class="${S.screen===x[0]?'active':''}" onclick="tab('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join('')}</nav>`}
function home(){let p=Math.min(100,S.xp/xpNeed()*100);return `<section class="hero"><h1>Willkommen, ${esc(S.name)}.</h1><div class="sub">Das Arkane Herz pulsiert unter deiner Taverne. Deine Reise beginnt jetzt.</div><div class="actions"><button onclick="quest('std')">📜 Standard-Raubzug · 12 AL</button><button onclick="quest('event')">🎲 Event-Quest · 18 AL</button><button onclick="quest('risk')">💰 Risiko-Quest · 28 AL</button></div></section><div class="grid"><div class="card"><h3>Fortschritt</h3><div class="row"><span>Stufe ${S.lvl}</span><b>${S.xp}/${xpNeed()} XP</b></div><div class="bar"><i style="width:${p}%"></i></div><p class="small">Feature-Gating: Arena ab 3 · Schmiede ab 5 · Dungeon ab 10 · Gilde ab 15 · Reinkarnation ab 100.</p></div><div class="card"><h3>Offline-Wachdienst</h3><p>Bis zu 12 Stunden automatisch Gold & XP sammeln.</p><button onclick="offline();render()">Wache abrechnen</button></div><div class="card"><h3>Aktivitäten</h3><button onclick="startCombat('dungeon')" ${S.lvl<10?'disabled':''}>🏰 Katakomben ${unlock(10)}</button><br><button onclick="startCombat('arena')" ${S.lvl<3?'disabled':''}>⚔️ Arena ${unlock(3)}</button></div><div class="card"><h3>Letzte Ereignisse</h3><div class="log">${S.log.map(x=>'• '+esc(x)).join('<br>')}</div></div></div>`}
function char(){let st=charStats(),sy=synergy(),r=RACES[S.race],c=CLASSES[S.cls],b=BG[S.bg];return `<section class="hero"><div class="row"><div><div class="small">CHARAKTEREDITOR · V1</div><h1>Dein Held</h1><div class="sub">Wähle Herkunft, Beruf und Vergangenheit. Deine Auswahl bildet die Grundlage für die späteren Kampf- und Progressionssysteme.</div></div><div style="font-size:58px">${r.icon}${c.icon}</div></div><div class="card" style="margin-top:14px"><label class="small">NAME DES HELDEN</label><input id="heroName" value="${esc(S.name)}" maxlength="24" oninput="setName(this.value)" style="width:100%;margin-top:6px;padding:12px;border-radius:12px;border:1px solid #ffffff18;background:#ffffff08;color:var(--text)"><div class="small" style="margin-top:5px">Maximal 24 Zeichen.</div></div><h2>1 · Volk</h2><div class="choice-grid">${Object.entries(RACES).map(([n,x])=>`<button class="choice ${S.race===n?'selected':''}" onclick="chooseRace('${n}')"><div class="choice-icon">${x.icon}</div><b>${n}</b><span>${Object.entries(x.bonus).map(([k,v])=>`+${v} ${k.toUpperCase()}`).join(' · ')}</span><small>${x.passive}<br>${x.effect}</small></button>`).join('')}</div><h2>2 · Klasse</h2><div class="choice-grid">${Object.entries(CLASSES).map(([n,x])=>`<button class="choice ${S.cls===n?'selected':''}" onclick="chooseClass('${n}')"><div class="choice-icon">${x.icon}</div><b>${n}</b><span>${x.role} · ${x.primary}</span><small>${x.res} · ${x.skill}<br>${x.desc}</small></button>`).join('')}</div><h2>3 · Hintergrund</h2><div class="choice-grid bg-grid">${Object.entries(BG).map(([n,x])=>`<button class="choice ${S.bg===n?'selected':''}" onclick="chooseBg('${n}')"><div class="choice-icon">${x.icon}</div><b>${n}</b><small>${x.effect}<br>${x.desc}</small></button>`).join('')}</div><div class="grid"><div class="card"><h3>Deine Attribute</h3><div class="statline"><span>STR</span><b>${st.str}</b></div><div class="statline"><span>AGI</span><b>${st.agi}</b></div><div class="statline"><span>INT</span><b>${st.int}</b></div><div class="statline"><span>HP</span><b>${st.hp}</b></div></div><div class="card"><h3>Passive</h3><p><b>${r.passive}</b></p><p class="small">${r.effect}</p><h3>Ressource</h3><p>${c.res}</p><p class="small">Signaturskill: ${c.skill}</p></div><div class="card"><h3>Volk-Klassen-Synergie</h3><p><span class="tag">${sy.level}</span></p><p class="small">${sy.text}</p><p><b>${S.race} + ${S.cls}</b></p></div></div><div class="hero" style="margin-top:14px"><div class="row"><div><div class="small">ZUSAMMENFASSUNG</div><h2 style="margin:3px 0">${esc(S.name)}</h2><div class="sub">${S.race} · ${S.cls} · ${S.bg}</div></div><div><button onclick="resetCharacter()">Zurücksetzen</button> <button onclick="createHero()">Held erstellen</button></div></div></div></section>`}
function inv(){return `<div class="hero"><h1>Rucksack</h1><div class="row"><span>${S.items.length}/${S.invCap} Plätze</span><button onclick="salvage()" ${S.lvl<5?'disabled':''}>♻️ Auto-Verwerten ${unlock(5)}</button></div></div><div class="card" style="margin-top:12px">${S.items.map(x=>`<div class="item"><div><b>${x.name}</b><div class="small">${x.slot} · Macht ${x.power}</div></div><span class="rarity ${x.rarity}">${x.rarity}</span></div>`).join('')}</div>`}
function forgeView(){return `<div class="hero"><h1>🔨 Ahnen-Schmiede</h1><p class="sub">Horizontale Progression: Mythisch ist das Stat-Cap. Legendär ★ bietet dasselbe Kampfwert-Niveau plus Stat-Swapping, Prestige-Aura und +15% Gold-Fund.</p><div class="actions"><button onclick="forge()">Aufwertung +1 · 80 Gold</button><button onclick="salvage()">Beute zerlegen → Staub</button></div></div><div class="grid"><div class="card"><h3>Ressourcen</h3><p>Entzauberungs-Staub: <b>${S.forgeDust}</b></p><p>Legendäre Essenzen: <b>${S.essence}</b></p><p>Seelensteine: <b>${S.souls}</b></p></div><div class="card"><h3>Legendäres Rezept ★</h3><p class="small">1× Mythische Basis +10<br>100× Legendäre Essenzen<br>50× Seelensteine<br>1× Relikt der Urahnen</p></div></div>`}
function arena(){return `<div class="hero"><h1>⚔️ Arena</h1><p>Asynchrones PvP. Wähle einen Gegner und eine Haltung.</p><div class="actions"><button onclick="startCombat('arena')">Einfach</button><button onclick="startCombat('arena')">Ebenbürtig</button><button onclick="startCombat('arena')">Herausforderer</button></div></div><div class="card" style="margin-top:12px"><h3>Haltungen</h3><span class="tag">Aggressiv +15% Crit / -10% Rüstung</span><span class="tag">Defensiv +20% Rüstung / -10% Schaden</span><span class="tag">Konter +15% Ausweichen & Konterschaden</span><p class="small">Dein Ruhm: ${S.arena} · Siege: ${S.wins} · Liga: Bronze</p></div>`}
function combat(){let c=S.combat;if(!c)return home();let hp=Math.max(0,S.hp),ep=Math.max(0,c.ehp);return `<div class="hero center"><div class="enemy">👹</div><h1>${c.enemy}</h1><div class="bar"><i style="width:${ep/c.max*100}%"></i></div><p>${ep}/${c.max} HP</p><hr><div class="enemy">${RACES[S.race].icon}</div><div class="bar"><i style="width:${hp/S.maxHp*100}%"></i></div><p>${hp}/${S.maxHp} HP</p><button onclick="fight()">⚔️ Angriff / Skill-Sequenz</button></div><div class="card" style="margin-top:12px"><h3>Kampfprotokoll</h3><div class="log">${S.log.slice(0,8).map(x=>'• '+esc(x)).join('<br>')}</div></div>`}
(function boot(){const style=document.createElement('style');style.textContent='.choice-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin:10px 0 18px}.choice{display:flex;flex-direction:column;align-items:flex-start;text-align:left;gap:6px;background:var(--panel);border:1px solid #ffffff10;box-shadow:none;min-height:150px}.choice.selected{border:2px solid var(--gold);background:linear-gradient(135deg,#38284d,#251b31)}.choice-icon{font-size:34px}.choice span{font-size:12px;color:var(--gold)}.choice small{font-size:11px;color:var(--muted);line-height:1.35}.statline{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #ffffff0d}.hero input:focus{outline:2px solid var(--accent)}h2{margin:20px 0 8px}@media(max-width:560px){.choice-grid{grid-template-columns:1fr}.choice{min-height:130px}.hero .row{align-items:flex-start}.hero .row>div:last-child{width:100%}}';document.head.appendChild(style);offline();render()})();