const RACES={Mensch:{bonus:{str:2,agi:2,int:2},passive:'Anpassungsfähigkeit',effect:'Permanent +10% XP-Gewinn',icon:'🧑',desc:'Ausgeglichen und anpassungsfähig.'},Elf:{bonus:{agi:4,int:2},passive:'Arkaner Reflex',effect:'+5% Ausweichen, +3% Krit-Chance',icon:'🧝',desc:'Schnell, präzise und arkan begabt.'},Zwerg:{bonus:{str:4,hp:20},passive:'Steinblut',effect:'Permanent +15% Rüstungswert',icon:'⛏️',desc:'Zäh und stark, gebaut für lange Kämpfe.'},Ork:{bonus:{str:5,agi:1},passive:'Blutrausch',effect:'+25% Schaden gegen Gegner unter 30% HP',icon:'👹',desc:'Brutale Kraft und unerbittlicher Angriff.'},Nachtläufer:{bonus:{agi:4,int:2},passive:'Schattenschritt',effect:'+5% Life-Steal, erster Schlag kritisch',icon:'🌙',desc:'Ein lautloser Jäger zwischen Schatten und Magie.'},Drachengeborener:{bonus:{str:3,int:3},passive:'Drachenatem',effect:'10% Chance auf Elementarbrand über 3 Runden',icon:'🐉',desc:'Träger uralter drakonischer Macht.'}};
const CLASSES={Krieger:{primary:'STR',res:'Wut',skill:'Schildwall',role:'Tank',icon:'🛡️',desc:'Robuster Frontkämpfer mit Schildwall und Wut.'},Magier:{primary:'INT',res:'Mana',skill:'Arkaner Meteor',role:'Burst',icon:'🔮',desc:'Magischer Burst-Schaden mit teilweiser Rüstungsignorierung.'},Druide:{primary:'Hybrid',res:'Naturfokus',skill:'Gestaltwechsel',role:'Hybrid',icon:'🌿',desc:'Wechselt zwischen Bär, Katze und Mensch.'},Waldläufer:{primary:'AGI',res:'Energie',skill:'Pfeilhagel',role:'Fernkampf',icon:'🏹',desc:'Hohe Angriffsfrequenz und Ausweichen.'},Hexenmeister:{primary:'INT/AGI',res:'Seelenfragmente',skill:'Seelenentzug',role:'Debuff',icon:'🕯️',desc:'Flüche, Debuffs und Life-Steal.'},Totenbeschwörer:{primary:'INT/STR',res:'Todesessenz',skill:'Skelett-Diener',role:'Beschwörer',icon:'💀',desc:'Beschwört Skelett-Diener, die Schaden abfangen.'}};
const BG={'Tavernen-Stammgast':{effect:'+15% Abenteuerlust-Effizienz',desc:'Du kennst jeden Winkel der Taverne.',icon:'🍺'},'Gefallener Adeliger':{effect:'+10% Gold aus allen Quellen',desc:'Alte Titel, neue Schulden und ein Händchen für Geschäfte.',icon:'👑'},'Runenschmied-Lehrling':{effect:'+10% Erfolgschance beim Aufwerten',desc:'Du hast die ersten Geheimnisse der Runenschmiede gelernt.',icon:'🔨'},'Schatten-Ausreißer':{effect:'+5% Beute-Glück',desc:'Du hast gelernt, dort Beute zu finden, wo andere nichts sehen.',icon:'🗝️'}};
const BASE={str:8,agi:8,int:8,hp:120};
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
let S=window.ARCANE_APP_STATE?.load?.()||{screen:'home',name:'Aventurier',race:'Mensch',cls:'Krieger',bg:'Tavernen-Stammgast',lvl:1,xp:0,gold:120,al:100,maxAl:100,hp:120,maxHp:120,str:8,agi:8,int:8,items:[{name:'Rostiges Schwert',slot:'Haupthand',power:4,rarity:'common'}],eq:{},invCap:15,forgeDust:0,essence:0,souls:0,keys:0,quests:0,wins:0,arena:0,skills:['Hieb','Schildwall','Mächtiger Schlag'],combat:null,log:['Willkommen in der Arcane Tavern.']};
function save(){return window.ARCANE_APP_STATE?.save?.(S)??false}
function xpNeed(){const lvl=Math.max(1,Math.min(50,Number(S.lvl)||1));return lvl>=50?0:Math.floor(80*Math.pow(1.10,lvl-1))}
function gainXP(amount){if((Number(S.lvl)||1)>=50){S.lvl=50;S.xp=0;return 0}S.xp=Math.max(0,Number(S.xp)||0)+Math.max(0,Math.floor(Number(amount)||0));let levels=0;while(S.lvl<50){const need=xpNeed();if(!need||S.xp<need)break;S.xp-=need;S.lvl++;levels++;S.maxHp=(Number(S.maxHp)||120)+10;S.hp=S.maxHp;S.str=(Number(S.str)||0)+1;S.agi=(Number(S.agi)||0)+1;S.int=(Number(S.int)||0)+1}if(S.lvl>=50){S.lvl=50;S.xp=0}return levels}
function unlock(level){return (Number(S.lvl)||1)>=level?'':` 🔒 ab Stufe ${level}`}
function log(message){if(!Array.isArray(S.log))S.log=[];S.log.unshift(String(message));S.log=S.log.slice(0,14)}
function toast(message){if(window.Arcane?.dialogs?.toast)return window.Arcane.dialogs.toast(message);alert(message)}
function offline(){return window.ARCANE_APP_STATE?.settleOffline?.()||false}
function reset(){if(confirm('Beta-Spielstand wirklich löschen?')){const storage=window.ARCANE_STORAGE||window.Arcane?.storage;if(storage?.clearGameData)storage.clearGameData();else try{localStorage.removeItem('arcaneBeta')}catch{}location.reload()}}
function tab(name){S.screen=name;render()}
function setName(value){S.name=String(value||'').slice(0,24)||'Aventurier'}
function chooseRace(value){if(RACES[value])S.race=value;render()}
function chooseClass(value){if(CLASSES[value])S.cls=value;render()}
function chooseBg(value){if(BG[value])S.bg=value;render()}
function resetCharacter(){S.name='Aventurier';S.race='Mensch';S.cls='Krieger';S.bg='Tavernen-Stammgast';render()}
function charStats(){const race=RACES[S.race]||RACES.Mensch,stats={...BASE};for(const [key,value] of Object.entries(race.bonus||{}))stats[key]=(stats[key]||0)+value;return stats}
function synergy(){const strong={Mensch:['Krieger','Druide'],Elf:['Magier','Waldläufer'],Zwerg:['Krieger','Totenbeschwörer'],Ork:['Krieger','Waldläufer'],Nachtläufer:['Hexenmeister','Waldläufer'],Drachengeborener:['Magier','Totenbeschwörer']};return strong[S.race]?.includes(S.cls)?{level:'Sehr hoch',text:'Diese Kombination unterstützt die Kernwerte und Spielweise besonders stark.'}:{level:'Solide',text:'Diese Kombination ist voll spielbar und bietet eine ausgewogene Mischung.'}}
function startCombat(kind='dungeon'){if(kind==='dungeon'&&S.lvl<10)return toast('Katakomben werden erst ab Stufe 10 freigeschaltet.');const hp=kind==='arena'?80+S.lvl*12:90+S.lvl*18;S.combat={kind,enemy:'Schattenbestie',ehp:hp,max:hp,round:0};S.screen='combat';render()}
function fight(){const c=S.combat;if(!c)return;let damage=Math.max(1,Math.floor(((Number(S.str)||0)+(Number(S.agi)||0)+(Number(S.int)||0))/3+4+Math.random()*10));if(S.cls==='Magier')damage+=8;c.ehp-=damage;c.round++;log(`Du triffst für ${damage} Schaden.`);if(c.ehp<=0){const reward=45+S.lvl*12;S.gold=(Number(S.gold)||0)+reward;gainXP(45+S.lvl*8);if(c.kind==='arena'){S.wins=(Number(S.wins)||0)+1;S.arena=(Number(S.arena)||0)+12}else{S.essence=(Number(S.essence)||0)+(Math.random()<.25?1:0);if(Math.random()<.3)S.keys=(Number(S.keys)||0)+1}log(`Sieg! +${reward} Gold.`);S.combat=null;S.screen='home';render();return}let enemyDamage=Math.max(2,Math.floor(8+S.lvl*2+Math.random()*7));if(S.cls==='Krieger')enemyDamage=Math.floor(enemyDamage*.8);S.hp=(Number(S.hp)||0)-enemyDamage;log(`Die Schattenbestie verursacht ${enemyDamage} Schaden.`);if(S.hp<=0){S.hp=Math.max(1,Math.floor((Number(S.maxHp)||120)*.35));S.gold=Math.max(0,(Number(S.gold)||0)-20);log('Du wurdest besiegt und wachst in der Taverne auf. -20 Gold.');S.combat=null;S.screen='home'}render()}
function forge(){if(S.lvl<5)return toast('Die Ahnenschmiede wird ab Stufe 5 freigeschaltet.');const item=S.items?.[0];if(!item)return toast('Kein Gegenstand zum Aufwerten vorhanden.');if(S.gold<80)return toast('80 Gold benötigt.');S.gold-=80;S.forgeDust=(Number(S.forgeDust)||0)+5;const success=Math.random()<.8;if(success)item.power=(Number(item.power)||1)+1;log(success?'Schmiede: Aufwertung gelungen.':'Schmiede: Aufwertung fehlgeschlagen.');render()}
function salvage(){const keep=(S.items||[]).find(x=>x.name==='Rostiges Schwert'),salvageable=(S.items||[]).filter(x=>x!==keep);if(!salvageable.length)return toast('Keine Beute zum Verwerten.');S.items=keep?[keep]:[];S.forgeDust=(Number(S.forgeDust)||0)+salvageable.length*3;log(`Auto-Verwerten: ${salvageable.length} Items → ${salvageable.length*3} Staub.`);render()}
function render(){const app=document.getElementById('app');if(app&&!app.firstElementChild)app.innerHTML='<main><div class="card">Arcane Quest wird geladen …</div></main>'}
function home(){return '<section class="card"><h1>Arcane Quest</h1><p>Die Taverne wird geladen …</p></section>'}
function char(){return '<section class="card"><h1>Held</h1></section>'}
function inv(){return '<section class="card"><h1>Inventar</h1></section>'}
function forgeView(){return '<section class="card"><h1>Ahnenschmiede</h1></section>'}
function arena(){return '<section class="card"><h1>Arena</h1></section>'}
function combat(){const c=S.combat;if(!c)return home();return `<section class="card"><h1>${esc(c.enemy)}</h1><p>${Math.max(0,c.ehp)} / ${c.max} HP</p><button onclick="fight()">Angreifen</button></section>`}
window.Arcane=window.Arcane||{};window.Arcane.bootstrap={version:'bootstrap-v2',state:()=>S};
