const RACES={Mensch:{bonus:'STR +2 / AGI +2 / INT +2',passive:'+10% XP'},Elf:{bonus:'AGI +4 / INT +2',passive:'+5% Ausweichen, +3% Krit'},Zwerg:{bonus:'STR +4 / HP +2',passive:'+15% Rüstung'},Ork:{bonus:'STR +5 / AGI +1',passive:'+25% Schaden <30% HP'},Nachtläufer:{bonus:'AGI +4 / INT +2',passive:'+5% Life-Steal, 1. Schlag kritisch'},Drachengeborener:{bonus:'STR +3 / INT +3',passive:'10% Elementarbrand'}};
const CLASSES={Krieger:{stat:'STR',res:'Wut',skill:'Schildwall'},Magier:{stat:'INT',res:'Mana',skill:'Arkaner Meteor'},Druide:{stat:'Hybrid',res:'Naturfokus',skill:'Gestaltwechsel'},Waldläufer:{stat:'AGI',res:'Energie',skill:'Pfeilhagel'},Hexenmeister:{stat:'INT/AGI',res:'Seelenfragmente',skill:'Seelenentzug'},Totenbeschwörer:{stat:'INT/STR',res:'Todesessenz',skill:'Skelett-Diener'}};
const BG={"Tavernen-Stammgast":'+15% Abenteuerlust-Effizienz',"Gefallener Adeliger":'+10% Gold aus allen Quellen',"Runenschmied-Lehrling":'+10% Schmiede-Erfolg',"Schatten-Ausreißer":'+5% Beute-Glück'};
let S=JSON.parse(localStorage.getItem('arcaneBeta')||'null')||{screen:'home',name:'Aventurier',race:'Mensch',cls:'Krieger',bg:'Tavernen-Stammgast',lvl:1,xp:0,gold:120,al:100,maxAl:100,hp:120,maxHp:120,str:8,agi:8,int:8,items:[{name:'Rostiges Schwert',slot:'Haupthand',power:4,rarity:'common'}],eq:{},invCap:15,forgeDust:0,essence:0,souls:0,keys:0,quests:0,wins:0,arena:0,skills:['Hieb','Schildwall','Mächtiger Schlag'],combat:null,log:['Willkommen in der Arcane Tavern.']};
function save(){localStorage.setItem('arcaneBeta',JSON.stringify(S));}
function xpNeed(){return Math.floor(80*Math.pow(1.16,S.lvl-1))} function unlock(l){return S.lvl>=l?'':' 🔒 ab Stufe '+l} function gainXP(n){S.xp+=n;let up=0;while(S.xp>=xpNeed()){S.xp-=xpNeed();S.lvl++;up++;S.maxHp+=10;S.hp=S.maxHp;S.str++;S.agi++;S.int++;}return up}
function log(x){S.log.unshift(x);S.log=S.log.slice(0,14)}
function quest(type){if(S.al<=0)return toast('Keine Abenteuerlust mehr.');let cost=type==='risk'?28:type==='event'?18:12;S.al=Math.max(0,S.al-cost);let xp=Math.floor(24+S.lvl*7), gold=Math.floor((type==='risk'?95:35)+Math.random()*45);if(type==='event'){let stat=['str','agi','int'][Math.floor(Math.random()*3)];let ok=S[stat]>=S.lvl+7; gold=ok?gold*2:Math.floor(gold*.4);log(`Event-Quest: ${stat.toUpperCase()}-Check ${ok?'erfolgreich':'fehlgeschlagen'}.`)}S.gold+=gold;let up=gainXP(xp);S.quests++;if(Math.random()<.22){S.items.push({name:'Abenteuer-Beute',slot:['Ring','Gürtel','Stiefel'][Math.floor(Math.random()*3)],power:2+S.lvl,rarity:Math.random()<.75?'magic':'rare'})}log(`Quest abgeschlossen: +${gold} Gold, +${xp} XP${up?' — Level Up!':''}`);render()}
function startCombat(kind='dungeon'){if(kind==='dungeon'&&S.lvl<10)return toast('Dungeons werden erst ab Stufe 10 freigeschaltet.');let hp=kind==='arena'?80+S.lvl*12:90+S.lvl*18;S.combat={kind,enemy:'Schattenbestie',ehp:hp,max:hp,round:0,playerTurn:true};S.screen='combat';render()}
function fight(){let c=S.combat;if(!c)return;let dmg=Math.max(1,Math.floor((S.str+S.agi+S.int)/3+4+Math.random()*10));if(S.cls==='Magier')dmg+=8;if(S.cls==='Waldläufer')dmg+=4;c.ehp-=dmg;c.round++;log(`Du triffst für ${dmg} Schaden.`);if(c.ehp<=0){let reward=45+S.lvl*12;S.gold+=reward;gainXP(45+S.lvl*8);if(c.kind==='arena'){S.wins++;S.arena+=12}else{S.essence+=Math.random()<.25?1:0;if(Math.random()<.3)S.keys++;}log(`Sieg! +${reward} Gold.`);S.combat=null;S.screen='home';render();return}let edmg=Math.max(2,Math.floor(8+S.lvl*2+Math.random()*7));if(S.cls==='Krieger')edmg=Math.floor(edmg*.8);S.hp-=edmg;log(`Die Schattenbestie verursacht ${edmg} Schaden.`);if(S.hp<=0){S.hp=Math.floor(S.maxHp*.35);S.gold=Math.max(0,S.gold-20);log('Du wurdest besiegt und wachst in der Taverne auf. -20 Gold.');S.combat=null;S.screen='home'}render()}
function forge(){if(S.lvl<5)return toast('Die Ahnen-Schmiede wird ab Stufe 5 freigeschaltet.');if(S.gold<80)return toast('80 Gold benötigt.');S.gold-=80;S.forgeDust+=5;let up=Math.random()<.8;log(up?'Schmiede: Aufwertung gelungen.':'Schmiede: Aufwertung fehlgeschlagen.');if(up)S.items[0].power++;render()}
function salvage(){let n=S.items.filter(x=>x.name!=='Rostiges Schwert').length;if(!n)return toast('Keine Beute zum Verwerten.');S.items=S.items.slice(0,1);S.forgeDust+=n*3;log(`Auto-Verwerten: ${n} Items → ${n*3} Staub.`);render()}
function offline(){let last=+localStorage.getItem('arcaneLast')||Date.now();let h=Math.min(12,(Date.now()-last)/3600000);if(h>.03){let g=Math.floor(h*18);let x=Math.floor(h*10);S.gold+=g;gainXP(x);log(`Wachdienst: ${h.toFixed(1)}h offline → +${g} Gold, +${x} XP.`)}localStorage.setItem('arcaneLast',Date.now())}
function toast(t){alert(t)}
function reset(){if(confirm('Beta-Spielstand wirklich löschen?')){localStorage.removeItem('arcaneBeta');location.reload()}}
function tab(name){S.screen=name;render()}
function render(){save();let xp=xpNeed();let unlocked=S.lvl>=3;document.getElementById('app').innerHTML=`<header><div class="top"><div class="brand">🍺 Arcane Tavern & Quest <span class="small">BETA</span></div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span><span class="pill">⚡ ${S.al}/${S.maxAl}</span><span class="pill">🜂 ${S.souls}</span></div></div></header><main>${S.screen==='home'?home():S.screen==='char'?char():S.screen==='inv'?inv():S.screen==='forge'?forgeView():S.screen==='arena'?arena():S.screen==='combat'?combat():home()}</main><nav class="tabs">${[['home','🍺','Taverne'],['char','🧙','Held'],['inv','🎒','Rucksack'],['forge','🔨','Schmiede'],['arena','⚔️','Arena']].map(x=>`<button class="${S.screen===x[0]?'active':''}" onclick="tab('${x[0]}')">${x[1]}<br>${x[2]}</button>`).join('')}</nav>`}
function home(){let p=Math.min(100,S.xp/xpNeed()*100);return `<section class="hero"><h1>Willkommen, ${S.name}.</h1><div class="sub">Das Arkane Herz pulsiert unter deiner Taverne. Deine Reise beginnt jetzt.</div><div class="actions"><button onclick="quest('std')">📜 Standard-Raubzug · 12 AL</button><button onclick="quest('event')">🎲 Event-Quest · 18 AL</button><button onclick="quest('risk')">💰 Risiko-Quest · 28 AL</button></div></section><div class="grid"><div class="card"><h3>Fortschritt</h3><div class="row"><span>Stufe ${S.lvl}</span><b>${S.xp}/${xpNeed()} XP</b></div><div class="bar"><i style="width:${p}%"></i></div><p class="small">Feature-Gating: Arena ab 3 · Schmiede ab 5 · Dungeon ab 10 · Gilde ab 15 · Reinkarnation ab 100.</p></div><div class="card"><h3>Offline-Wachdienst</h3><p>Bis zu 12 Stunden automatisch Gold & XP sammeln.</p><button onclick="offline();render()">Wache abrechnen</button></div><div class="card"><h3>Aktivitäten</h3><button onclick="startCombat('dungeon')" ${S.lvl<10?'disabled':''}>🏰 Katakomben ${unlock(10)}</button><br><button onclick="startCombat('arena')" ${S.lvl<3?'disabled':''}>⚔️ Arena ${unlock(3)}</button></div><div class="card"><h3>Letzte Ereignisse</h3><div class="log">${S.log.map(x=>'• '+x).join('<br>')}</div></div></div>`}
function char(){return `<div class="hero"><h1>Charaktereditor</h1><div class="grid"><div class="card"><h3>Volk</h3><select id="race" onchange="S.race=this.value;render()">${Object.keys(RACES).map(x=>`<option ${S.race===x?'selected':''}>${x}</option>`).join('')}</select><p class="small">${RACES[S.race].bonus}<br>${RACES[S.race].passive}</p></div><div class="card"><h3>Klasse</h3><select onchange="S.cls=this.value;render()">${Object.keys(CLASSES).map(x=>`<option ${S.cls===x?'selected':''}>${x}</option>`).join('')}</select><p class="small">${CLASSES[S.cls].stat} · Ressource: ${CLASSES[S.cls].res}<br>Signaturskill: ${CLASSES[S.cls].skill}</p></div><div class="card"><h3>Hintergrund</h3><select onchange="S.bg=this.value;render()">${Object.keys(BG).map(x=>`<option ${S.bg===x?'selected':''}>${x}</option>`).join('')}</select><p class="small">${BG[S.bg]}</p></div></div></div>`}
function inv(){return `<div class="hero"><h1>Rucksack</h1><div class="row"><span>${S.items.length}/${S.invCap} Plätze</span><button onclick="salvage()" ${S.lvl<5?'disabled':''}>♻️ Auto-Verwerten ${unlock(5)}</button></div></div><div class="card" style="margin-top:12px">${S.items.map((x,i)=>`<div class="item"><div><b>${x.name}</b><div class="small">${x.slot} · Macht ${x.power}</div></div><span class="rarity ${x.rarity}">${x.rarity}</span></div>`).join('')}</div>`}
function forgeView(){return `<div class="hero"><h1>🔨 Ahnen-Schmiede</h1><p class="sub">Horizontale Progression: Mythisch ist das Stat-Cap. Legendär ★ bietet dasselbe Kampfwert-Niveau plus Stat-Swapping, Prestige-Aura und +15% Gold-Fund.</p><div class="actions"><button onclick="forge()">Aufwertung +1 · 80 Gold</button><button onclick="salvage()">Beute zerlegen → Staub</button></div></div><div class="grid"><div class="card"><h3>Ressourcen</h3><p>Entzauberungs-Staub: <b>${S.forgeDust}</b></p><p>Legendäre Essenzen: <b>${S.essence}</b></p><p>Seelensteine: <b>${S.souls}</b></p></div><div class="card"><h3>Legendäres Rezept ★</h3><p class="small">1× Mythische Basis +10<br>100× Legendäre Essenzen<br>50× Seelensteine<br>1× Relikt der Urahnen</p></div></div>`}
function arena(){return `<div class="hero"><h1>⚔️ Arena</h1><p>Asynchrones PvP. Wähle einen Gegner und eine Haltung.</p><div class="actions"><button onclick="startCombat('arena')">Einfach</button><button onclick="startCombat('arena')">Ebenbürtig</button><button onclick="startCombat('arena')">Herausforderer</button></div></div><div class="card" style="margin-top:12px"><h3>Haltungen</h3><span class="tag">Aggressiv +15% Crit / -10% Rüstung</span><span class="tag">Defensiv +20% Rüstung / -10% Schaden</span><span class="tag">Konter +15% Ausweichen & Konterschaden</span><p class="small">Dein Ruhm: ${S.arena} · Siege: ${S.wins} · Liga: Bronze</p></div>`}
function combat(){let c=S.combat;if(!c)return home();let hp=Math.max(0,S.hp),ep=Math.max(0,c.ehp);return `<div class="hero center"><div class="enemy">👹</div><h1>${c.enemy}</h1><div class="bar"><i style="width:${ep/c.max*100}%"></i></div><p>${ep}/${c.max} HP</p><hr><div class="enemy">🧙</div><div class="bar"><i style="width:${hp/S.maxHp*100}%"></i></div><p>${hp}/${S.maxHp} HP</p><button onclick="fight()">⚔️ Angriff / Skill-Sequenz</button></div><div class="card" style="margin-top:12px"><h3>Kampfprotokoll</h3><div class="log">${S.log.slice(0,8).map(x=>'• '+x).join('<br>')}</div></div>`}
offline();render();
