(()=>{
const oldQStart=window.qStart,oldHome=window.home;
const BOSS={name:'Der Knochenhauer',icon:'💀',maxHp:78,baseDamage:9};
const CLASS_ACTIONS={Krieger:{name:'Schildwall',icon:'🛡️',stat:'str',desc:'Starker Block mit Gegenangriff.'},Magier:{name:'Arkaner Meteor',icon:'☄️',stat:'int',desc:'Hoher magischer Schaden.'},Druide:{name:'Gestaltwechsel',icon:'🌿',stat:'int',desc:'Heilt und stärkt die nächste Aktion.'},Waldläufer:{name:'Pfeilhagel',icon:'🏹',stat:'agi',desc:'Mehrere schnelle Treffer.'},Hexenmeister:{name:'Seelenentzug',icon:'🕯️',stat:'int',desc:'Schaden und Lebensraub.'},Totenbeschwörer:{name:'Skelett-Diener',icon:'💀',stat:'int',desc:'Diener fängt Schaden ab.'}};
function stat(k){let v=Number(S[k])||8;try{v+=RACES?.[S.race]?.bonus?.[k]||0}catch{}return v}
function clamp(n,a,b){return Math.max(a,Math.min(b,n))}
function chance(base,k){let c=base+(stat(k)-8)*3;if(k==='agi'&&['Elf','Nachtläufer'].includes(S.race))c+=5;if(k==='str'&&['Zwerg','Ork'].includes(S.race))c+=5;if(k==='int'&&['Elf','Drachengeborener'].includes(S.race))c+=4;if(S.race==='Mensch')c+=2;return clamp(Math.round(c),18,92)}
function roll(p){const r=Math.floor(Math.random()*100)+1;return {r,ok:r<=p,crit:r<=Math.max(5,Math.floor(p*.12))}}
function startBounty(){if(S.quest||S.bountyCombat)return;if(S.al<24)return toast('Nicht genug Abenteuerlust. Benötigt: 24 AL.');S.al-=24;S.bountyCombat={bossHp:BOSS.maxHp,playerHp:Math.max(1,S.hp||S.maxHp||120),round:1,feedback:null,history:[],buff:0};S.screen='home';log('Kopfgeld gestartet: Der Knochenhauer stellt sich dir entgegen.');save();render()}
window.qStart=function(id,e){if(e)e.stopPropagation();if(id==='bounty')return startBounty();return oldQStart?.(id,e)};
function enemyTurn(mode){const c=S.bountyCombat;if(!c||c.bossHp<=0)return;let dodge=mode==='dodge'?chance(48,'agi'):0,block=mode==='block'?chance(52,'str'):0;let raw=BOSS.baseDamage+Math.floor(Math.random()*7)+Math.floor(S.lvl/2),text='';if(mode==='dodge'){const rr=roll(dodge);if(rr.ok){text=`Du weichst dem Gegenangriff aus (${dodge}% Chance).`;raw=0}else{text=`Ausweichen fehlgeschlagen (${dodge}% Chance).`}}else if(mode==='block'){const rr=roll(block);if(rr.ok){raw=Math.max(1,Math.floor(raw*.3));text=`Block erfolgreich (${block}% Chance).`}else{text=`Block fehlgeschlagen (${block}% Chance).`}}else if(c.guard){raw=Math.floor(raw*.35);text='Dein Diener fängt einen Großteil des Schadens ab.';c.guard=false}else text='Der Knochenhauer schlägt zurück.';c.playerHp=Math.max(0,c.playerHp-raw);return {raw,text}}
function action(type){const c=S.bountyCombat;if(!c||c.feedback)return;let title='',body='',tone='good',damage=0,heal=0,defMode=null;const str=stat('str'),agi=stat('agi'),int=stat('int');if(type==='attack'){let p=chance(68,'str'),rr=roll(p);if(rr.ok){damage=Math.max(4,Math.floor(str*1.15+5+Math.random()*6))*(rr.crit?2:1);title=rr.crit?'Kritischer Treffer':'Treffer';body=`Dein Angriff trifft (${p}% Chance) und verursacht ${damage} Schaden.`}else{title='Angriff verfehlt';body=`Der Knochenhauer entgeht deinem Angriff (${p}% Chance).`;tone='bad'}}
if(type==='block'){defMode='block';damage=Math.max(1,Math.floor(str*.45));title='Defensive Haltung';body='Du bereitest einen Block vor und setzt einen kurzen Gegenstoß.'}
if(type==='dodge'){defMode='dodge';let p=chance(58,'agi'),rr=roll(p);if(rr.ok){damage=Math.max(2,Math.floor(agi*.7));title='Schneller Konter';body=`Du bringst dich in Position und verursachst ${damage} Schaden.`}else{title='Ausweichmanöver';body='Du konzentrierst dich vollständig auf den nächsten gegnerischen Angriff.'}}
if(type==='class'){const a=CLASS_ACTIONS[S.cls]||CLASS_ACTIONS.Krieger,p=chance(58,a.stat),rr=roll(p);if(S.cls==='Krieger'){defMode='block';if(rr.ok){damage=Math.floor(str*.9)+6;title='Schildwall';body=`Schildwall gelingt (${p}% Chance). ${damage} Gegenschaden.`}else{title='Schildwall instabil';body=`Die Technik gelingt nur teilweise (${p}% Chance).`;tone='bad'}}else if(S.cls==='Magier'){if(rr.ok){damage=Math.floor(int*1.5)+10;title='Arkaner Meteor';body=`Der Meteor trifft für ${damage} Schaden (${p}% Chance).`}else{title='Zauber verpufft';body=`Der arkane Fokus bricht ab (${p}% Chance).`;tone='bad'}}else if(S.cls==='Druide'){heal=Math.floor(int*.8)+10;c.buff=1;title='Gestaltwechsel';body=`Du regenerierst ${heal} HP und stärkst deine nächste Attacke.`}else if(S.cls==='Waldläufer'){if(rr.ok){damage=Math.floor(agi*1.25)+8;title='Pfeilhagel';body=`Mehrere Pfeile treffen für insgesamt ${damage} Schaden.`}else{title='Pfeilhagel verfehlt';body='Der Boss durchbricht deine Schusslinie.';tone='bad'}}else if(S.cls==='Hexenmeister'){if(rr.ok){damage=Math.floor(int*1.05)+7;heal=Math.floor(damage*.45);title='Seelenentzug';body=`Du verursachst ${damage} Schaden und raubst ${heal} HP.`}else{title='Fluch widerstanden';body='Der Knochenhauer widersteht deinem Seelenentzug.';tone='bad'}}else{c.guard=true;if(rr.ok){damage=Math.floor(int*.8)+5;title='Skelett-Diener';body=`Dein Diener greift an (${damage} Schaden) und schützt dich.`}else{title='Diener beschworen';body='Der Diener erscheint verspätet, kann aber den nächsten Treffer abfangen.'}}}
if(c.buff&&damage>0&&type!=='class'){damage=Math.floor(damage*1.4);c.buff=0;body+=` Naturfokus verstärkt den Treffer auf ${damage}.`}c.bossHp=Math.max(0,c.bossHp-damage);c.playerHp=Math.min(S.maxHp||120,c.playerHp+heal);let enemy=null;if(c.bossHp>0)enemy=enemyTurn(defMode);if(enemy?.raw>0)body+=` ${enemy.text} Du erleidest ${enemy.raw} Schaden.`;else if(enemy?.text)body+=` ${enemy.text}`;c.history.unshift(`${title}: ${body}`);c.feedback={title,body,tone};if(c.playerHp<=0){c.feedback={title:'Niederlage',body:'Der Knochenhauer zwingt dich zum Rückzug. Das Kopfgeld ist gescheitert.',tone:'bad',end:'lose'}}else if(c.bossHp<=0)c.feedback={title:'Kopfgeld erfüllt',body:'Der Knochenhauer fällt. Du kannst deine Belohnung einsammeln.',tone:'great',end:'win'};else c.round++;save();render()}
function next(){if(S.bountyCombat?.feedback?.end==='win')return win();if(S.bountyCombat?.feedback?.end==='lose')return lose();if(S.bountyCombat)S.bountyCombat.feedback=null;save();render()}
function win(){const c=S.bountyCombat,gold=100+Math.floor(Math.random()*61),xp=65;S.gold+=gold;const levels=gainXP(xp);S.essence=(S.essence||0)+1;let item=null;if(S.items.length<S.invCap){item={name:'Knochenhauer-Trophäe',slot:'Beute',power:S.lvl+4,rarity:'rare'};S.items.push(item)}S.hp=Math.max(1,c.playerHp);S.quests++;S.bountyCombat=null;S.questResult={name:'Der Knochenhauer',icon:'💀',cat:'KOPFGELD',gold,xp,levels,material:1,item:item?.name||null};log(`Kopfgeld erfüllt: +${gold} Gold, +${xp} XP.`);save();render()}
function lose(){S.hp=Math.max(1,Math.floor((S.maxHp||120)*.35));S.bountyCombat=null;log('Kopfgeld gescheitert. Du kehrst verwundet in die Taverne zurück.');save();render()}
function view(){const c=S.bountyCombat;if(!c)return oldHome();const hp=Math.max(0,c.playerHp),bhp=Math.max(0,c.bossHp),a=CLASS_ACTIONS[S.cls]||CLASS_ACTIONS.Krieger;if(c.feedback)return `<section class="bc-wrap"><div class="bc-feedback ${c.feedback.tone}"><div class="bc-ficon">${c.feedback.tone==='bad'?'✕':c.feedback.tone==='great'?'★':'✓'}</div><div class="eyebrow">RUNDE ${c.round}</div><h2>${c.feedback.title}</h2><p>${c.feedback.body}</p><button onclick="bcNext()">${c.feedback.end==='win'?'Belohnung einsammeln':c.feedback.end==='lose'?'Zur Taverne':'Weiter'}</button></div></section>`;return `<section class="bc-wrap"><div class="bc-head"><div><div class="eyebrow">KOPFGELD · RUNDE ${c.round}</div><h1>${BOSS.icon} ${BOSS.name}</h1></div><span class="bc-badge">MINI-BOSS</span></div><div class="bc-bars"><div><span>${BOSS.name}</span><b>${bhp}/${BOSS.maxHp}</b><i><em style="width:${bhp/BOSS.maxHp*100}%"></em></i></div><div><span>${S.name}</span><b>${hp}/${S.maxHp||120}</b><i><em style="width:${hp/(S.maxHp||120)*100}%"></em></i></div></div><div class="bc-actions"><button onclick="bcAct('attack')"><span>⚔️</span><b>Angreifen</b><small>STR · ${chance(68,'str')}%</small></button><button onclick="bcAct('block')"><span>🛡️</span><b>Blocken</b><small>STR · ${chance(52,'str')}%</small></button><button onclick="bcAct('dodge')"><span>💨</span><b>Ausweichen</b><small>AGI · ${chance(48,'agi')}%</small></button><button onclick="bcAct('class')"><span>${a.icon}</span><b>${a.name}</b><small>${a.stat.toUpperCase()} · ${chance(58,a.stat)}%</small></button></div><div class="bc-note">Wähle eine Aktion. Treffer, Block und Ausweichen werden im Hintergrund zufällig ausgewertet.</div></section>`}
window.bcAct=action;window.bcNext=next;window.home=view;
const style=document.createElement('style');style.textContent=`.bc-wrap{max-width:650px;margin:0 auto}.bc-head{display:flex;justify-content:space-between;align-items:center;background:var(--panel);padding:12px;border-radius:15px;border:1px solid #ffffff10}.bc-head h1{font-size:19px;margin:2px 0}.bc-badge{font-size:8px;color:var(--danger);border:1px solid #e86a7a55;border-radius:999px;padding:5px 7px}.bc-bars{display:grid;gap:7px;margin:9px 0}.bc-bars>div{background:var(--panel);border-radius:12px;padding:8px 10px}.bc-bars span,.bc-bars b{font-size:10px}.bc-bars b{float:right}.bc-bars i{display:block;clear:both;height:7px;background:#ffffff0b;border-radius:99px;overflow:hidden;margin-top:5px}.bc-bars em{display:block;height:100%;background:linear-gradient(90deg,var(--danger),var(--gold))}.bc-actions{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.bc-actions button{display:grid;grid-template-columns:30px 1fr;grid-template-rows:auto auto;text-align:left;align-items:center;padding:10px;background:var(--panel);border:1px solid #ffffff10;box-shadow:none}.bc-actions button>span{grid-row:1/3;font-size:21px}.bc-actions b{font-size:11px}.bc-actions small{font-size:8px;color:var(--gold)}.bc-note{font-size:8px;color:var(--muted);text-align:center;margin-top:8px}.bc-feedback{max-width:430px;margin:30px auto;background:var(--panel);border:1px solid #ffffff14;border-radius:18px;padding:18px;text-align:center}.bc-feedback.good{border-color:#71d59a55}.bc-feedback.great{border-color:#f4c15d77}.bc-feedback.bad{border-color:#e86a7a66}.bc-ficon{font-size:34px}.bc-feedback h2{margin:4px 0;font-size:19px}.bc-feedback p{color:var(--muted);font-size:11px;line-height:1.45}.bc-feedback button{width:100%}@media(max-width:430px){.bc-actions{grid-template-columns:1fr 1fr}.bc-head h1{font-size:17px}}`;document.head.appendChild(style);
if(S.bountyCombat&&S.screen==='home')render();
})();