(()=>{
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const rarity=v=>String(v||'common').toLowerCase();
window.char=function(){
 const r=RACES[S.race]||RACES.Mensch,c=CLASSES[S.cls]||CLASSES.Krieger,b=BG[S.bg]||BG['Tavernen-Stammgast'];
 const base={str:8,agi:8,int:8,hp:120};Object.entries(r.bonus||{}).forEach(([k,v])=>base[k]=(base[k]||0)+v);
 const equipped=S.eq&&Object.keys(S.eq).length?Object.values(S.eq):[];
 const slots=['Kopf','Brust','Schultern','Handschuhe','Beine','Stiefel','Haupthand','Nebenhand'];
 const slotMap={};equipped.forEach(x=>{if(x&&x.slot)slotMap[x.slot]=x});
 const gear=slots.map(slot=>{const x=slotMap[slot];return `<div class="profile-gear"><span class="profile-slot">${slot}</span><span>${x?esc(x.name):'—'}</span><b>${x?`+${x.power||0}`:''}</b></div>`}).join('');
 const items=(S.items||[]).map(x=>`<div class="profile-item"><div><b>${esc(x.name)}</b><div class="small">${esc(x.slot||'Gegenstand')} · Macht ${x.power||0}</div></div><span class="rarity ${rarity(x.rarity)}">${esc(x.rarity||'common')}</span></div>`).join('')||'<div class="small">Dein Inventar ist leer.</div>';
 return `<section class="profile-page"><div class="hero profile-hero"><div class="profile-avatar">${r.icon}${c.icon}</div><div class="profile-main"><div class="small">CHARAKTER</div><h1>${esc(S.name)}</h1><div class="sub">Stufe ${S.lvl} · ${esc(S.race)} · ${esc(S.cls)}</div><div class="profile-tags"><span class="tag">${esc(S.bg)}</span><span class="tag">${esc(c.role)}</span><span class="tag">${esc(c.res)}</span></div></div></div><div class="grid profile-grid"><div class="card"><h3>Attribute</h3><div class="profile-stat"><span>STR</span><b>${base.str}</b></div><div class="profile-stat"><span>AGI</span><b>${base.agi}</b></div><div class="profile-stat"><span>INT</span><b>${base.int}</b></div><div class="profile-stat"><span>HP</span><b>${S.maxHp}</b></div></div><div class="card"><h3>Passive & Klasse</h3><p><b>${esc(r.passive)}</b></p><p class="small">${esc(r.effect)}</p><hr><p><b>${esc(c.skill)}</b></p><p class="small">${esc(c.res)} · ${esc(c.role)}</p></div><div class="card"><h3>Hintergrund</h3><p><b>${esc(S.bg)}</b></p><p class="small">${esc(b.effect)}</p></div></div><div class="card profile-section"><div class="row"><h3>Ausrüstung</h3><span class="small">Angelegt</span></div>${gear}</div><div class="card profile-section"><div class="row"><h3>Inventar</h3><span class="small">${(S.items||[]).length}/${S.invCap||15}</span></div>${items}</div><div class="card profile-section"><div class="row"><h3>Fertigkeiten</h3><span class="small">Vorschau</span></div><div class="profile-skills">${(S.skills||[]).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div><p class="small">Das vollständige Fertigkeiten-System folgt in einer späteren Version.</p></div></section>`;
};
const s=document.createElement('style');s.textContent=`.profile-page{padding-bottom:8px}.profile-hero{display:flex;gap:18px;align-items:center}.profile-avatar{width:92px;height:92px;border-radius:24px;background:#ffffff0b;display:grid;place-items:center;font-size:44px;flex:none;border:1px solid #ffffff12}.profile-main h1{margin:3px 0;font-size:30px}.profile-tags{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px}.profile-grid{margin-top:12px}.profile-stat{display:flex;justify-content:space-between;padding:9px 0;border-bottom:1px solid #ffffff0d}.profile-section{margin-top:12px}.profile-section hr{border:0;border-top:1px solid #ffffff0d;margin:12px 0}.profile-gear{display:grid;grid-template-columns:110px 1fr 40px;gap:8px;padding:10px 0;border-bottom:1px solid #ffffff0d;align-items:center}.profile-slot{color:var(--muted);font-size:12px}.profile-item{display:flex;justify-content:space-between;gap:10px;padding:11px 0;border-bottom:1px solid #ffffff0d}.profile-skills{display:flex;flex-wrap:wrap;gap:5px}@media(max-width:560px){.profile-hero{align-items:flex-start}.profile-avatar{width:76px;height:76px;font-size:36px}.profile-main h1{font-size:25px}.profile-grid{grid-template-columns:1fr}.profile-gear{grid-template-columns:90px 1fr 30px}}`;
document.head.appendChild(s);
})();