(()=>{
let o=JSON.parse(localStorage.getItem('arcaneBeta')||'null')||{},draft={name:o.name||'',race:o.race||'Mensch',cls:o.cls||'Krieger',bg:o.bg||'Tavernen-Stammgast'};
const oldName=window.cgName,oldPick=window.cgPick,oldNext=window.cgNext;
if(!oldNext)return;
window.cgName=v=>{draft.name=v;oldName(v)};
window.cgPick=(t,n)=>{draft[t==='race'?'race':t==='class'?'cls':'bg']=n;oldPick(t,n)};
const strengths={Mensch:['Anpassungsfähigkeit','vielseitigen Proben','kaum ausgeprägte Schwächen'],Elf:['schnelle Reflexe','Ausweichen und arkanen Aufgaben','direkter körperlicher Gewalt'],Zwerg:['außergewöhnliche Zähigkeit','Blocken und Durchbrechen','subtilen Ausweichmanövern'],Ork:['enorme Körperkraft','Einschüchtern und Durchbrechen','feinen arkanen Lösungen'],Nachtläufer:['Beweglichkeit und Heimlichkeit','Verstecken und Ausweichen','offenem Kraftvergleich'],Drachengeborener:['arkane und körperliche Präsenz','magischen Proben und Standhalten','reiner Heimlichkeit']};
const classes={Krieger:['entschlossener Frontkämpfer','STR','Blocken, Standhalten und direkte Konfrontationen'],Magier:['Meister arkaner Kräfte','INT','Runen, Resonanz und magische Lösungen'],Druide:['anpassungsfähiger Grenzgänger','Hybrid','flexible Entscheidungen zwischen Kraft, Instinkt und Wissen'],Waldläufer:['beweglicher Spurenleser','AGI','Schleichen, Ausweichen und taktische Wege'],Hexenmeister:['berechnender Nutzer dunkler Magie','INT','arkane Manipulation und ungewöhnliche Lösungen'],Totenbeschwörer:['beharrlicher Beschwörer','INT','Wissen, Kontrolle und widerstandsfähige Strategien']};
const bg={'Tavernen-Stammgast':'Durch deine Zeit in der Taverne weißt du, wie man aus begrenzter Abenteuerlust möglichst viel herausholt.','Gefallener Adeliger':'Deine Vergangenheit im Adel hat dir ein Gespür für Wert, Handel und Gold eingebracht.','Runenschmied-Lehrling':'Deine Ausbildung an der Schmiede wird dir später beim Verbessern deiner Ausrüstung helfen.','Schatten-Ausreißer':'Dein Leben abseits sicherer Wege schärfte deinen Blick für seltene Beute und verborgene Chancen.'};
function story(){let r=strengths[draft.race]||strengths.Mensch,c=classes[draft.cls]||classes.Krieger,n=draft.name||'Dein Held';return `${n} beginnt die Reise als ${draft.race} und ${c[0]}. Besonders prägend sind ${r[0]}. Dadurch liegen dir ${r[1]} und ${c[2]} besonders gut. In Ereignisquests und später auch in Dungeons werden diese Eigenschaften deine Möglichkeiten direkt beeinflussen: Manche Wege werden sicherer, andere riskanter und gelegentlich öffnen sich Lösungen, die für andere Helden kaum erreichbar sind.\n\nDein wichtigster Klassenfokus ist ${c[1]}. Das bedeutet nicht, dass andere Wege unmöglich sind – Zufall und Ausrüstung bleiben wichtig –, aber dein Charakter besitzt klare natürliche Stärken. Vorsicht ist vor allem bei ${r[2]} geboten. Dort können Fehlschläge wahrscheinlicher werden und eine alternative Herangehensweise kann klüger sein.\n\n${bg[draft.bg]||''} ${n} ist damit kein austauschbarer Abenteurer: Deine Entscheidungen bei der Charaktererschaffung bestimmen, wie du Gefahren einschätzt, welche Risiken du eingehst und welche Geschichten sich auf deiner Reise entwickeln.`}
function showSummary(){const gate=document.getElementById('character-gate');if(!gate)return;let r=strengths[draft.race]||strengths.Mensch,c=classes[draft.cls]||classes.Krieger;gate.innerHTML=`<div class="cg cg-final"><div class="cg-step">CHARAKTEREDITOR · ABSCHLUSS</div><h1>Dein Held ist bereit</h1><div class="final-head"><div class="final-avatar">✦</div><div><b>${draft.name||'Aventurier'}</b><small>${draft.race} · ${draft.cls} · ${draft.bg}</small></div></div><div class="final-tags"><span>Stark: ${r[1]}</span><span>Klassenfokus: ${c[1]}</span><span>Vorsicht: ${r[2]}</span></div><div class="final-story">${story().split('\n\n').map(p=>`<p>${p}</p>`).join('')}</div><div class="cg-actions"><button class="back" onclick="cgSummaryBack()">Zurück</button><button onclick="cgConfirmHero()">Charakter bestätigen</button></div></div>`}
let confirming=false;
window.cgNext=()=>{const btn=[...document.querySelectorAll('#character-gate .cg-actions button')].at(-1);if(!confirming&&btn?.textContent.includes('Held erschaffen'))return showSummary();oldNext()};
window.cgSummaryBack=()=>location.reload();
window.cgConfirmHero=()=>{confirming=true;oldNext()};
const s=document.createElement('style');s.textContent=`.cg-final{max-height:100vh;overflow:auto}.final-head{display:flex;gap:10px;align-items:center;background:#20182b;border:1px solid #ffffff12;border-radius:14px;padding:10px}.final-head b,.final-head small{display:block}.final-head small{font-size:10px;color:#b8a9c4;margin-top:2px}.final-avatar{width:42px;height:42px;border-radius:12px;background:#ffffff09;display:grid;place-items:center;font-size:24px}.final-tags{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.final-tags span{background:#ffffff08;border-radius:9px;padding:7px;font-size:9px;color:#d8cde0}.final-story{background:#120e18;border:1px solid #f4c15d22;border-radius:14px;padding:11px}.final-story p{font-size:11px!important;line-height:1.5!important;margin:0 0 8px!important}.final-story p:last-child{margin-bottom:0!important}@media(max-width:430px){.final-tags{grid-template-columns:1fr}.final-story p{font-size:10px!important}}`;document.head.appendChild(s);
})();