(()=>{
function cityShell(){if(!['city','merchant','bank','forge'].includes(S.screen))return;const main=document.querySelector('main');if(!main)return;let crumb=main.querySelector('.cux-top');if(!crumb){main.insertAdjacentHTML('afterbegin',`<div class="cux-top"><button onclick="tab('city')">🏘️ Stadt</button><span>›</span><b>${S.screen==='city'?'Übersicht':S.screen==='merchant'?'Händler':S.screen==='bank'?'Bank':'Ahnen-Schmiede'}</b></div>`)}if(S.screen==='city')main.querySelector('.cux-top')?.classList.add('root')}
function enhanceCity(){if(S.screen!=='city')return;const head=document.querySelector('.cv2-head');if(head){head.innerHTML=`<div class="cux-city-title"><span>🏘️</span><div><small>STADTVIERTEL</small><h1>Die Stadt</h1><p>Handel, Lager und Handwerk an einem Ort.</p></div></div><div class="cux-city-res"><span>🪙 ${S.gold}</span><span>🎒 ${(S.items||[]).length}/${S.invCap||15}</span></div>`}document.querySelectorAll('.cv2-grid>button').forEach((b,i)=>{b.classList.add('cux-building');const em=b.querySelector('em');if(em)em.classList.add('cux-unlock');if(i===3)b.classList.add('soon')})}
function enhanceMerchantBank(){if(!['merchant','bank'].includes(S.screen))return;const head=document.querySelector('.mb-head');if(head)head.classList.add('cux-panel-head');document.querySelectorAll('.mb-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelectorAll('.mb-item').forEach(x=>x.classList.add('cux-item'));const back=document.querySelector('.cv2-back');if(back)back.remove()}
function enhanceForge(){if(S.screen!=='forge')return;document.querySelector('.fv2-head')?.classList.add('cux-panel-head');document.querySelectorAll('.fv2-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelectorAll('.fv2-item').forEach(x=>x.classList.add('cux-item'));const back=document.querySelector('.cv2-back');if(back)back.remove()}
function polish(){cityShell();enhanceCity();enhanceMerchantBank();enhanceForge()}
const prev=window.render;window.render=function(){prev();polish()};
const css=document.createElement('style');css.textContent=`
.cux-top{max-width:760px;margin:0 auto 8px;display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px}.cux-top.root{display:none}.cux-top button{min-height:36px!important;padding:6px 9px!important;background:#ffffff07!important;border:1px solid #ffffff0d!important;font-size:11px!important}.cux-top b{font-size:11px;color:var(--text)}
.cv2{max-width:760px;margin:auto}.cv2-head{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;padding:13px!important;background:linear-gradient(135deg,#241833,#16101e)!important;border-radius:14px!important;box-shadow:none!important}.cux-city-title{display:flex;align-items:center;gap:10px}.cux-city-title>span{font-size:30px}.cux-city-title small{font-size:10px!important;color:var(--muted)}.cux-city-title h1{font-size:21px!important;margin:1px 0!important}.cux-city-title p{font-size:12px!important;margin:2px 0 0!important}.cux-city-res{display:flex;flex-direction:column;gap:4px;align-items:flex-end}.cux-city-res span{font-size:11px;padding:5px 7px;border-radius:999px;background:#ffffff07;white-space:nowrap}.cv2-grid{grid-template-columns:1fr!important;gap:8px!important}.cux-building{min-height:82px!important;grid-template-columns:48px 1fr auto!important;padding:12px!important;border-radius:13px!important}.cux-building>span:first-child{font-size:29px!important}.cux-building b{font-size:15px!important}.cux-building small{font-size:11px!important;line-height:1.4!important;margin-top:3px!important}.cux-building .cux-unlock{font-size:10px!important;margin-top:4px!important}.cux-building.soon{opacity:.5}
.cux-panel-head{padding:12px!important;border-radius:14px!important;background:linear-gradient(135deg,#241833,#17111f)!important}.cux-panel-head h1{font-size:20px!important}.cux-panel-head p{font-size:11px!important;line-height:1.4!important}.cux-panel-head>small,.cux-panel-head small{font-size:10px!important}.cux-panel-head>b{font-size:13px!important}.mb-tabs,.fv2-tabs{gap:6px!important;margin:8px 0!important}.cux-tab{min-height:44px!important;font-size:12px!important;padding:8px 7px!important}.mb-note{font-size:11px!important;line-height:1.4!important;padding:9px!important}.mb-row{font-size:11px!important}.mb-row button{font-size:11px!important;min-height:38px!important}.mb-list,.fv2-list{gap:7px!important}.cux-item{min-height:70px!important}.mb-item{grid-template-columns:44px 1fr auto!important;padding:10px!important}.mb-icon{font-size:25px!important}.mb-info b{font-size:13px!important}.mb-info small,.mb-info em{font-size:10px!important;line-height:1.35!important}.mb-act>b{font-size:11px!important}.mb-act button{font-size:11px!important;min-height:38px!important;padding:7px 9px!important}.mb-empty span,.mb-empty b{font-size:12px!important}.mb-lock h1{font-size:21px!important}.mb-lock b{font-size:12px!important}.mb-lock p{font-size:11px!important;line-height:1.4!important}.mb-lock button{font-size:12px!important;min-height:44px!important}
.fv2{max-width:760px;margin:auto}.fv2-head small{font-size:10px!important}.fv2-head h1{font-size:20px!important}.fv2-res span{font-size:11px!important}.fv2-list{grid-template-columns:1fr!important}.fv2-item{grid-template-columns:46px 1fr!important;padding:10px!important;min-height:66px!important}.fv2-item>span{width:42px!important;height:42px!important;font-size:22px!important}.fv2-item b{font-size:13px!important}.fv2-item small,.fv2-item em{font-size:10px!important;line-height:1.35!important}.fv2-detail{grid-template-columns:56px 1fr!important}.fv2-detail small{font-size:10px!important}.fv2-detail h2{font-size:16px!important}.fv2-detail p{font-size:11px!important;line-height:1.4!important}.fv2-next small,.fv2-cost small{font-size:10px!important}.fv2-next b{font-size:16px!important}.fv2-cost b{font-size:13px!important}.fv2-danger,.fv2-max,.fv2-empty{font-size:11px!important;line-height:1.4!important}.fv2-action{min-height:46px!important;font-size:12px!important}.fv2-auto{grid-template-columns:1fr!important}.fv2-auto b{font-size:13px!important}.fv2-auto small{font-size:10px!important;line-height:1.4!important}.fv2-auto button{font-size:11px!important;min-height:40px!important}.fv2-ancestor p,.fv2-recipe span{font-size:11px!important;line-height:1.4!important}
@media(max-width:430px){.cv2-head{align-items:flex-start!important}.cux-city-res{font-size:10px}.cux-building{grid-template-columns:42px 1fr auto!important;min-height:78px!important}.cux-building>span:first-child{font-size:25px!important}.cux-building b{font-size:14px!important}.cux-building small{font-size:11px!important}.mb-item{grid-template-columns:40px 1fr!important}.mb-act{grid-column:2;text-align:left!important;display:flex;align-items:center;gap:8px}.mb-act button{display:inline-block!important;margin:0!important}.fv2-res{width:100%;justify-content:flex-start!important;margin-top:4px}.fv2-head{align-items:flex-start!important;flex-direction:column!important}}
`;document.head.appendChild(css);polish();
})();