(()=>{
'use strict';
const CITY_ICON='assets/icons/nav-stadt.webp';
const cityImg=(cls='cux-city-icon')=>`<img class="${cls}" src="${CITY_ICON}" alt="" aria-hidden="true" decoding="async">`;
function cityShell(){if(!['city','merchant','forge','shrine'].includes(S.screen))return;const main=document.querySelector('main');if(!main)return;let crumb=main.querySelector('.cux-top');if(!crumb){const label=S.screen==='city'?'Übersicht':S.screen==='merchant'?'Händler':S.screen==='forge'?'Ahnenschmiede':'Ahnenschrein';main.insertAdjacentHTML('afterbegin',`<div class="cux-top"><button onclick="tab('city')">${cityImg('cux-inline-city')}<span>Stadt</span></button><span>›</span><b>${label}</b></div>`)}if(S.screen==='city')main.querySelector('.cux-top')?.classList.add('root')}
function enhanceCity(){if(S.screen!=='city')return;document.querySelectorAll('.cv2-grid>button').forEach(b=>{b.classList.add('cux-building');b.classList.remove('soon');const em=b.querySelector('em');if(em)em.classList.add('cux-unlock')})}
function enhanceMerchant(){if(S.screen!=='merchant')return;const head=document.querySelector('.mb2-head');if(head)head.classList.add('cux-panel-head');document.querySelectorAll('.mb2-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelector('.cv2-back')?.remove()}
function enhanceForge(){if(S.screen!=='forge')return;document.querySelector('.fv4-head')?.classList.add('cux-panel-head');document.querySelectorAll('.fv4-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelector('.cv2-back')?.remove()}
function enhanceShrine(){if(S.screen!=='shrine')return;document.querySelector('.cv2-back')?.remove()}
function polish(){cityShell();enhanceCity();enhanceMerchant();enhanceForge();enhanceShrine()}
window.Arcane?.on?.('afterRender',polish);window.Arcane?.on?.('bootReady',polish);
const css=document.createElement('style');css.textContent=`
/* City UX is the single authority for city card/icon geometry. */
.cv2{--city-icon-box:104px;--city-icon-column:116px;max-width:760px;margin:auto}.cv2-grid{grid-template-columns:1fr!important;gap:8px!important}.cux-building{min-height:122px!important;grid-template-columns:var(--city-icon-column) minmax(0,1fr) auto!important;padding:12px 14px!important;border-radius:13px!important;overflow:visible!important}.cux-building .cv2-icon{width:var(--city-icon-box)!important;height:var(--city-icon-box)!important;display:grid!important;place-items:center!important;overflow:visible!important;justify-self:center!important}.cux-building .cv2-icon img{display:block!important;width:100%!important;height:100%!important;min-width:0!important;min-height:0!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;object-position:center!important;transform:none!important;will-change:auto!important}.cux-building b{font-size:15px!important}.cux-building small{font-size:11px!important;line-height:1.4!important;margin-top:3px!important}.cux-building .cux-unlock{font-size:10px!important;margin-top:4px!important}
.cux-top{max-width:760px;margin:0 auto 8px;display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px}.cux-top.root{display:none}.cux-top button{min-height:36px!important;padding:6px 9px!important;background:#ffffff07!important;border:1px solid #ffffff0d!important;font-size:11px!important;display:inline-flex!important;align-items:center!important;gap:4px!important}.cux-top b{font-size:11px;color:var(--text)}.cux-inline-city{display:block;width:22px;height:22px;object-fit:contain}
.cux-panel-head{padding:10px 12px!important;border-radius:14px!important;background:linear-gradient(135deg,#241833,#17111f)!important}.cux-panel-head h1{font-size:19px!important}.cux-panel-head p{font-size:11px!important;line-height:1.4!important}.cux-panel-head>small,.cux-panel-head small{font-size:9px!important}.cux-panel-head>b{font-size:12px!important}.mb2-tabs,.fv4-tabs{gap:6px!important;margin:8px 0!important}.cux-tab{min-height:44px!important;font-size:12px!important;padding:8px 7px!important}.mb2-lock h1{font-size:21px!important}.mb2-lock b{font-size:12px!important}
@media(max-width:430px){.cv2{--city-icon-box:102px;--city-icon-column:114px}.cux-building{min-height:120px!important;padding:11px 13px!important}.cux-building b{font-size:14px!important}.cux-building small{font-size:11px!important}}
@media(max-width:365px){.cv2{--city-icon-box:94px;--city-icon-column:106px}.cux-building{min-height:112px!important}}
`;document.head.appendChild(css);queueMicrotask(polish);
})();