(()=>{
function footer(){const nav=document.querySelector('nav.tabs');if(!nav)return;const cityActive=['city','merchant','bank','forge'].includes(S.screen);nav.innerHTML=`
<button class="${S.screen==='home'?'active':''}" onclick="tab('home')"><span class="nav-art"><img src="assets/icons/nav-tavern.webp" alt="" aria-hidden="true"></span><small>Taverne</small></button>
<button class="${S.screen==='dungeon'?'active':''}" onclick="tab('dungeon')"><span class="nav-art"><img src="assets/icons/nav-catacombs.webp" alt="" aria-hidden="true"></span><small>Katakomben</small></button>
<button class="hero-tab ${S.screen==='char'?'active':''}" onclick="tab('char')"><span>🧙</span><small>Held</small></button>
<button class="${cityActive?'active':''}" onclick="tab('city')"><span>🏘️</span><small>Stadt</small></button>
<button class="${S.screen==='arena'?'active':''}" onclick="tab('arena')"><span>⚔️</span><small>Arena</small></button>`}
function lock(level){return S.lvl>=level?'':'<span class="cv2-lock">🔒</span>'}
function city(){return `<section class="cv2"><div class="cv2-head"><small>STADTVIERTEL</small><h1>🏘️ Die Stadt</h1><p>Alle Wirtschafts- und Verwaltungsbereiche an einem Ort. Wähle ein Gebäude, statt durch zusätzliche Haupttabs zu navigieren.</p></div><div class="cv2-grid">
<button onclick="tab('merchant')"><span>🧺</span><div><b>Händler</b><small>Ausrüstung kaufen und Fundstücke verkaufen.</small><em>Ab Stufe 3</em></div>${lock(3)}</button>
<button onclick="tab('forge')"><span>🔨</span><div><b>Ahnen-Schmiede</b><small>Items aufwerten, verwerten und später legendär schmieden.</small><em>Ab Stufe 5</em></div>${lock(5)}</button>
<button onclick="tab('bank')"><span>🏦</span><div><b>Bank</b><small>100 Tresorplätze für Ausrüstung außerhalb des Rucksacks.</small><em>Ab Stufe 10</em></div>${lock(10)}</button>
<button class="cv2-soon" disabled><span>📚</span><div><b>Trainer</b><small>Später: Attribute, Builds und Skill-Vorbereitung.</small><em>In Entwicklung</em></div></button>
</div></section>`}
function addBack(){if(!['merchant','bank','forge'].includes(S.screen))return;const main=document.querySelector('main');if(!main||main.querySelector('.cv2-back'))return;main.insertAdjacentHTML('afterbegin',`<button class="cv2-back" onclick="tab('city')">‹ Zur Stadt</button>`)}
const prevRender=window.render;window.render=function(){if(S.screen==='city'){save();document.getElementById('app').innerHTML=`<header><div class="top"><div class="brand">🍺 Arcane Tavern & Quest <span class="small">BETA</span></div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span><span class="pill">⚡ ${S.al}/${S.maxAl}</span></div></div></header><main>${city()}</main><nav class="tabs"></nav>`;footer();return}prevRender();footer();addBack()};
const prevTab=window.tab;window.tab=function(n){if(n==='city'){S.screen='city';save();render();return}if(n==='merchant'&&S.lvl<3){S.screen='merchant';save();render();return}if(n==='forge'&&S.lvl<5){S.screen='forge';save();render();return}if(n==='bank'&&S.lvl<10){S.screen='bank';save();render();return}prevTab(n)};
const css=document.createElement('style');css.textContent=`
.tabs{display:grid!important;grid-template-columns:repeat(5,1fr)!important;align-items:end!important;height:84px!important;overflow:visible!important;padding:7px max(8px,env(safe-area-inset-left)) max(9px,env(safe-area-inset-bottom))!important}
.tabs button{min-width:0!important;width:100%!important;height:64px!important;padding:4px 2px!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:2px!important}.tabs button span{font-size:27px!important;line-height:1!important}.tabs button small{font-size:9.5px!important;line-height:1.1!important;white-space:nowrap;font-weight:700}.tabs button .nav-art{width:46px;height:46px;display:grid!important;place-items:center;overflow:visible;border-radius:50%;font-size:0!important}.tabs button .nav-art img{display:block;width:100%;height:100%;object-fit:contain}.tabs button.active .nav-art{filter:drop-shadow(0 0 7px #f4c15daa)}.tabs .hero-tab{justify-self:center!important;width:86px!important;max-width:86px!important;height:86px!important;border-radius:50%!important;transform:translateY(-17px)!important;background:linear-gradient(145deg,#8f62df,#5f399f)!important;border:3px solid #2a2038!important;box-shadow:0 8px 22px #0009,0 0 0 2px #f4c15d33!important}.tabs .hero-tab span{font-size:34px!important}.tabs .hero-tab small{font-size:11px!important;font-weight:800}.tabs .hero-tab.active{box-shadow:0 8px 24px #0009,0 0 0 2px var(--gold),0 0 19px #f4c15d55!important}
.cv2{max-width:760px;margin:auto}.cv2-head{background:linear-gradient(135deg,#2b1b40,#17111f);border:1px solid #ffffff14;border-radius:17px;padding:15px}.cv2-head h1{margin:3px 0;font-size:22px}.cv2-head p{margin:5px 0 0;font-size:9px;line-height:1.45;color:var(--muted)}.cv2-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:8px;margin-top:9px}.cv2-grid>button{position:relative;display:grid;grid-template-columns:42px 1fr;gap:9px;text-align:left;align-items:center;background:var(--panel);border:1px solid #ffffff10;box-shadow:none;padding:12px}.cv2-grid>button>span:first-child{font-size:27px;text-align:center}.cv2-grid b,.cv2-grid small,.cv2-grid em{display:block}.cv2-grid b{font-size:11px}.cv2-grid small{font-size:8px;line-height:1.4;color:var(--muted);margin-top:2px}.cv2-grid em{font-size:7px;font-style:normal;color:var(--gold);margin-top:5px}.cv2-lock{position:absolute!important;right:8px;top:8px;font-size:11px!important}.cv2-soon{opacity:.55}.cv2-back{margin:0 0 8px;background:#ffffff08;border:1px solid #ffffff10;box-shadow:none;padding:7px 10px;font-size:9px}
@media(max-width:520px){.cv2-grid{grid-template-columns:1fr}.tabs{height:82px!important}.tabs button{height:62px!important}.tabs .hero-tab{width:82px!important;max-width:82px!important;height:82px!important;transform:translateY(-16px)!important}.tabs .hero-tab span{font-size:32px!important}.tabs button small{font-size:9px!important}.tabs button .nav-art{width:44px;height:44px}}
`;document.head.appendChild(css);render();
})();