(()=>{
'use strict';
const CITY_ICON='assets/icons/nav-stadt.webp';
const cityImg=(cls='cux-city-icon')=>`<img class="${cls}" src="${CITY_ICON}" alt="" aria-hidden="true" decoding="async">`;
function cityShell(){if(!['city','merchant','forge','shrine'].includes(S.screen))return;const main=document.querySelector('main');if(!main)return;let crumb=main.querySelector('.cux-top');if(!crumb){const label=S.screen==='city'?'Übersicht':S.screen==='merchant'?'Händler':S.screen==='forge'?'Ahnenschmiede':'Ahnenschrein';main.insertAdjacentHTML('afterbegin',`<div class="cux-top"><button onclick="tab('city')">${cityImg('cux-inline-city')}<span>Stadt</span></button><span>›</span><b>${label}</b></div>`)}if(S.screen==='city')main.querySelector('.cux-top')?.classList.add('root')}
function enhanceCity(){if(S.screen!=='city')return;document.body.classList.add('aq-city-root');document.querySelectorAll('.cv2-grid>button').forEach(b=>{b.classList.add('cux-building');b.classList.remove('soon');const em=b.querySelector('em');if(em)em.classList.add('cux-unlock')})}
function clearCityClass(){if(S.screen!=='city')document.body.classList.remove('aq-city-root')}
function enhanceMerchant(){if(S.screen!=='merchant')return;const head=document.querySelector('.mb2-head');if(head)head.classList.add('cux-panel-head');document.querySelectorAll('.mb2-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelector('.cv2-back')?.remove()}
function enhanceForge(){if(S.screen!=='forge')return;document.querySelector('.fv4-head')?.classList.add('cux-panel-head');document.querySelectorAll('.fv4-tabs button').forEach(x=>x.classList.add('cux-tab'));document.querySelector('.cv2-back')?.remove()}
function enhanceShrine(){if(S.screen!=='shrine')return;document.querySelector('.cv2-back')?.remove()}
function polish(){clearCityClass();cityShell();enhanceCity();enhanceMerchant();enhanceForge();enhanceShrine()}
window.Arcane?.on?.('afterRender',polish);window.Arcane?.on?.('bootReady',polish);window.Arcane?.on?.('screenChange',polish);
const css=document.createElement('style');css.textContent=`
/* City UX: compact premium hub cards, tuned for one-screen mobile readability. */
body.aq-city-root main{padding-top:12px!important}.cv2{--city-art:132px;--city-col:152px;max-width:760px;margin:auto}.cv2-grid{grid-template-columns:1fr!important;gap:12px!important}.cux-building{position:relative!important;min-height:150px!important;grid-template-columns:var(--city-col) minmax(0,1fr) 24px!important;gap:12px!important;padding:12px 14px!important;border-radius:20px!important;overflow:hidden!important;border:1px solid #ffffff14!important;background:linear-gradient(135deg,#21182c 0%,#191220 64%,#15101c 100%)!important;box-shadow:inset 0 1px 0 #ffffff0c,0 10px 24px #05030924!important;isolation:isolate}.cux-building::before{content:'';position:absolute;inset:5px;border:1px solid #f4c15d12;border-radius:16px;pointer-events:none;z-index:-1}.cux-building::after{content:'';position:absolute;left:var(--city-col);right:44px;bottom:43px;height:1px;background:linear-gradient(90deg,#f4c15d66,#f4c15d18 58%,transparent);pointer-events:none}.cux-building .cv2-icon{width:var(--city-art)!important;height:var(--city-art)!important;display:grid!important;place-items:center!important;overflow:visible!important;justify-self:center!important;align-self:center!important}.cux-building .cv2-icon img{display:block!important;width:100%!important;height:100%!important;max-width:100%!important;max-height:100%!important;object-fit:contain!important;object-position:center!important;filter:drop-shadow(0 7px 9px #0008)!important}.cux-building .cv2-copy{align-self:center!important;min-width:0!important;padding:1px 0 2px!important}.cux-building b{font-size:20px!important;line-height:1.08!important;letter-spacing:-.02em!important;color:#fff!important}.cux-building small{font-size:12px!important;line-height:1.42!important;margin-top:7px!important;color:#c0b3c8!important;max-width:390px}.cux-building .cv2-rule{display:block;height:12px;margin-top:6px}.cux-building .cux-unlock{font-size:11px!important;line-height:1.2!important;margin-top:4px!important;color:var(--gold)!important;font-weight:900!important}.cux-building .cv2-chevron{align-self:center!important;justify-self:end!important;font-size:34px!important;font-weight:300!important;color:#f6c45f!important;text-shadow:0 2px 8px #d77d1840!important;transform:translateY(-1px)}.cux-building .cv2-lock{top:10px!important;right:11px!important;z-index:2!important;background:#100b16e8!important;border-color:#f4c15d24!important;color:#d1c3d7!important}.cux-building.is-locked{opacity:.82}.cux-building.is-locked .cv2-chevron{opacity:.55}.cux-building.cv2-shrine{border-color:#a875ff70!important;background:radial-gradient(circle at 12% 50%,#8b4bdd2d,transparent 43%),linear-gradient(135deg,#25162f 0%,#1b1227 64%,#15101c 100%)!important;box-shadow:inset 0 1px 0 #ffffff0c,0 0 0 1px #8f62df13,0 10px 28px #5a2a8920!important}.cux-building.cv2-shrine::before{border-color:#b47cff24}.cux-building.cv2-shrine::after{background:linear-gradient(90deg,#b47cff80,#f4c15d35 58%,transparent)}
.cux-top{max-width:760px;margin:0 auto 8px;display:flex;align-items:center;gap:6px;color:var(--muted);font-size:11px}.cux-top.root{display:none}.cux-top button{min-height:36px!important;padding:6px 9px!important;background:#ffffff07!important;border:1px solid #ffffff0d!important;font-size:11px!important;display:inline-flex!important;align-items:center!important;gap:4px!important}.cux-top b{font-size:11px;color:var(--text)}.cux-inline-city{display:block;width:22px;height:22px;object-fit:contain}
.cux-panel-head{padding:10px 12px!important;border-radius:14px!important;background:linear-gradient(135deg,#241833,#17111f)!important}.cux-panel-head h1{font-size:19px!important}.cux-panel-head p{font-size:11px!important;line-height:1.4!important}.cux-panel-head>small,.cux-panel-head small{font-size:9px!important}.cux-panel-head>b{font-size:12px!important}.mb2-tabs,.fv4-tabs{gap:6px!important;margin:8px 0!important}.cux-tab{min-height:44px!important;font-size:12px!important;padding:8px 7px!important}.mb2-lock h1{font-size:21px!important}.mb2-lock b{font-size:12px!important}
@media(max-width:430px){.cv2{--city-art:116px;--city-col:132px}.cv2-grid{gap:10px!important}.cux-building{min-height:136px!important;grid-template-columns:var(--city-col) minmax(0,1fr) 20px!important;gap:10px!important;padding:10px 11px!important;border-radius:18px!important}.cux-building::before{inset:4px;border-radius:15px}.cux-building::after{left:var(--city-col);right:38px;bottom:38px}.cux-building b{font-size:18px!important}.cux-building small{font-size:11px!important;line-height:1.38!important;margin-top:5px!important}.cux-building .cv2-rule{height:8px;margin-top:4px}.cux-building .cux-unlock{font-size:10px!important;margin-top:3px!important}.cux-building .cv2-chevron{font-size:30px!important}.cux-building .cv2-lock{top:7px!important;right:8px!important;font-size:7px!important}}
@media(max-width:380px){.cv2{--city-art:102px;--city-col:116px}.cux-building{min-height:124px!important;gap:8px!important;padding:9px 10px!important}.cux-building b{font-size:16px!important}.cux-building small{font-size:10px!important}.cux-building .cux-unlock{font-size:9px!important}.cux-building::after{left:var(--city-col);bottom:35px}}
@media(max-height:760px){body.aq-city-root .cv2-grid{gap:8px!important}.cux-building{min-height:118px!important}.cux-building .cv2-icon{width:100px!important;height:100px!important}.cux-building small{line-height:1.3!important}.cux-building .cv2-rule{height:5px!important}}
`;document.head.appendChild(css);queueMicrotask(polish);
})();