(()=>{
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function stats(){return window.getFinalStats?getFinalStats():{str:S.str||8,agi:S.agi||8,int:S.int||8}}
function chance(stat){const s=stats(),base=52+(Number(s[stat]||8)-8)*2;return Math.max(28,Math.min(88,Math.round(base)))}
function riskLabel(p){return p>=75?['Sehr günstig','good']:p>=60?['Günstig','good']:p>=45?['Ausgeglichen','mid']:['Riskant','bad']}
function effectText(stat){return stat==='str'?'Erfolg: Gold/Beute · Fehlschlag: HP-Verlust':stat==='agi'?'Erfolg: Gold/Beute · Fehlschlag: HP-Verlust':'Erfolg: Gold/Beute · Fehlschlag: HP-Verlust'}
function lootPanel(){const d=S.dungeonV1;if(!d)return '';const items=d.loot||[];return `<div class="d2-loot"><div class="d2-loot-head"><div><small>AKTUELLE DUNGEON-BEUTE</small><b>${items.length?`${items.length} Gegenstand${items.length===1?'':'e'} gefunden`:'Noch keine Gegenstände'}</b></div><span>🪙 ${d.gold||0} · ✦ ${d.xp||0} XP</span></div>${items.length?`<div class="d2-loot-list">${items.map(it=>`<div class="d2-loot-item ${esc(it.rarity||'common')}"><span>🎁</span><div><b>${esc(it.name||'Unbekannte Beute')}</b><small>${esc(it.slot||'Beute')} · Macht ${Number(it.power)||0}</small></div></div>`).join('')}</div>`:'<p>Noch nichts gefunden. Alles hier Gezeigte geht bei einer Niederlage verloren.</p>'}<div class="d2-warning">⚠ Ungesicherte Beute geht bei einer Niederlage verloren.</div></div>`}
function decisionCards(){const s=stats();return `<div class="d2-decisions">${[['str','🛡️','Kraft',s.str],['agi','🌑','Geschick',s.agi],['int','🔮','Wissen',s.int]].map(([stat,icon,label,val])=>{const p=chance(stat),r=riskLabel(p);return `<button class="d2-choice" onclick="d1Event('${stat}')"><div class="d2-top"><span>${icon}</span><div><b>${label}</b><small>${stat.toUpperCase()} ${val}</small></div><em class="${r[1]}">${p}%</em></div><div class="d2-meter"><i style="width:${p}%"></i></div><p>${r[0]} · ${effectText(stat)}</p></button>`}).join('')}</div>`}
const oldView=window.dungeonV1;
window.dungeonV1=function(){let html=oldView();const d=S.dungeonV1;if(!d)return html;
  html=html.replace(/<div class="d-beta-back"><button onclick="d1Leave\(\)">‹ Katakomben verlassen<\/button><\/div>/,'');
  if(d.state==='event'){
    html=html.replace(/<div class="d1-actions"><button onclick="d1Event\('str'\)">[\s\S]*?<\/div><\/div>/,`${decisionCards()}</div>`);
  }
  const insert=lootPanel();
  html=html.replace(/(<div class="d1-bank">[\s\S]*?<\/div>)/,`$1${insert}`);
  return html;
};
const oldRender=window.render;window.render=function(){oldRender();if(S.screen==='dungeon'){const main=document.querySelector('main');if(main)main.innerHTML=window.dungeonV1()}};
const style=document.createElement('style');style.textContent=`
.d2-loot{margin:8px 0;background:#17111f;border:1px solid #ffffff12;border-radius:13px;padding:10px}.d2-loot-head{display:flex;justify-content:space-between;gap:8px;align-items:flex-start}.d2-loot-head small,.d2-loot-head b{display:block}.d2-loot-head small{font-size:8px;color:var(--muted)}.d2-loot-head b{font-size:11px;margin-top:2px}.d2-loot-head>span{font-size:9px;color:var(--gold);white-space:nowrap}.d2-loot p{font-size:8px;color:var(--muted);margin:8px 0 0}.d2-warning{margin-top:8px;padding:6px 8px;border-radius:8px;background:#e86a7a12;color:#eaa3ad;font-size:8px}.d2-loot-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:5px;margin-top:8px}.d2-loot-item{display:grid;grid-template-columns:28px 1fr;gap:6px;align-items:center;padding:7px;border-radius:9px;background:#ffffff07;border:1px solid #777}.d2-loot-item.rare{border-color:#4aa3ff}.d2-loot-item.magic{border-color:#4fd18b}.d2-loot-item.epic{border-color:#a875ff}.d2-loot-item.mythic{border-color:#ff8b45;box-shadow:0 0 10px #ff8b4533}.d2-loot-item.legendary{border-color:#ffd84d;box-shadow:0 0 12px #ffd84d44}.d2-loot-item>span{font-size:18px}.d2-loot-item b,.d2-loot-item small{display:block}.d2-loot-item b{font-size:9px}.d2-loot-item small{font-size:7px;color:var(--muted)}
.d2-decisions{display:grid;gap:7px;margin-top:10px}.d2-choice{width:100%;padding:9px 10px;background:#ffffff08;border:1px solid #ffffff12;box-shadow:none;text-align:left}.d2-top{display:grid;grid-template-columns:30px 1fr auto;gap:7px;align-items:center}.d2-top>span{font-size:20px;text-align:center}.d2-top b,.d2-top small{display:block}.d2-top b{font-size:11px}.d2-top small{font-size:8px;color:var(--muted)}.d2-top em{font-style:normal;font-size:11px;font-weight:900}.d2-top em.good{color:var(--ok)}.d2-top em.mid{color:var(--gold)}.d2-top em.bad{color:var(--danger)}.d2-meter{height:5px;background:#ffffff0b;border-radius:99px;overflow:hidden;margin:6px 0}.d2-meter i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--gold))}.d2-choice p{margin:0;font-size:8px;color:var(--muted);line-height:1.35}@media(max-width:420px){.d2-loot-list{grid-template-columns:1fr}}
`;document.head.appendChild(style);if(S.screen==='dungeon')render();
})();