(()=>{
const base=window.dungeonV1;if(!base)return;
function lootSummary(d){const items=(d.loot||[]).length;return `<div class="dux-loot"><span><b>🪙 ${d.gold||0}</b><small>Gold</small></span><span><b>✦ ${d.xp||0}</b><small>XP</small></span><span><b>🎁 ${items}</b><small>Items</small></span></div>`}
function status(d){const pct=Math.max(0,Math.min(100,((d.room||0)+1)/10*100));return `<div class="dux-run"><div class="dux-runhead"><div><small>AKTIVER RUN</small><b>Raum ${(d.room||0)+1} / 10</b></div><div><small>❤️ HP</small><b>${d.hp}/${d.maxHp}</b></div></div><div class="dux-progress"><i style="width:${pct}%"></i></div>${lootSummary(d)}</div>`}
function clean(h,d){h=h.replace(/<div class="d1-bank">[\s\S]*?<\/div>/,'');h=h.replace(/<div class="dv2-risk">[\s\S]*?<\/div>/,'');h=h.replace(/<div class="d2-loot">[\s\S]*?<\/div>/,'');return h.replace('<section class="d1','<section class="d1 dux3')}
window.dungeonV1=function(){let h=base(),d=S.dungeonV1;if(!d)return h;h=clean(h,d);const marker=h.indexOf('>');if(marker>=0)h=h.slice(0,marker+1)+status(d)+h.slice(marker+1);if(d.room>=2&&d.state!=='combat'&&!['complete'].includes(d.state)){h=h.replace('</section>',`<div class="dux-exit"><div><b>Beute sichern?</b><small>Bei Niederlage geht die ungesicherte Beute verloren.</small></div><button onclick="d1Leave()">Sichern & raus</button></div></section>`)}return h};
const css=document.createElement('style');css.textContent=`
.dux3{max-width:720px;margin:auto}.dux-run{position:sticky;top:60px;z-index:3;background:#17111ff2;border:1px solid #ffffff10;border-radius:14px;padding:10px;margin-bottom:9px;backdrop-filter:blur(10px)}.dux-runhead{display:flex;justify-content:space-between;align-items:end;gap:10px}.dux-runhead small,.dux-runhead b{display:block}.dux-runhead small{font-size:10px;color:var(--muted)}.dux-runhead b{font-size:14px}.dux-progress{height:8px;background:#ffffff0b;border-radius:99px;overflow:hidden;margin:8px 0}.dux-progress i{display:block;height:100%;background:linear-gradient(90deg,var(--accent),var(--gold))}.dux-loot{display:grid;grid-template-columns:repeat(3,1fr);gap:5px}.dux-loot span{text-align:center;background:#ffffff05;border-radius:9px;padding:6px}.dux-loot b,.dux-loot small{display:block}.dux-loot b{font-size:12px}.dux-loot small{font-size:9px;color:var(--muted)}.dux3 .d1-track{margin:6px 0!important}.dux3 .d1-track i{min-height:36px;display:grid;place-items:center}.dux3 .d1-room{padding:14px!important;border-radius:14px!important}.dux3 .d1-room .d1-icon{font-size:34px!important}.dux3 .d1-room h2{font-size:19px!important;margin:4px 0!important}.dux3 .d1-room p{font-size:12px!important;line-height:1.45!important;color:#d8cde0!important}.dux3 .d1-room button{min-height:46px!important;font-size:13px!important;width:100%}.dux3 .auto-combat-panel{margin:8px 0!important;padding:10px!important}.dux3 .auto-label{font-size:10px!important}.dux3 .auto-combat-panel>b{font-size:13px!important}.dux3 .auto-combat-panel>p{font-size:11px!important}.dux3 .auto-log{font-size:11px!important;line-height:1.45!important;max-height:170px!important}.dux3 .d1-enemy h2{font-size:18px!important}.dux3 .d1-bars b,.dux3 .d1-bars em{font-size:12px!important}.dux3 .d1-bars i{height:12px!important}.dux3 .dv2-boss span,.dux3 .dv2-boss small{font-size:10px!important}.dux3 .df3-intro{font-size:11px!important}.dux3 .df3-head b{font-size:13px!important}.dux3 .df3-head small,.dux3 .df3-result{font-size:10px!important}.dux3 .df3-choices p{font-size:11px!important}.dux3 .df3-head em{font-size:14px!important}.dux-exit{display:flex;justify-content:space-between;align-items:center;gap:10px;margin-top:9px;padding:10px;border-radius:12px;background:#f4c15d0b;border:1px solid #f4c15d22}.dux-exit b,.dux-exit small{display:block}.dux-exit b{font-size:12px}.dux-exit small{font-size:10px;color:var(--muted)}.dux-exit button{font-size:11px;min-height:42px;background:#ffffff0b}
@media(max-width:430px){.dux-run{top:58px;padding:9px}.dux3 .d1-track{grid-template-columns:repeat(5,1fr)!important}.dux3 .d1-track i{font-size:13px!important}.dux-exit{display:grid;grid-template-columns:1fr}.dux-exit button{width:100%}}
`;document.head.appendChild(css);if(S.screen==='dungeon')render();
})();