(()=>{
const V2ROOMS=[
{type:'event',icon:'🜂',name:'Flüsternde Galerie',text:'Runen flackern an den Wänden. Ein falscher Schritt weckt die Wächter.'},
{type:'combat',icon:'⚔️',name:'Knochenwache',text:'Ein gepanzerter Wächter versperrt den Abstieg.'},
{type:'event',icon:'🗝️',name:'Versiegelte Nische',text:'Eine alte Truhe liegt hinter einem arkanen Mechanismus.'},
{type:'combat',icon:'👁️',name:'Schattenbestie',text:'Etwas bewegt sich zwischen den zerbrochenen Säulen.'},
{type:'elite',icon:'🛡️',name:'Grabritter',text:'Ein Elitewächter schützt den Weg in die tieferen Gewölbe.'},
{type:'rest',icon:'🕯️',name:'Schrein der Stille',text:'Ein geschützter Schrein bietet einen Moment zum Atemholen.'},
{type:'event',icon:'📜',name:'Archiv der Toten',text:'Verbotene Runen versprechen Wissen und Beute – wenn du sie richtig deutest.'},
{type:'combat',icon:'🕷️',name:'Gruftweberin',text:'Netze versperren den schmalen Gang zur letzten Kammer.'},
{type:'treasure',icon:'💎',name:'Schatzkammer',text:'Die Beute der Gefallenen liegt offen vor dir. Dahinter wartet nur noch der Hüter.'},
{type:'boss',icon:'💀',name:'Hüter der Katakomben',text:'Der Hüter erhebt sich vor dem versiegelten Herzraum.'}
];
function D(){return S.dungeonV1}function st(){return window.getFinalStats?getFinalStats():{str:S.str||8,agi:S.agi||8,int:S.int||8,hp:S.maxHp||120,armor:0,damage:0,crit:0,dodge:0,block:0}}
function loot(type='risk'){if(!window.generateLoot)return null;const it=generateLoot(type);if(it&&it.rarity==='legendary')it.rarity='mythic';return it}
function addLoot(type,chance=1){const d=D();if(Math.random()>chance)return null;const it=loot(type);if(it)d.loot.push(it);return it}
function startRoom(){const d=D(),r=V2ROOMS[d.room];if(!d||!r)return;if(r.type==='event'){d.state='event';d.feedback=null;save();render();return}if(r.type==='rest'){d.state='v2rest';d.feedback=null;save();render();return}if(r.type==='treasure'){d.state='v2treasure';d.feedback=null;save();render();return}combat(r)}
function combat(r){const d=D(),s=st(),boss=r.type==='boss',elite=r.type==='elite';let max=Math.floor((boss?170:elite?95:62)+S.lvl*(boss?10:elite?7:5));d.enemy={name:r.name,hp:max,max,damage:boss?17+S.lvl*2:elite?12+S.lvl:9+S.lvl,boss,elite,phase:'attack',telegraph:null,v2:true,round:1,shield:boss?Math.floor(max*.28):0,maxShield:boss?Math.floor(max*.28):0,enraged:false};d.state='combat';d.feedback=null;save();render()}
function rest(){const d=D(),heal=Math.max(8,Math.floor(d.maxHp*.25));d.hp=Math.min(d.maxHp,d.hp+heal);d.feedback={good:true,title:'Kräfte gesammelt',text:`Der Schrein stellt ${heal} HP wieder her.`};d.state='cleared';save();render()}
function treasure(){const d=D(),g=45+S.lvl*4;d.gold+=g;const it=addLoot('risk',.9);d.feedback={good:true,title:'Schatzkammer geplündert',text:`+${g} Gold${it?` · ${it.name} gefunden`:''}. Vor dir wartet der Endboss.`};d.state='cleared';save();render()}
const oldAttack=window.d1Attack;window.d1Attack=function(kind){const d=D(),e=d?.enemy;if(!e?.v2)return oldAttack(kind);if(e.phase!=='attack')return;const s=st();let chance=kind==='safe'?82:kind==='heavy'?58:70,base=kind==='safe'?5:kind==='heavy'?14:9;chance+=Math.floor(((s.str||8)+(s.agi||8)+(s.int||8)-24)/6);let hit=Math.random()*100<chance;if(hit){let dmg=Math.floor(base+(s.damage||0)+(Math.max(s.str||8,s.agi||8,s.int||8)-8)*.55+Math.random()*5);if(Math.random()*100<(s.crit||0)+5)dmg=Math.floor(dmg*1.55);let shieldHit=0;if(e.shield>0){shieldHit=Math.min(e.shield,dmg);e.shield-=shieldHit;dmg-=shieldHit}if(dmg>0)e.hp=Math.max(0,e.hp-dmg);d.feedback={good:true,title:e.shield>0?'Phasenschild getroffen':'Treffer',text:`${shieldHit?`${shieldHit} Schildschaden${dmg?` und ${dmg} Lebensschaden`:''}`:`${dmg} Schaden gegen ${e.name}`}.`};if(e.hp<=0)return win()}else d.feedback={good:false,title:'Verfehlt',text:'Der Angriff findet keine Lücke.'};e.phase='defense';const moves=e.boss?[{name:'Grabeswucht',hint:'Schwer und frontal – Blocken ist günstig.',block:20,dodge:-12},{name:'Seelenlanze',hint:'Schnell und linear – Ausweichen ist günstig.',block:-10,dodge:20},{name:'Totenwelle',hint:'Flächenangriff – Standhalten ist am sichersten.',block:-3,dodge:-3}]:[{name:'Wuchtangriff',hint:'Schwer und frontal – Blocken ist günstig.',block:18,dodge:-8},{name:'Schattenstoß',hint:'Schnell und geradlinig – Ausweichen ist günstig.',block:-8,dodge:18}];e.telegraph=moves[Math.floor(Math.random()*moves.length)];save();render()};
const oldDef=window.d1Defend;window.d1Defend=function(kind){const d=D(),e=d?.enemy;if(!e?.v2)return oldDef(kind);if(e.phase!=='defense')return;const s=st();let chance=kind==='block'?52+(s.block||0)+(e.telegraph?.block||0):kind==='dodge'?52+(s.dodge||0)+(e.telegraph?.dodge||0):72;if(e.boss&&e.telegraph?.name==='Totenwelle'&&kind==='brace')chance=88;chance=Math.max(22,Math.min(92,chance));const ok=Math.random()*100<chance;if(ok)d.feedback={good:true,title:'Verteidigt',text:`${kind==='block'?'Blocken':kind==='dodge'?'Ausweichen':'Standhalten'} gelingt.`};else{const armor=Math.min(.55,(s.armor||0)*.018),rage=e.enraged?1.45:1,dmg=Math.max(2,Math.floor((e.damage+Math.random()*7)*rage*(1-armor)));d.hp=Math.max(0,d.hp-dmg);d.feedback={good:false,title:'Getroffen',text:`${e.name} verursacht ${dmg} Schaden${e.enraged?' (Enrage)':''}.`};if(d.hp<=0)return window.d1V2Lose()}e.round++;if(e.boss&&!e.enraged&&e.round>=7){e.enraged=true;d.feedback.text+=' Der Hüter gerät in Raserei: Sein Schaden steigt.'}e.phase='attack';e.telegraph=null;save();render()};
function win(){const d=D(),e=d.enemy;d.gold+=e.boss?110+S.lvl*7:e.elite?55+S.lvl*4:28+S.lvl*3;d.xp+=e.boss?85+S.lvl*5:e.elite?38+S.lvl*3:22+S.lvl*2;const it=addLoot(e.boss?'bounty':'risk',e.boss?.95:e.elite?.65:.3);d.enemy=null;d.feedback={good:true,title:e.boss?'Hüter bezwungen':e.elite?'Elite besiegt':'Raum gesäubert',text:e.boss?`Der Hüter fällt${it?` · ${it.name} erbeutet`:''}. Die Katakomben sind bezwungen.`:`Der Weg ist frei${it?` · ${it.name} gefunden`:''}.`};d.state=e.boss?'complete':'cleared';save();render()}
window.d1V2Lose=function(){const d=D();S.hp=Math.max(1,Math.floor((S.maxHp||120)*.35));S.dungeonV1=null;S.screen='home';log('In den Katakomben besiegt. Ungesicherte Dungeon-Beute ging verloren.');save();render();toast('Niederlage: Die ungesicherte Dungeon-Beute ist verloren.')};
const oldEnter=window.d1Enter;window.d1Enter=function(){const d=D();if(d&&d.room<10)return startRoom();return oldEnter()};
const oldNext=window.d1Next;window.d1Next=function(){const d=D();if(!d)return;if(['feedback','cleared'].includes(d.state)){d.room++;d.state='room';d.feedback=null;save();render();return}return oldNext()};
function risk(){const d=D();if(!d||d.room<2||d.state==='combat')return '';const depth=d.room+1,bonus=Math.max(0,(depth-1)*4);return `<div class="dv2-risk"><div><small>RISIKO / BELOHNUNG</small><b>Ebene ${depth}/10 · Loot-Bonus +${bonus}%</b><p>Je tiefer du gehst, desto wertvoller wird die Expedition. Bei Niederlage verlierst du die gesamte ungesicherte Beute.</p></div><button onclick="d1Leave()">Beute sichern & raus</button></div>`}
const oldView=window.dungeonV1;window.dungeonV1=function(){let h=oldView(),d=D();if(!d)return h.replace(/Fünf Räume/g,'Zehn Räume').replace(/>5<\/b><small>Räume/g,'>10</b><small>Räume');const r=V2ROOMS[d.room]||V2ROOMS[9];h=h.replace(/KATAKOMBEN · RAUM \d+\/5/g,`KATAKOMBEN · RAUM ${d.room+1}/10`).replace(/RAUM \d+ \/ 5/g,`RAUM ${d.room+1} / 10`);h=h.replace(/<div class="d1-track">[\s\S]*?<\/div><div class="d1-bank">/,`<div class="d1-track dv2-track">${V2ROOMS.map((x,i)=>`<i class="${i<d.room?'done':i===d.room?'now':''}">${x.icon}</i>`).join('')}</div><div class="d1-bank">`);if(d.state==='room')h=h.replace(/<div class="d1-room">[\s\S]*?<button onclick="d1Enter\(\)">Raum betreten<\/button><\/div>/,`<div class="d1-room"><div class="d1-icon">${r.icon}</div><div class="small">RAUM ${d.room+1} / 10</div><h2>${r.name}</h2><p>${r.text}</p><button onclick="d1Enter()">Raum betreten</button></div>`);if(d.state==='v2rest')h=h.replace(/<div class="d1-room">[\s\S]*?<\/div>$/,`<div class="d1-room"><div class="d1-icon">🕯️</div><div class="small">RUHERAUM · RAUM 6</div><h2>Schrein der Stille</h2><p>Du kannst einen Teil deiner Lebenspunkte wiederherstellen, bevor du tiefer gehst.</p><button onclick="d1V2Rest()">25% HP wiederherstellen</button></div>`);if(d.state==='v2treasure')h=h.replace(/<div class="d1-room">[\s\S]*?<\/div>$/,`<div class="d1-room"><div class="d1-icon">💎</div><div class="small">SCHATZRAUM · RAUM 9</div><h2>Schatzkammer</h2><p>Eine garantierte Zwischenbelohnung. Danach wartet der Hüter.</p><button onclick="d1V2Treasure()">Schatz öffnen</button></div>`);if(d.enemy?.boss){const e=d.enemy,shield=Math.round((e.shield||0)/(e.maxShield||1)*100);h=h.replace(`<h2>${e.name}</h2>`,`<h2>${e.name}</h2><div class="dv2-boss"><span>PHASENSCHILD ${e.shield||0}/${e.maxShield||0}</span><i><b style="width:${shield}%"></b></i><small>${e.shield>0?'Das Schild absorbiert zunächst deinen Schaden.':e.enraged?'ENRAGE AKTIV · erhöhter Boss-Schaden':'Schild gebrochen · der Hüter ist verwundbar.'}</small></div>`)}h=h.replace(/(<div class="d1-bank">[\s\S]*?<\/div>)/,`$1${risk()}`);return h};
window.d1V2Rest=rest;window.d1V2Treasure=treasure;
const style=document.createElement('style');style.textContent=`.dv2-track{grid-template-columns:repeat(10,1fr)!important}.dv2-track i{font-size:11px;padding:6px 0!important}.dv2-risk{margin:7px 0;padding:9px;background:#f4c15d0b;border:1px solid #f4c15d25;border-radius:11px;display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center}.dv2-risk small,.dv2-risk b,.dv2-risk p{display:block}.dv2-risk small{font-size:7px;color:var(--gold)}.dv2-risk b{font-size:10px}.dv2-risk p{font-size:7px;color:var(--muted);margin:2px 0 0}.dv2-risk button{font-size:8px;padding:7px 8px;background:#ffffff0c;box-shadow:none}.dv2-boss{margin:7px 0;padding:8px;border-radius:10px;background:#e86a7a0b;border:1px solid #e86a7a22;text-align:left}.dv2-boss span,.dv2-boss small{display:block;font-size:8px}.dv2-boss small{color:var(--muted);margin-top:4px}.dv2-boss i{display:block;height:6px;background:#ffffff0c;border-radius:99px;overflow:hidden;margin-top:4px}.dv2-boss i b{display:block;height:100%;background:var(--accent)}@media(max-width:420px){.dv2-track{gap:2px!important}.dv2-track i{font-size:9px}.dv2-risk{grid-template-columns:1fr}.dv2-risk button{width:100%}}`;document.head.appendChild(style);
})();