(()=>{
const RACES={Mensch:{icon:'🧑',bonus:'STR +2 · AGI +2 · INT +2',passive:'Anpassungsfähigkeit',effect:'+10% XP'},Elf:{icon:'🧝',bonus:'AGI +4 · INT +2',passive:'Arkaner Reflex',effect:'+5% Ausweichen · +3% Krit'},Zwerg:{icon:'⛏️',bonus:'STR +4 · HP +20',passive:'Steinblut',effect:'+15% Rüstung'},Ork:{icon:'👹',bonus:'STR +5 · AGI +1',passive:'Blutrausch',effect:'+25% Schaden gegen Gegner unter 30% HP'},Nachtläufer:{icon:'🌙',bonus:'AGI +4 · INT +2',passive:'Schattenschritt',effect:'+5% Life-Steal · erster Schlag kritisch'},Drachengeborener:{icon:'🐉',bonus:'STR +3 · INT +3',passive:'Drachenatem',effect:'10% Chance auf Elementarbrand'}};
const CLASSES={Krieger:{icon:'🛡️',role:'Tank',primary:'STR',res:'Wut',skill:'Schildwall'},Magier:{icon:'🔮',role:'Burst',primary:'INT',res:'Mana',skill:'Arkaner Meteor'},Druide:{icon:'🌿',role:'Hybrid',primary:'Hybrid',res:'Naturfokus',skill:'Gestaltwechsel'},Waldläufer:{icon:'🏹',role:'Fernkampf',primary:'AGI',res:'Energie',skill:'Pfeilhagel'},Hexenmeister:{icon:'🕯️',role:'Debuff',primary:'INT/AGI',res:'Seelenfragmente',skill:'Seelenentzug'},Totenbeschwörer:{icon:'💀',role:'Beschwörer',primary:'INT/STR',res:'Todesessenz',skill:'Skelett-Diener'}};
const BGS={'Tavernen-Stammgast':{icon:'🍺',effect:'+15% Abenteuerlust-Effizienz'},'Gefallener Adeliger':{icon:'👑',effect:'+10% Gold aus allen Quellen'},'Runenschmied-Lehrling':{icon:'🔨',effect:'+10% Erfolgschance beim Aufwerten'},'Schatten-Ausreißer':{icon:'🗝️',effect:'+5% Beute-Glück'}};
let created=localStorage.getItem('arcaneCharacterCreated')==='1';
const old=JSON.parse(localStorage.getItem('arcaneBeta')||'null')||{};
let draft={name:old.name||'',race:old.race||'Mensch',cls:old.cls||'Krieger',bg:old.bg||'Tavernen-Stammgast',step:1};
const css=`#character-gate{position:fixed;inset:0;z-index:999;background:radial-gradient(circle at 50% -10%,#3a2454 0,#120e18 48%);color:#f7f0e8;display:flex;justify-content:center;overflow:hidden;font-family:system-ui,-apple-system,Segoe UI,Roboto,sans-serif}#character-gate *{box-sizing:border-box}.cg-shell{width:min(720px,100%);height:100%;display:flex;flex-direction:column;padding:18px 14px max(18px,env(safe-area-inset-bottom))}.cg-head{padding:6px 2px 14px}.cg-brand{font-weight:900;font-size:14px}.cg-title{font-size:28px;font-weight:900;margin:14px 0 4px}.cg-sub{color:#b8a9c4;font-size:14px;line-height:1.45}.cg-progress{display:grid;grid-template-columns:repeat(3,1fr);gap:6px;margin-top:14px}.cg-progress i{height:5px;border-radius:99px;background:#ffffff14}.cg-progress i.on{background:#f4c15d}.cg-content{flex:1;min-height:0;display:flex;flex-direction:column;overflow:hidden}.cg-step{display:none;flex:1;min-height:0;overflow:auto;padding:4px 1px 10px}.cg-step.on{display:flex;flex-direction:column}.cg-label{font-size:11px;color:#b8a9c4;letter-spacing:.8px;font-weight:800;margin:5px 0 7px}.cg-input{width:100%;padding:14px;border-radius:14px;border:1px solid #ffffff18;background:#ffffff09;color:#f7f0e8;font-size:17px;outline:none}.cg-input:focus{border-color:#a875ff}.cg-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.cg-card{border:1px solid #ffffff12;background:#20182b;color:#f7f0e8;border-radius:16px;padding:13px;text-align:left;min-height:118px;box-shadow:none}.cg-card.sel{border:2px solid #f4c15d;background:#2b1b40}.cg-icon{font-size:30px}.cg-card b{display:block;margin-top:5px}.cg-meta{display:block;color:#f4c15d;font-size:11px;margin-top:4px}.cg-small{display:block;color:#b8a9c4;font-size:11px;line-height:1.35;margin-top:5px}.cg-footer{padding-top:10px;display:flex;gap:8px}.cg-btn{flex:1;border:0;border-radius:14px;padding:14px;background:#a875ff;color:white;font-weight:800;font-size:15px}.cg-btn.secondary{background:#ffffff0d}.cg-summary{background:#20182b;border:1px solid #ffffff12;border-radius:18px;padding:16px;margin-top:4px}.cg-hero{font-size:44px}.cg-summary h2{margin:5px 0}.cg-stat{display:flex;justify-content:space-between;padding:7px 0;border-bottom:1px solid #ffffff0d}.cg-note{color:#b8a9c4;font-size:12px;margin-top:10px}@media(max-width:430px){.cg-grid{grid-template-columns:1fr}.cg-card{min-height:96px}.cg-title{font-size:25px}}`;
function style(){if(document.getElementById('cg-style'))return;const s=document.createElement('style');s.id='cg-style';s.textContent=css;document.head.appendChild(s)}
function saveDraft(){const s=JSON.parse(localStorage.getItem('arcaneBeta')||'null')||{};Object.assign(s,{name:draft.name||'Aventurier',race:draft.race,cls:draft.cls,bg:draft.bg,screen:'home'});localStorage.setItem('arcaneBeta',JSON.stringify(s));localStorage.setItem('arcaneCharacterCreated','1')}
function render(){if(created)return;style();let root=document.getElementById('character-gate');if(!root){root=document.createElement('div');root.id='character-gate';document.body.appendChild(root)}root.innerHTML=`<div class="cg-shell"><div class="cg-head"><div class="cg-brand">🍺 ARCANE TAVERN & QUEST · BETA</div><div class="cg-title">Erschaffe deinen Helden</div><div class="cg-sub">Deine erste Entscheidung bestimmt Herkunft, Klasse und Hintergrund. Nach der Erstellung ist der Charakter festgelegt.</div><div class="cg-progress"><i class="${draft.step>=1?'on':''}"></i><i class="${draft.step>=2?'on':''}"></i><i class="${draft.step>=3?'on':''}"></i></div></div><div class="cg-content">${step1()}${step2()}${step3()}</div><div class="cg-footer">${draft.step>1?'<button class="cg-btn secondary" onclick="cgPrev()">Zurück</button>':''}<button class="cg-btn" onclick="cgNext()">${draft.step<3?'Weiter':'Held erschaffen'}</button></div></div>`}
function step1(){return `<section class="cg-step ${draft.step===1?'on':''}"><div class="cg-label">SCHRITT 1 VON 3 · NAME & VOLK</div><input class="cg-input" maxlength="24" placeholder="Name deines Helden" value="${String(draft.name).replace(/"/g,'&quot;')}" oninput="cgName(this.value)"><div class="cg-label" style="margin-top:16px">VOLK</div><div class="cg-grid">${Object.entries(RACES).map(([n,x])=>`<button type="button" class="cg-card ${draft.race===n?'sel':''}" onclick="cgRace('${n}')"><span class="cg-icon">${x.icon}</span><b>${n}</b><span class="cg-meta">${x.bonus}</span><span class="cg-small">${x.passive} · ${x.effect}</span></button>`).join('')}</div></section>`}
function step2(){return `<section class="cg-step ${draft.step===2?'on':''}"><div class="cg-label">SCHRITT 2 VON 3 · KLASSE</div><h2 style="margin:4px 0 6px">Welche Art Held bist du?</h2><div class="cg-sub" style="margin-bottom:12px">Die Klasse bestimmt deine grundlegende Kampfrolle und Ressource.</div><div class="cg-grid">${Object.entries(CLASSES).map(([n,x])=>`<button type="button" class="cg-card ${draft.cls===n?'sel':''}" onclick="cgClass('${n}')"><span class="cg-icon">${x.icon}</span><b>${n}</b><span class="cg-meta">${x.role} · ${x.primary}</span><span class="cg-small">${x.res} · ${x.skill}</span></button>`).join('')}</div></section>`}
function step3(){const r=RACES[draft.race],c=CLASSES[draft.cls];return `<section class="cg-step ${draft.step===3?'on':''}"><div class="cg-label">SCHRITT 3 VON 3 · HINTERGRUND</div><div class="cg-grid">${Object.entries(BGS).map(([n,x])=>`<button type="button" class="cg-card ${draft.bg===n?'sel':''}" onclick="cgBg('${n}')"><span class="cg-icon">${x.icon}</span><b>${n}</b><span class="cg-small">${x.effect}</span></button>`).join('')}</div><div class="cg-summary"><div class="cg-hero">${r.icon}${c.icon}</div><h2>${draft.name||'Aventurier'}</h2><div class="cg-sub">${draft.race} · ${draft.cls} · ${draft.bg}</div><div class="cg-stat"><span>Hauptwerte</span><b>${r.bonus}</b></div><div class="cg-stat"><span>Ressource</span><b>${c.res}</b></div><div class="cg-stat"><span>Passive</span><b>${r.passive}</b></div><div class="cg-note">Nach „Held erschaffen“ ist der Charaktereditor nicht mehr verfügbar.</div></div></section>`}
window.cgName=v=>{draft.name=v.slice(0,24)};window.cgRace=v=>{draft.race=v;render()};window.cgClass=v=>{draft.cls=v;render()};window.cgBg=v=>{draft.bg=v;render()};window.cgPrev=()=>{draft.step=Math.max(1,draft.step-1);render()};window.cgNext=()=>{if(draft.step<3){if(draft.step===1&&!draft.name.trim())return alert('Bitte gib deinem Helden einen Namen.');draft.step++;render()}else{if(!draft.name.trim())return alert('Bitte gib deinem Helden einen Namen.');saveDraft();created=true;document.getElementById('character-gate')?.remove();location.reload()}};
style();if(!created)render();
})();