(()=>{
const R=window.ITEM_RARITY_V3||{common:{color:'#85858f'},magic:{color:'#45d483'},rare:{color:'#4b9cff'},epic:{color:'#b06cff'},mythic:{color:'#ff7043'},legendary:{color:'#ffd84d'}};let tab='upgrade',selected=null;
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function ensure(){S.forgeDust=Number(S.forgeDust)||0;S.essence=Number(S.essence)||0;S.legendaryEssence=Number(S.legendaryEssence)||0;S.ancestorRelics=Number(S.ancestorRelics)||0;S.autoSalvage=S.autoSalvage||{common:false,magic:false};all().forEach(it=>it.upgrade=Number(it.upgrade)||0)}
function all(){return [...(S.items||[]),...Object.values(S.eq||{}).filter(Boolean)]}function find(id){return all().find(x=>x.id===id)}
function art(it){return window.itemAssetTag?itemAssetTag(it,null,'fv3-art'):'◆'}
function cost(l){const n=l+1;return{n,gold:Math.round(45*Math.pow(1.72,n-1)),dust:Math.max(1,Math.round(2*Math.pow(1.42,n-1))),essence:n>=7?Math.round(Math.pow(2,n-7)):0}}
function chance(l){const b=[100,98,95,91,86,78,68,58,48,38][l]??38;return Math.min(100,b+(S.bg==='Runenschmied-Lehrling'?10:0))}
function yieldFor(it){const r={common:1,rare:2,magic:3,epic:5,mythic:9,legendary:0}[it.rarity]||1;return{dust:r*3+(it.upgrade||0)*2,essence:it.rarity==='epic'?1:it.rarity==='mythic'?3:0}}
function boost(it){it.power=(Number(it.power)||0)+1;const ks=Object.keys(it.bonus||{});if(ks.length){const k=ks[(it.upgrade-1)%ks.length];it.bonus[k]=Number(it.bonus[k]||0)+1}}
function upgrade(){ensure();const it=find(selected);if(!it)return toast('Wähle zuerst einen Gegenstand.');if(it.rarity==='legendary')return toast('Legendäre Gegenstände werden nicht weiter aufgewertet.');if(it.upgrade>=10)return toast('Dieser Gegenstand ist bereits +10.');const c=cost(it.upgrade),p=chance(it.upgrade);if(S.gold<c.gold)return toast(`${c.gold} Gold benötigt.`);if(S.forgeDust<c.dust)return toast(`${c.dust} Staub benötigt.`);if(S.essence<c.essence)return toast(`${c.essence} Essenz benötigt.`);const old={power:it.power,bonus:{...(it.bonus||{})}};S.gold-=c.gold;S.forgeDust-=c.dust;S.essence-=c.essence;if(Math.random()*100<p){it.upgrade++;boost(it);save();render();const changes=[];if(it.power>old.power)changes.push(`Macht ${old.power} → ${it.power}`);Object.keys(it.bonus||{}).forEach(k=>{if((it.bonus[k]||0)>(old.bonus[k]||0))changes.push(`${k.toUpperCase()} ${old.bonus[k]||0} → ${it.bonus[k]}`)});aqDialog?.({icon:'🔨',eyebrow:'Aufwertung erfolgreich',title:`${it.name} +${it.upgrade}`,message:changes.join('\n')||'Der Gegenstand wurde verbessert.'});}else{save();render();aqDialog?.({icon:'✦',eyebrow:'Schmiede',title:'Aufwertung fehlgeschlagen',message:'Materialien wurden verbraucht. Der Gegenstand bleibt unverändert.'})}}
function salvage(id){ensure();const ix=(S.items||[]).findIndex(x=>x.id===id);if(ix<0)return toast('Nur Gegenstände im Inventar können verwertet werden.');const it=S.items[ix];if(it.rarity==='legendary')return toast('Legendäre Gegenstände können nicht verwertet werden.');const y=yieldFor(it),doIt=()=>{const pos=(S.items||[]).findIndex(x=>x.id===id);if(pos<0)return;S.items.splice(pos,1);S.forgeDust+=y.dust;S.essence+=y.essence;if(selected===id)selected=null;log(`${it.name} verwertet: +${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}.`);save();render();toast(`${it.name} verwertet.`)};if(window.aqConfirm)aqConfirm({icon:'🔥',eyebrow:'Ahnenschmiede',title:`${it.name} verwerten?`,message:`Du erhältst ${y.dust} Staub${y.essence?` und ${y.essence} Essenz`:''}.`,confirmText:'Verwerten',cancelText:'Abbrechen',danger:true},doIt);else doIt()}
function card(it,mode){const y=yieldFor(it),sel=selected===it.id;return `<button class="fv3-item ${sel?'sel':''}" style="--rar:${R[it.rarity]?.color||'#888'}" onclick="fv3Select('${it.id}')"><span>${art(it)}</span><div><b>${esc(it.name)}${it.upgrade?` +${it.upgrade}`:''}</b><small>${esc(it.slot||'Item')} · Macht ${it.power||0}</small>${mode==='salvage'?`<em>+${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}</em>`:''}</div></button>`}
function upgradePane(){const it=find(selected);if(!it)return '<div class="fv3-empty">Wähle einen Gegenstand.</div>';const c=cost(it.upgrade||0),p=chance(it.upgrade||0);return `<div class="fv3-detail" style="--rar:${R[it.rarity]?.color||'#888'}"><div class="fv3-big">${art(it)}</div><div><small>AUFWERTUNG</small><h2>${esc(it.name)}${it.upgrade?` +${it.upgrade}`:''}</h2><p>${p}% Erfolg · 🪙 ${c.gold} · ✨ ${c.dust}${c.essence?` · ◆ ${c.essence}`:''}</p></div></div>${it.upgrade>=10?'<div class="fv3-max">Maximale Stufe +10 erreicht.</div>':`<button class="fv3-action" onclick="fv3Upgrade()">Auf +${c.n} schmieden</button>`}`}
function salvagePane(){const it=find(selected);return `<div class="fv3-list">${(S.items||[]).filter(x=>x.rarity!=='legendary').map(x=>card(x,'salvage')).join('')||'<div class="fv3-empty">Keine verwertbaren Gegenstände.</div>'}</div>${it&&S.items.includes(it)?`<button class="fv3-salvage" onclick="fv3Salvage('${it.id}')">${esc(it.name)} verwerten</button>`:''}`}
function ancestor(){const it=find(selected),ok=it?.rarity==='mythic'&&(it.upgrade||0)>=10;return `<div class="fv3-ancestor"><div class="fv3-star">★</div><h2>Legendäres Ahnenwerk</h2><p>Benötigt eine mythische +10 Basis, 100 Legendäre Essenzen, 50 Seelensteine und 1 Relikt.</p><div class="fv3-list">${all().filter(x=>x.rarity==='mythic').map(x=>card(x,'ancestor')).join('')||'<div class="fv3-empty">Keine mythische Basis vorhanden.</div>'}</div><button class="fv3-action" ${ok&&S.legendaryEssence>=100&&S.souls>=50&&S.ancestorRelics>=1?'':'disabled'} onclick="fv3Legendary()">Ahnenwerk vollenden</button></div>`}
function legendary(){const it=find(selected);if(!it||it.rarity!=='mythic'||it.upgrade<10)return toast('Benötigt wird ein mythisches Item +10.');if(S.legendaryEssence<100||S.souls<50||S.ancestorRelics<1)return toast('Materialien fehlen.');S.legendaryEssence-=100;S.souls-=50;S.ancestorRelics--;it.rarity='legendary';it.legendary=true;it.goldFind=15;save();render()}
function view(){ensure();if(S.lvl<5)return `<section class="fv3"><div class="hero"><div class="small">🔒 AB STUFE 5</div><h1>🔨 Ahnenschmiede</h1></div></section>`;return `<section class="fv3"><div class="fv3-head"><div><small>AHNENSCHMIEDE</small><h1>🔨 Schmiede</h1></div><div><span>🪙 ${S.gold}</span><span>✨ ${S.forgeDust}</span><span>◆ ${S.essence}</span></div></div><div class="fv3-tabs"><button class="${tab==='upgrade'?'on':''}" onclick="fv3Tab('upgrade')">Aufwerten</button><button class="${tab==='salvage'?'on':''}" onclick="fv3Tab('salvage')">Verwerten</button><button class="${tab==='ancestor'?'on':''}" onclick="fv3Tab('ancestor')">Ahnenwerk</button></div>${tab==='upgrade'?`<div class="fv3-list">${all().map(x=>card(x,'upgrade')).join('')||'<div class="fv3-empty">Keine Items.</div>'}</div>${upgradePane()}`:tab==='salvage'?salvagePane():ancestor()}</section>`}
window.forgeView=view;window.fv3Tab=x=>{tab=x;selected=null;render()};window.fv3Select=id=>{selected=selected===id?null:id;render()};window.fv3Upgrade=upgrade;window.fv3Salvage=salvage;window.fv3Legendary=legendary;
const oldRender=window.render;window.render=function(){if(S.screen==='forge'){const app=document.getElementById('app');if(app){app.innerHTML=`<header><div class="top"><div class="brand">🔨 Ahnenschmiede</div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span></div></div></header><main>${view()}</main><nav class="tabs"></nav>`;return} }return oldRender.apply(this,arguments)};
const css=document.createElement('style');css.textContent=`.fv3{max-width:760px;margin:auto}.fv3-head{display:flex;justify-content:space-between;align-items:center;padding:12px;background:var(--panel);border-radius:14px}.fv3-head h1{margin:2px 0;font-size:20px}.fv3-head small{font-size:8px;color:var(--muted)}.fv3-head>div:last-child{display:flex;gap:5px}.fv3-head span{font-size:9px;background:#ffffff08;padding:6px;border-radius:999px}.fv3-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:7px 0}.fv3-tabs button{background:#ffffff08;box-shadow:none;font-size:9px}.fv3-tabs .on{background:#7149b7}.fv3-list{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.fv3-item{display:grid;grid-template-columns:48px 1fr;gap:8px;text-align:left;align-items:center;background:#ffffff06;border:1px solid #ffffff0d;border-left:3px solid var(--rar);box-shadow:none}.fv3-item>span,.fv3-big{display:block;width:46px;height:46px;overflow:hidden;border-radius:9px;background:#0d0912}.fv3-item b,.fv3-item small,.fv3-item em{display:block}.fv3-item b{font-size:9px}.fv3-item small,.fv3-item em{font-size:7px;color:var(--muted)}.fv3-item em{color:var(--gold);font-style:normal}.fv3-item.sel{border-color:var(--rar)}.fv3-detail{display:grid;grid-template-columns:64px 1fr;gap:10px;margin-top:8px;padding:10px;background:var(--panel);border:1px solid var(--rar);border-radius:12px}.fv3-big{width:62px;height:62px}.fv3-detail h2{font-size:14px;margin:2px 0}.fv3-detail p{font-size:8px;color:var(--muted)}.fv3-action,.fv3-salvage{width:100%;margin-top:7px}.fv3-salvage{background:linear-gradient(135deg,#9a3449,#d85b6e)}.fv3-empty{grid-column:1/-1;padding:18px;text-align:center;color:var(--muted);font-size:9px}.fv3-max{padding:10px;margin-top:7px;background:#71d59a12;border-radius:10px;color:#9ce0b5}.fv3-ancestor{text-align:center}.fv3-star{font-size:38px;color:var(--gold)}.fv3-ancestor p{font-size:9px;color:var(--muted)}@media(max-width:430px){.fv3-list{grid-template-columns:1fr}}`;document.head.appendChild(css);
})();