(()=>{
'use strict';
const R=window.ITEM_RARITY_V3||{common:{color:'#85858f'},magic:{color:'#45d483'},rare:{color:'#4b9cff'},epic:{color:'#b06cff'},mythic:{color:'#ff7043'},legendary:{color:'#ffd84d'}};
const ROOT='assets/icons/ui/';let tab='upgrade',selected=null,showAll=false;
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const ico=(f,c='fv4-res')=>`<img class="${c}" src="${ROOT}${f}" alt="">`;
function ensure(){S.forgeDust=Number(S.forgeDust)||0;S.essence=Number(S.essence)||0;S.legendaryEssence=Number(S.legendaryEssence)||0;S.ancestorRelics=Number(S.ancestorRelics)||0;S.autoSalvage=S.autoSalvage||{common:false,magic:false};all().forEach(it=>it.upgrade=Number(it.upgrade)||0)}
function all(){return [...(S.items||[]),...Object.values(S.eq||{}).filter(Boolean)]}function find(id){return all().find(x=>x.id===id)}
function art(it,cls='fv4-art'){return window.itemAssetTag?itemAssetTag(it,null,cls):'◆'}
function yieldFor(it){const r={common:1,rare:2,magic:3,epic:5,mythic:9,legendary:0}[it.rarity]||1;return{dust:r*3+(it.upgrade||0)*2,essence:it.rarity==='epic'?1:it.rarity==='mythic'?3:0}}
function cost(l){const n=l+1;return{gold:Math.round(45*Math.pow(1.72,n-1)),dust:Math.max(1,Math.round(2*Math.pow(1.42,n-1))),essence:n>=7?Math.round(Math.pow(2,n-7)):0}}
function chance(l){const b=[100,98,95,91,86,78,68,58,48,38][l]??38;return Math.min(100,b+(S.bg==='Runenschmied-Lehrling'?10:0))}
function wallet(){return `<div class="fv4-wallet"><span>${ico('resource_gold.webp')}<b>${Number(S.gold)||0}</b></span><span>${ico('resource_forge_dust.webp')}<b>${Number(S.forgeDust)||0}</b></span><span>${ico('resource_forge_essence.webp')}<b>${Number(S.essence)||0}</b></span></div>`}
function tabs(){return `<div class="fv4-tabs" aria-label="Schmiedebereiche"><button class="${tab==='upgrade'?'on':''}" onclick="fv4Tab('upgrade')">Aufwerten</button><button class="${tab==='salvage'?'on':''}" onclick="fv4Tab('salvage')">Verwerten</button><button class="${tab==='ancestor'?'on':''}" onclick="fv4Tab('ancestor')">Ahnenwerk</button></div>`}
function doSalvage(id){const pos=(S.items||[]).findIndex(x=>x.id===id);if(pos<0)return false;const it=S.items[pos];if(it.rarity==='legendary')return false;const y=yieldFor(it);S.items.splice(pos,1);S.forgeDust+=y.dust;S.essence+=y.essence;return{it,y}}
function salvage(id){const it=(S.items||[]).find(x=>x.id===id);if(!it)return;const y=yieldFor(it),run=()=>{if(!doSalvage(id))return;save?.();render?.();toast?.(`${it.name} verwertet: +${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}.`)};window.aqConfirm?aqConfirm({eyebrow:'Ahnenschmiede',title:`${it.name} verwerten?`,message:`Du erhältst ${y.dust} Staub${y.essence?` und ${y.essence} Essenz`:''}.`,confirmText:'Verwerten',cancelText:'Abbrechen',danger:true},run):run()}
function salvageAll(){const items=(S.items||[]).filter(x=>x.rarity!=='legendary');if(!items.length)return toast?.('Keine verwertbaren Gegenstände.');const run=()=>{items.forEach(x=>doSalvage(x.id));save?.();render?.()};window.aqConfirm?aqConfirm({eyebrow:'Ahnenschmiede',title:`Alle ${items.length} Items verwerten?`,message:'Alle verwertbaren Inventargegenstände werden zerlegt. Legendäre Items bleiben erhalten.',confirmText:'Alles verwerten',cancelText:'Abbrechen',danger:true},run):run()}
function mini(it,mode='select'){const y=yieldFor(it);return `<button class="fv4-mini" style="--rar:${R[it.rarity]?.color||'#888'}" onclick="${mode==='salvage'?`fv4Salvage('${it.id}')`:`fv4Select('${it.id}')`}"><span class="fv4-mini-art">${art(it,'fv4-mini-img')}</span><span class="fv4-mini-copy"><b>${esc(it.name)}</b><small>${mode==='salvage'?`+${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}`:`${esc(it.slot||'Item')} · Macht ${it.power||0}`}</small></span>${mode==='salvage'?'<em>ZERLEGEN</em>':''}</button>`}
function chooser(items,title,mode='select'){const visible=showAll?items:items.slice(0,6);return `<section class="fv4-chooser ${mode==='salvage'?'fv4-salvage-chooser':''}"><div class="fv4-section-title"><span>${title}</span>${items.length>6?`<button onclick="fv4ToggleAll()">${showAll?'Weniger':'Alle anzeigen'}</button>`:''}</div><div class="fv4-strip ${showAll?'all':''}">${visible.map(x=>mini(x,mode)).join('')||'<div class="fv4-empty">Keine passenden Gegenstände.</div>'}</div></section>`}
function salvagePane(){const items=(S.items||[]).filter(x=>x.rarity!=='legendary'),total=items.reduce((a,it)=>{const y=yieldFor(it);a.dust+=y.dust;a.essence+=y.essence;return a},{dust:0,essence:0});return `${tabs()}<section class="fv4-salvage-compact"><div><small>AUSRÜSTUNG VERWERTEN</small><h2>Fundstücke zerlegen</h2><p>Tippe unten auf ein Item, um es einzeln zu zerlegen.</p></div><div class="fv4-salvage-summary"><span><b>${items.length}</b><small>Items</small></span><span><b>${total.dust}</b><small>Staub</small></span><span><b>${total.essence}</b><small>Essenz</small></span></div><button ${items.length?'':'disabled'} onclick="fv4SalvageAll()">ALLES VERWERTEN</button></section>${chooser(items,'GEGENSTÄNDE','salvage')}`}
function upgradePane(items){let it=find(selected)||items[0];if(!it)return `${tabs()}<div class="fv4-empty">Keine Ausrüstung vorhanden.</div>`;selected=it.id;const c=cost(it.upgrade||0),p=chance(it.upgrade||0);return `${tabs()}<section class="fv4-workbench" style="--rar:${R[it.rarity]?.color||'#888'}"><div class="fv4-focus"><div class="fv4-focus-art">${art(it,'fv4-focus-img')}</div><h2>${esc(it.name)}</h2><p>${esc(it.slot||'Item')} · Macht ${it.power||0}</p></div><div class="fv4-costs"><span>${ico('resource_gold.webp','fv4-cost-icon')}<b>${c.gold}</b></span><span>${ico('resource_forge_dust.webp','fv4-cost-icon')}<b>${c.dust}</b></span></div><button class="fv4-action" onclick="fv4Upgrade()">AUFWERTEN · ${p}%</button></section>${chooser(items,'AUSRÜSTUNG WECHSELN')}`}
function ancestorPane(){return `${tabs()}<section class="fv4-workbench"><div class="fv4-eyebrow">LEGENDÄRES AHNENWERK</div><h2>Ahnenwerk</h2><p>Mythische Gegenstände auf +10 können hier künftig vollendet werden.</p></section>`}
function view(){ensure();const items=all().filter(x=>x.rarity!=='legendary');return `<section class="fv4"><header class="fv4-head"><div><small>AHNENSCHMIEDE</small><h1>Ahnenschmiede</h1></div>${wallet()}</header>${tab==='salvage'?salvagePane():tab==='ancestor'?ancestorPane():upgradePane(items)}</section>`}
window.forgeView=view;window.fv4Tab=x=>{tab=x;selected=null;showAll=false;render?.()};window.fv4Select=id=>{selected=id;render?.()};window.fv4ToggleAll=()=>{showAll=!showAll;render?.()};window.fv4Salvage=salvage;window.fv4SalvageAll=salvageAll;
window.fv4Upgrade=()=>{const it=find(selected);if(!it)return;const c=cost(it.upgrade||0);if((S.gold||0)<c.gold||(S.forgeDust||0)<c.dust)return toast?.('Materialien fehlen.');S.gold-=c.gold;S.forgeDust-=c.dust;if(Math.random()*100<chance(it.upgrade||0)){it.upgrade=(it.upgrade||0)+1;it.power=(Number(it.power)||0)+1}save?.();render?.()};
const st=document.createElement('style');st.id='forge-v5-css';st.textContent=`
.fv4 .fv4-wallet{display:flex!important;flex-wrap:nowrap!important;gap:4px!important;overflow:visible!important}.fv4 .fv4-wallet span{display:flex!important;align-items:center!important;gap:2px!important;padding:3px 5px!important;min-width:0!important}.fv4 .fv4-wallet b{display:inline!important;visibility:visible!important;opacity:1!important;position:static!important;width:auto!important;max-width:none!important;color:#f7f0e8!important;font-size:8px!important;line-height:1!important;white-space:nowrap!important}.fv4 .fv4-wallet .fv4-res{width:19px!important;height:19px!important;flex:0 0 19px!important}.fv4 .fv4-head{overflow:visible!important}.fv4-salvage-compact{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:9px 12px;align-items:center;padding:12px;border:1px solid #b9814938;border-radius:16px;background:linear-gradient(145deg,#1d1425,#100c15);text-align:left}.fv4-salvage-compact>div:first-child small{font-size:7px;letter-spacing:.13em;color:#d7aa68;font-weight:850}.fv4-salvage-compact h2{margin:2px 0;font-size:16px}.fv4-salvage-compact p{margin:0;font-size:7.5px;color:var(--muted)}.fv4-salvage-summary{display:flex;gap:4px}.fv4-salvage-summary span{min-width:46px;padding:5px;border:1px solid #ffffff0d;border-radius:9px;background:#0b0810;text-align:center}.fv4-salvage-summary b{display:block;font-size:11px}.fv4-salvage-summary small{font-size:6px;color:var(--muted)}.fv4-salvage-compact>button{grid-column:1/-1;min-height:38px;padding:8px;background:linear-gradient(135deg,#703047,#a84457);font-size:9px}.fv4-salvage-chooser{margin-top:8px}.fv4-salvage-chooser .fv4-strip{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;grid-auto-flow:row!important;grid-auto-columns:auto!important;gap:6px!important;overflow:visible!important}.fv4-salvage-chooser .fv4-mini{display:grid!important;grid-template-columns:52px minmax(0,1fr)!important;grid-template-rows:auto auto!important;gap:2px 7px!important;align-items:center!important;min-height:68px!important;padding:7px!important;text-align:left!important}.fv4-salvage-chooser .fv4-mini-art{grid-row:1/3;width:50px!important;height:50px!important;margin:0!important}.fv4-salvage-chooser .fv4-mini-img{width:48px!important;height:48px!important}.fv4-salvage-chooser .fv4-mini-copy{min-width:0}.fv4-salvage-chooser .fv4-mini b{font-size:7.5px!important}.fv4-salvage-chooser .fv4-mini small{font-size:6.5px!important;color:#d7aa68!important}.fv4-salvage-chooser .fv4-mini em{position:static!important;grid-column:2!important;padding:0!important;background:none!important;font-size:6px!important;color:#e77f8b!important;letter-spacing:.08em!important}
@media(max-width:430px){.fv4 .fv4-head{grid-template-columns:minmax(0,1fr) auto!important}.fv4 .fv4-wallet{gap:1px!important}.fv4 .fv4-wallet span{padding:2px 3px!important}.fv4 .fv4-wallet b{font-size:7px!important}.fv4 .fv4-wallet .fv4-res{width:17px!important;height:17px!important;flex-basis:17px!important}.fv4-salvage-compact{grid-template-columns:1fr!important}.fv4-salvage-summary{justify-content:flex-start}.fv4-salvage-chooser .fv4-strip{grid-template-columns:1fr!important}}
`;document.head.appendChild(st);
})();