(()=>{
const R=window.ITEM_RARITY_V3||{common:{color:'#85858f'},magic:{color:'#45d483'},rare:{color:'#4b9cff'},epic:{color:'#b06cff'},mythic:{color:'#ff7043'},legendary:{color:'#ffd84d'}};let tab='upgrade',selected=null;
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function ensure(){S.forgeDust=Number(S.forgeDust)||0;S.essence=Number(S.essence)||0;S.legendaryEssence=Number(S.legendaryEssence)||0;S.ancestorRelics=Number(S.ancestorRelics)||0;S.autoSalvage=S.autoSalvage||{common:false,magic:false};all().forEach(it=>it.upgrade=Number(it.upgrade)||0)}
function all(){return [...(S.items||[]),...Object.values(S.eq||{}).filter(Boolean)]}function find(id){return all().find(x=>x.id===id)}
function art(it){return window.itemAssetTag?itemAssetTag(it,null,'fv4-art'):'◆'}
function cost(l){const n=l+1;return{n,gold:Math.round(45*Math.pow(1.72,n-1)),dust:Math.max(1,Math.round(2*Math.pow(1.42,n-1))),essence:n>=7?Math.round(Math.pow(2,n-7)):0}}
function chance(l){const b=[100,98,95,91,86,78,68,58,48,38][l]??38;return Math.min(100,b+(S.bg==='Runenschmied-Lehrling'?10:0))}
function yieldFor(it){const r={common:1,rare:2,magic:3,epic:5,mythic:9,legendary:0}[it.rarity]||1;return{dust:r*3+(it.upgrade||0)*2,essence:it.rarity==='epic'?1:it.rarity==='mythic'?3:0}}
function boost(it){it.power=(Number(it.power)||0)+1;const ks=Object.keys(it.bonus||{});if(ks.length){const k=ks[(it.upgrade-1)%ks.length];it.bonus[k]=Number(it.bonus[k]||0)+1}}
function upgrade(){ensure();const it=find(selected);if(!it)return toast('Wähle zuerst einen Gegenstand.');if(it.rarity==='legendary')return toast('Legendäre Gegenstände werden nicht weiter aufgewertet.');if(it.upgrade>=10)return toast('Dieser Gegenstand ist bereits +10.');const c=cost(it.upgrade),p=chance(it.upgrade);if(S.gold<c.gold)return toast(`${c.gold} Gold benötigt.`);if(S.forgeDust<c.dust)return toast(`${c.dust} Staub benötigt.`);if(S.essence<c.essence)return toast(`${c.essence} Essenz benötigt.`);const old={power:it.power,bonus:{...(it.bonus||{})}};S.gold-=c.gold;S.forgeDust-=c.dust;S.essence-=c.essence;if(Math.random()*100<p){it.upgrade++;boost(it);save();render();const changes=[];if(it.power>old.power)changes.push(`Macht ${old.power} → ${it.power}`);Object.keys(it.bonus||{}).forEach(k=>{if((it.bonus[k]||0)>(old.bonus[k]||0))changes.push(`${k.toUpperCase()} ${old.bonus[k]||0} → ${it.bonus[k]}`)});aqDialog?.({icon:'🔨',eyebrow:'Aufwertung erfolgreich',title:`${it.name} +${it.upgrade}`,message:changes.join('\n')||'Der Gegenstand wurde verbessert.'});}else{save();render();aqDialog?.({icon:'✦',eyebrow:'Schmiede',title:'Aufwertung fehlgeschlagen',message:'Materialien wurden verbraucht. Der Gegenstand bleibt unverändert.'})}}
function doSalvage(id){const pos=(S.items||[]).findIndex(x=>x.id===id);if(pos<0)return false;const it=S.items[pos];if(it.rarity==='legendary')return false;const y=yieldFor(it);S.items.splice(pos,1);S.forgeDust+=y.dust;S.essence+=y.essence;if(selected===id)selected=null;log(`${it.name} verwertet: +${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}.`);return {it,y}}
function salvage(id){ensure();const it=(S.items||[]).find(x=>x.id===id);if(!it)return toast('Nur Gegenstände im Inventar können verwertet werden.');if(it.rarity==='legendary')return toast('Legendäre Gegenstände können nicht verwertet werden.');const y=yieldFor(it),run=()=>{const res=doSalvage(id);if(!res)return;save();render();toast(`${it.name} verwertet: +${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}.`)};if(window.aqConfirm)aqConfirm({icon:'🔥',eyebrow:'Ahnenschmiede',title:`${it.name} verwerten?`,message:`Du erhältst ${y.dust} Staub${y.essence?` und ${y.essence} Essenz`:''}.`,confirmText:'Verwerten',cancelText:'Abbrechen',danger:true},run);else run()}
function salvageAll(){ensure();const items=(S.items||[]).filter(x=>x.rarity!=='legendary');if(!items.length)return toast('Keine verwertbaren Gegenstände im Inventar.');const total=items.reduce((a,it)=>{const y=yieldFor(it);a.dust+=y.dust;a.essence+=y.essence;return a},{dust:0,essence:0});const run=()=>{const ids=items.map(x=>x.id);ids.forEach(doSalvage);save();render();toast(`${items.length} Items verwertet: +${total.dust} Staub${total.essence?` · +${total.essence} Essenz`:''}.`)};if(window.aqConfirm)aqConfirm({icon:'🔥',eyebrow:'Ahnenschmiede',title:`Alle ${items.length} Items verwerten?`,message:`Alle verwertbaren Gegenstände im Inventar werden zerlegt. Du erhältst ${total.dust} Staub${total.essence?` und ${total.essence} Essenz`:''}. Legendäre Items bleiben erhalten.`,confirmText:'Alles verwerten',cancelText:'Abbrechen',danger:true},run);else run()}
function card(it,mode){const y=yieldFor(it),sel=selected===it.id,body=`<span class="fv4-artbox">${art(it)}</span><div class="fv4-info"><b>${esc(it.name)}${it.upgrade?` +${it.upgrade}`:''}</b><small>${esc(it.slot||'Item')} · Macht ${it.power||0}</small>${mode==='salvage'?`<em>+${y.dust} Staub${y.essence?` · +${y.essence} Essenz`:''}</em>`:''}</div>`;if(mode==='salvage')return `<div class="fv4-item fv4-salvage-row" style="--rar:${R[it.rarity]?.color||'#888'}">${body}<button class="fv4-inline-salvage" onclick="fv4Salvage('${it.id}')">Verwerten</button></div>`;return `<button class="fv4-item ${sel?'sel':''}" style="--rar:${R[it.rarity]?.color||'#888'}" onclick="fv4Select('${it.id}')">${body}</button>`}
function upgradePane(){const it=find(selected);if(!it)return '<div class="fv4-empty">Wähle einen Gegenstand.</div>';const c=cost(it.upgrade||0),p=chance(it.upgrade||0);return `<div class="fv4-detail" style="--rar:${R[it.rarity]?.color||'#888'}"><div class="fv4-big">${art(it)}</div><div><small>AUFWERTUNG</small><h2>${esc(it.name)}${it.upgrade?` +${it.upgrade}`:''}</h2><p>${p}% Erfolg · 🪙 ${c.gold} · ✨ ${c.dust}${c.essence?` · ◆ ${c.essence}`:''}</p></div></div>${it.upgrade>=10?'<div class="fv4-max">Maximale Stufe +10 erreicht.</div>':`<button class="fv4-action" onclick="fv4Upgrade()">Auf +${c.n} schmieden</button>`}`}
function salvagePane(){const usable=(S.items||[]).filter(x=>x.rarity!=='legendary');return `<div class="fv4-salvage-head"><div><b>Inventar verwerten</b><small>${usable.length} verwertbare Item${usable.length===1?'':'s'}</small></div><button class="fv4-all" ${usable.length?'':'disabled'} onclick="fv4SalvageAll()">Alles verwerten</button></div><div class="fv4-list fv4-salvage-list">${usable.map(x=>card(x,'salvage')).join('')||'<div class="fv4-empty">Keine verwertbaren Gegenstände.</div>'}</div>`}
function ancestor(){const it=find(selected),ok=it?.rarity==='mythic'&&(it.upgrade||0)>=10;return `<div class="fv4-ancestor"><div class="fv4-star">★</div><h2>Legendäres Ahnenwerk</h2><p>Benötigt eine mythische +10 Basis, 100 Legendäre Essenzen, 50 Seelensteine und 1 Relikt.</p><div class="fv4-list">${all().filter(x=>x.rarity==='mythic').map(x=>card(x,'ancestor')).join('')||'<div class="fv4-empty">Keine mythische Basis vorhanden.</div>'}</div><button class="fv4-action" ${ok&&S.legendaryEssence>=100&&S.souls>=50&&S.ancestorRelics>=1?'':'disabled'} onclick="fv4Legendary()">Ahnenwerk vollenden</button></div>`}
function legendary(){const it=find(selected);if(!it||it.rarity!=='mythic'||it.upgrade<10)return toast('Benötigt wird ein mythisches Item +10.');if(S.legendaryEssence<100||S.souls<50||S.ancestorRelics<1)return toast('Materialien fehlen.');S.legendaryEssence-=100;S.souls-=50;S.ancestorRelics--;it.rarity='legendary';it.legendary=true;it.goldFind=15;save();render()}
function view(){ensure();if(S.lvl<5)return `<section class="fv4"><div class="hero"><div class="small">🔒 AB STUFE 5</div><h1>🔨 Ahnenschmiede</h1></div></section>`;return `<section class="fv4"><div class="fv4-head"><div><small>AHNENSCHMIEDE</small><h1>🔨 Schmiede</h1></div><div><span>🪙 ${S.gold}</span><span>✨ ${S.forgeDust}</span><span>◆ ${S.essence}</span></div></div><div class="fv4-tabs"><button class="${tab==='upgrade'?'on':''}" onclick="fv4Tab('upgrade')">Aufwerten</button><button class="${tab==='salvage'?'on':''}" onclick="fv4Tab('salvage')">Verwerten</button><button class="${tab==='ancestor'?'on':''}" onclick="fv4Tab('ancestor')">Ahnenwerk</button></div>${tab==='upgrade'?`<div class="fv4-list">${all().map(x=>card(x,'upgrade')).join('')||'<div class="fv4-empty">Keine Items.</div>'}</div>${upgradePane()}`:tab==='salvage'?salvagePane():ancestor()}</section>`}
window.forgeView=view;window.fv4Tab=x=>{tab=x;selected=null;render()};window.fv4Select=id=>{selected=selected===id?null:id;render()};window.fv4Upgrade=upgrade;window.fv4Salvage=salvage;window.fv4SalvageAll=salvageAll;window.fv4Legendary=legendary;
const oldRender=window.render;window.render=function(){if(S.screen==='forge'){const app=document.getElementById('app');if(app){app.innerHTML=`<header><div class="top"><div class="brand">🔨 Ahnenschmiede</div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span></div></div></header><main>${view()}</main><nav class="tabs"></nav>`;return} }return oldRender.apply(this,arguments)};
const css=document.createElement('style');css.textContent=`.fv4{max-width:760px;margin:auto}.fv4-head{display:flex;justify-content:space-between;align-items:center;padding:12px;background:var(--panel);border-radius:14px}.fv4-head h1{margin:2px 0;font-size:20px}.fv4-head small{font-size:8px;color:var(--muted)}.fv4-head>div:last-child{display:flex;gap:5px}.fv4-head span{font-size:9px;background:#ffffff08;padding:6px;border-radius:999px}.fv4-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:7px 0}.fv4-tabs button{background:#ffffff08;box-shadow:none;font-size:9px}.fv4-tabs .on{background:#7149b7}.fv4-list{display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.fv4-item{display:grid;grid-template-columns:48px 1fr;gap:8px;text-align:left;align-items:center;background:#ffffff06;border:1px solid #ffffff0d;border-left:3px solid var(--rar);box-shadow:none;border-radius:14px;padding:10px 12px;color:var(--text)}.fv4-artbox,.fv4-big{display:block;width:46px;height:46px;overflow:hidden;border-radius:9px;background:#0d0912}.fv4-info b,.fv4-info small,.fv4-info em{display:block}.fv4-info b{font-size:9px}.fv4-info small,.fv4-info em{font-size:7px;color:var(--muted)}.fv4-info em{color:var(--gold);font-style:normal}.fv4-item.sel{border-color:var(--rar)}.fv4-salvage-row{grid-template-columns:48px minmax(0,1fr) auto}.fv4-inline-salvage{padding:7px 9px;font-size:8px;box-shadow:none;border-radius:9px;background:linear-gradient(135deg,#873146,#c94f65);white-space:nowrap}.fv4-salvage-head{position:sticky;top:0;z-index:2;display:flex;align-items:center;justify-content:space-between;gap:10px;padding:9px 10px;margin:0 0 7px;background:#17111ff2;border:1px solid #ffffff10;border-radius:11px;backdrop-filter:blur(8px)}.fv4-salvage-head b,.fv4-salvage-head small{display:block}.fv4-salvage-head b{font-size:10px}.fv4-salvage-head small{font-size:8px;color:var(--muted);margin-top:2px}.fv4-all{padding:8px 10px;font-size:8px;background:linear-gradient(135deg,#873146,#c94f65);box-shadow:none}.fv4-detail{display:grid;grid-template-columns:64px 1fr;gap:10px;margin-top:8px;padding:10px;background:var(--panel);border:1px solid var(--rar);border-radius:12px}.fv4-big{width:62px;height:62px}.fv4-detail h2{font-size:14px;margin:2px 0}.fv4-detail p{font-size:8px;color:var(--muted)}.fv4-action{width:100%;margin-top:7px}.fv4-empty{grid-column:1/-1;padding:18px;text-align:center;color:var(--muted);font-size:9px}.fv4-max{padding:10px;margin-top:7px;background:#71d59a12;border-radius:10px;color:#9ce0b5}.fv4-ancestor{text-align:center}.fv4-star{font-size:38px;color:var(--gold)}.fv4-ancestor p{font-size:9px;color:var(--muted)}@media(max-width:520px){.fv4-list{grid-template-columns:1fr}.fv4-salvage-row{grid-template-columns:46px minmax(0,1fr) auto}.fv4-inline-salvage{padding:7px 8px}}`;document.head.appendChild(css);
})();