(()=>{
const EQUIP_SLOTS=['Kopf','Schulter','Brust','Beine','Stiefel','Amulett','Ring','Haupthand','Zweithand'];
const SLOT_ALIASES={'Ring 1':'Ring','Ring 2':'Ring',Schultern:'Schulter',Nebenhand:'Zweithand'};
const RARITY_MULT={common:1,magic:1.2,rare:1.45,mythic:2.3,legendary:2.3};
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
function id(){return 'i'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function normSlot(s){return SLOT_ALIASES[s]||s}
function normalizeItem(x){if(!x)return x;x.id=x.id||id();x.slot=normSlot(x.slot||'Beute');if(['Gürtel','Handschuhe'].includes(x.slot))x.slot='Beute';x.rarity=x.rarity||'common';x.power=Number(x.power)||1;x.bonus=x.bonus||{};if(!Object.keys(x.bonus).length){if(x.name==='Rostiges Schwert'){x.slot='Haupthand';x.bonus={str:1,damage:2}}else if(x.slot==='Stiefel')x.bonus={agi:1,dodge:2};else if(x.slot==='Ring')x.bonus={int:1,crit:2}}return x}
function migrate(){S.items=(S.items||[]).map(normalizeItem);S.eq=S.eq||{};const old=Object.entries(S.eq);S.eq={};for(const [k,v0] of old){if(!v0)continue;const v=normalizeItem(v0),slot=normSlot(k);if(v.slot==='Beute'||!EQUIP_SLOTS.includes(slot)){S.items.push(v);continue}if(slot==='Ring'&&S.eq.Ring){v.slot='Ring';S.items.push(v);continue}v.slot=slot;S.eq[slot]=v}save()}
function finalStats(){const race=RACES?.[S.race]||{},stats={str:8+(S.lvl-1),agi:8+(S.lvl-1),int:8+(S.lvl-1),hp:120+(S.lvl-1)*10,armor:0,damage:0,crit:0,dodge:0,block:0};Object.entries(race.bonus||{}).forEach(([k,v])=>stats[k]=(stats[k]||0)+v);Object.values(S.eq||{}).forEach(it=>{if(!it)return;Object.entries(it.bonus||{}).forEach(([k,v])=>stats[k]=(stats[k]||0)+Number(v||0))});return stats}
function bonusText(it){const names={str:'STR',agi:'AGI',int:'INT',hp:'HP',armor:'Rüstung',damage:'Schaden',crit:'Krit',dodge:'Ausweichen',block:'Block'};return Object.entries(it?.bonus||{}).filter(([,v])=>v).map(([k,v])=>`+${v}${['crit','dodge','block'].includes(k)?'%':''} ${names[k]||k}`).join(' · ')||'Keine direkten Werte'}
function compareText(it){if(!it||!EQUIP_SLOTS.includes(it.slot))return '';const old=S.eq?.[it.slot];if(!old)return 'Slot ist frei.';const keys=[...new Set([...Object.keys(it.bonus||{}),...Object.keys(old.bonus||{})])];return keys.map(k=>{const d=(it.bonus?.[k]||0)-(old.bonus?.[k]||0);return d?`${k.toUpperCase()} ${d>0?'+':''}${d}`:''}).filter(Boolean).join(' · ')||'Ähnliche Werte wie aktuell.'}
function equip(itemId){const ix=S.items.findIndex(x=>x.id===itemId);if(ix<0)return;const it=S.items[ix];if(!EQUIP_SLOTS.includes(it.slot))return toast('Dieser Gegenstand kann nicht ausgerüstet werden.');const old=S.eq[it.slot];S.items.splice(ix,1);if(old)S.items.push(old);S.eq[it.slot]=it;S.hp=Math.min(finalStats().hp,S.hp||finalStats().hp);log(`${it.name} ausgerüstet.`);save();render()}
function unequip(slot){const it=S.eq?.[slot];if(!it)return;if(S.items.length>=S.invCap)return toast('Inventar voll.');delete S.eq[slot];S.items.push(it);log(`${it.name} abgelegt.`);save();render()}
function createLoot(kind='general',rarity='magic',level=S.lvl||1){const p=Math.max(1,level+Math.floor(Math.random()*3)),mult=RARITY_MULT[rarity]||1;const pools={bounty:[['Knochenhauerschild','Zweithand',{armor:Math.ceil(3*mult),block:Math.ceil(5*mult),hp:Math.ceil(8*mult)}],['Knochenspalt-Beinschutz','Beine',{armor:Math.ceil(3*mult),hp:Math.ceil(12*mult)}],['Jägerring des Knochenhauers','Ring',{str:Math.ceil(1*mult),crit:Math.ceil(2*mult)}]],event:[['Arkaner Siegelring','Ring',{int:Math.ceil(2*mult),crit:Math.ceil(2*mult)}],['Runenleder-Stiefel','Stiefel',{agi:Math.ceil(2*mult),dodge:Math.ceil(3*mult)}],['Siegelamulett','Amulett',{int:Math.ceil(1*mult),hp:Math.ceil(8*mult)}]],risk:[['Kryptenklinge','Haupthand',{str:Math.ceil(2*mult),damage:Math.ceil(4*mult)}],['Schattenstiefel','Stiefel',{agi:Math.ceil(2*mult),dodge:Math.ceil(4*mult)}],['Kryptenpanzer','Brust',{armor:Math.ceil(4*mult),hp:Math.ceil(14*mult)}]],general:[['Abenteurerring','Ring',{agi:1,crit:2}],['Reiseleder','Brust',{armor:2,hp:8}],['Wanderstiefel','Stiefel',{agi:1,dodge:2}]]};const pool=pools[kind]||pools.general,[name,slot,bonus]=pool[Math.floor(Math.random()*pool.length)];return normalizeItem({id:id(),name,slot,power:p,rarity,bonus})}
function itemRows(){return (S.items||[]).map(it=>`<div class="is-item"><div><b>${esc(it.name)}</b><small>${esc(it.slot)} · Macht ${it.power} · ${esc(bonusText(it))}</small>${EQUIP_SLOTS.includes(it.slot)?`<em>${esc(compareText(it))}</em>`:''}</div><div><span class="rarity ${esc(it.rarity)}">${esc(it.rarity)}</span>${EQUIP_SLOTS.includes(it.slot)?`<button onclick="equipItem('${it.id}')">Ausrüsten</button>`:''}</div></div>`).join('')||'<div class="small">Inventar leer.</div>'}
window.inv=function(){return `<section class="is-page"><div class="hero is-hero"><div><div class="small">INVENTAR</div><h1>Rucksack</h1></div><b>${S.items.length}/${S.invCap}</b></div><div class="card is-list">${itemRows()}</div></section>`}
window.getFinalStats=finalStats;window.itemBonusText=bonusText;window.itemCompareText=compareText;window.equipItem=equip;window.unequipItem=unequip;window.createLoot=createLoot;window.EQUIP_SLOTS=EQUIP_SLOTS;
const st=document.createElement('style');st.textContent=`.is-hero{display:flex;justify-content:space-between;align-items:center;padding:13px 15px}.is-hero h1{font-size:20px;margin:2px 0}.is-list{margin-top:8px;padding:8px 11px}.is-item{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:9px 0;border-bottom:1px solid #ffffff09}.is-item b{font-size:11px}.is-item small,.is-item em{display:block;font-size:8px;color:var(--muted);font-style:normal;margin-top:2px}.is-item em{color:var(--gold)}.is-item>div:last-child{text-align:right}.is-item button{display:block;margin-top:4px;padding:5px 7px;font-size:8px;border-radius:8px;box-shadow:none}.is-item .rarity{font-size:8px}`;document.head.appendChild(st);migrate();
})();