(()=>{
const RAR={common:1,magic:1.2,rare:1.45,mythic:2.3};
function init(){S.city=S.city||{view:'merchant',stock:null,stamp:0};S.bank=S.bank||[];S.bankCap=100;if(S.lvl>=3&&!S.city.stock)refresh(true)}
function rname(r){return({common:'Gewöhnlich',magic:'Magisch',rare:'Selten',mythic:'Mythisch'})[r]||r}
function icon(slot){return({Haupthand:'⚔️',Nebenhand:'🛡️',Brust:'🥋',Beine:'👖',Stiefel:'🥾',Amulett:'📿','Ring 1':'💍'})[slot]||'🎒'}
function rarity(){let x=Math.random();return x<.03?'mythic':x<.14?'rare':x<.45?'magic':'common'}
function refresh(free=false){if(S.lvl<3)return;let now=Date.now();if(!free&&S.city.stamp&&now-S.city.stamp<300000)return toast('Der Händler stellt sein Sortiment nur alle 5 Minuten kostenlos neu zusammen.');S.city.stock=[];for(let i=0;i<6;i++){let r=rarity(),it=window.createLoot?createLoot(['general','event','risk'][Math.floor(Math.random()*3)],r,S.lvl):{name:'Handelsware',slot:'Ring 1',rarity:r,power:S.lvl,bonus:{agi:1}};it.itemLevel=it.itemLevel||S.lvl;it.price=Math.max(35,Math.round((28+it.itemLevel*14+(it.power||1)*8)*(RAR[r]||1)));S.city.stock.push(it)}S.city.stamp=now;save();render()}
function buy(id){let i=S.city.stock.findIndex(x=>x.id===id);if(i<0)return;let it=S.city.stock[i];if(S.gold<it.price)return toast('Nicht genug Gold.');if(S.items.length>=S.invCap)return toast('Dein Rucksack ist voll. Nutze die Bank oder verwerten Gegenstände.');S.gold-=it.price;delete it.price;S.items.push(it);S.city.stock.splice(i,1);log(`${it.name} beim Händler gekauft.`);save();render()}
function sellValue(it){return Math.max(1,Math.round((20+(it.itemLevel||S.lvl||1)*8+(it.power||1)*5)*(RAR[it.rarity]||1)*.125))}
function sell(id){let i=S.items.findIndex(x=>x.id===id);if(i<0)return;let it=S.items[i],g=sellValue(it);S.items.splice(i,1);S.gold+=g;log(`${it.name} für ${g} Gold verkauft.`);save();render()}
function deposit(id){if(S.lvl<10)return toast('Die Bank wird ab Stufe 10 freigeschaltet.');if(S.bank.length>=100)return toast('Die Bank ist voll.');let i=S.items.findIndex(x=>x.id===id);if(i<0)return;let it=S.items.splice(i,1)[0];S.bank.push(it);save();render()}
function withdraw(id){if(S.items.length>=S.invCap)return toast('Dein Rucksack ist voll.');let i=S.bank.findIndex(x=>x.id===id);if(i<0)return;S.items.push(S.bank.splice(i,1)[0]);save();render()}
function stat(it){return window.itemBonusText?itemBonusText(it):Object.entries(it.bonus||{}).map(([k,v])=>`+${v} ${k}`).join(' · ')}
function card(it,mode){let cmp=window.itemCompareText?itemCompareText(it):'';return `<div class="mb-item rarity-border-${it.rarity||'common'}"><div class="mb-icon">${icon(it.slot)}</div><div class="mb-info"><b>${it.name}</b><small>iLvl ${it.itemLevel||S.lvl} · ${it.slot} · Macht ${it.power||1}</small><small>${stat(it)}</small>${cmp&&mode!=='bank'?`<em>${cmp}</em>`:''}</div><div class="mb-act">${mode==='shop'?`<b>🪙 ${it.price}</b><button onclick="merchantBuy('${it.id}')">Kaufen</button>`:mode==='sell'?`<b>🪙 ${sellValue(it)}</b><button onclick="merchantSell('${it.id}')">Verkaufen</button>`:mode==='deposit'?`<button onclick="bankDeposit('${it.id}')">Einlagern</button>`:`<button onclick="bankWithdraw('${it.id}')">Entnehmen</button>`}</div></div>`}
function merchant(){init();if(S.lvl<3)return locked('Händler',3,'Der Händler öffnet seinen Stand, sobald dein Name in der Stadt bekannt wird.');return `<section class="mb"><div class="mb-head"><div><small>STADTVIERTEL · STUFE 3</small><h1>🧺 Händler</h1><p>Ausrüstung kaufen oder Fundstücke für wenig Gold verkaufen. Verwerten bleibt meist wertvoller.</p></div><b>🪙 ${S.gold}</b></div><div class="mb-tabs"><button class="${S.city.view==='merchant'?'on':''}" onclick="cityMode('merchant')">Kaufen</button><button class="${S.city.view==='sell'?'on':''}" onclick="cityMode('sell')">Verkaufen</button><button onclick="tab('bank')">🏦 Bank ${S.lvl<10?'🔒':''}</button></div>${S.city.view==='sell'?`<div class="mb-note">Der Händler zahlt nur ca. 10–15 % des Gegenstandswerts. Für Schmiede-Materialien ist Verwerten meist sinnvoller.</div><div class="mb-list">${S.items.length?S.items.map(x=>card(x,'sell')).join(''):'<p class="small">Keine Gegenstände im Rucksack.</p>'}</div>`:`<div class="mb-row"><span>Sortiment skaliert mit deinem aktuellen Level.</span><button onclick="merchantRefresh()">↻ Sortiment</button></div><div class="mb-list">${S.city.stock.map(x=>card(x,'shop')).join('')}</div>`}</section>`}
function bank(){init();if(S.lvl<10)return locked('Bank',10,'100 Tresorplätze werden ab Stufe 10 freigeschaltet.');return `<section class="mb"><div class="mb-head"><div><small>STADTVIERTEL · STUFE 10</small><h1>🏦 Bank</h1><p>Sichere Ausrüstung außerhalb deines Rucksacks. Die Bank bietet 100 feste Tresorplätze.</p></div><b>${S.bank.length}/100</b></div><div class="mb-tabs"><button onclick="tab('merchant')">🧺 Händler</button><button class="on" onclick="bankMode('vault')">Tresor</button><button class="${S.city.bankView==='bag'?'on':''}" onclick="bankMode('bag')">Rucksack ${S.items.length}/${S.invCap}</button></div>${S.city.bankView==='bag'?`<div class="mb-list">${S.items.length?S.items.map(x=>card(x,'deposit')).join(''):'<p class="small">Rucksack leer.</p>'}</div>`:`<div class="mb-list">${S.bank.length?S.bank.map(x=>card(x,'bank')).join(''):'<div class="mb-empty">🏦<b>Dein Tresor ist leer.</b><span>Wechsle zu „Rucksack“, um Gegenstände einzulagern.</span></div>'}</div>`}</section>`}
function locked(name,lvl,text){return `<section class="mb"><div class="mb-lock"><span>${name==='Bank'?'🏦':'🧺'}</span><h1>${name}</h1><b>🔒 Freischaltung ab Stufe ${lvl}</b><p>${text}</p><button onclick="tab('home')">Zur Taverne</button></div></section>`}
window.merchantView=merchant;window.bankView=bank;window.merchantBuy=buy;window.merchantSell=sell;window.bankDeposit=deposit;window.bankWithdraw=withdraw;window.merchantRefresh=()=>refresh(false);window.cityMode=m=>{S.city.view=m;save();render()};window.bankMode=m=>{S.city.bankView=m;save();render()};
const baseRender=window.render;window.render=function(){if(S.screen==='merchant'||S.screen==='bank'){save();document.getElementById('app').innerHTML=`<header><div class="top"><div class="brand">🍺 Arcane Tavern & Quest <span class="small">BETA</span></div><div class="stats"><span class="pill">Lv ${S.lvl}</span><span class="pill gold">🪙 ${S.gold}</span><span class="pill">⚡ ${S.al}/${S.maxAl}</span></div></div></header><main>${S.screen==='merchant'?merchant():bank()}</main><nav class="tabs"></nav>`;return}baseRender()};
const oldTab=window.tab;window.tab=function(n){if(n==='merchant'||n==='bank'){S.screen=n;save();render();return}oldTab(n)};
const css=document.createElement('style');css.textContent=`.mb{max-width:760px;margin:auto}.mb-head{display:flex;justify-content:space-between;gap:12px;align-items:center;background:linear-gradient(135deg,#2b1b40,#17111f);border:1px solid #ffffff14;border-radius:16px;padding:13px}.mb-head h1{font-size:20px;margin:2px 0}.mb-head p{font-size:8px;color:var(--muted);margin:2px 0;max-width:500px}.mb-head>b{font-size:11px;color:var(--gold);white-space:nowrap}.mb-tabs{display:grid;grid-template-columns:repeat(3,1fr);gap:5px;margin:8px 0}.mb-tabs button{padding:8px;font-size:8px;background:#ffffff08;box-shadow:none}.mb-tabs .on{background:#7048aa}.mb-note{font-size:8px;color:#d7c28c;background:#f4c15d0b;border:1px solid #f4c15d22;border-radius:9px;padding:7px}.mb-row{display:flex;justify-content:space-between;align-items:center;font-size:8px;color:var(--muted);margin:7px 2px}.mb-row button{font-size:8px;padding:6px 8px;box-shadow:none}.mb-list{display:grid;gap:6px}.mb-item{display:grid;grid-template-columns:36px 1fr auto;gap:8px;align-items:center;background:var(--panel);border:1px solid #ffffff10;border-left:3px solid #888;border-radius:11px;padding:8px}.mb-icon{font-size:22px;text-align:center}.mb-info b,.mb-info small,.mb-info em{display:block}.mb-info b{font-size:9px}.mb-info small,.mb-info em{font-size:7px;color:var(--muted);font-style:normal;margin-top:2px}.mb-info em{color:var(--gold)}.mb-act{text-align:right}.mb-act>b{font-size:8px;color:var(--gold)}.mb-act button{display:block;font-size:7px;padding:6px 8px;margin-top:3px;box-shadow:none}.rarity-border-common{border-left-color:#999}.rarity-border-magic{border-left-color:#5da9e9}.rarity-border-rare{border-left-color:#b96ee5}.rarity-border-mythic{border-left-color:#f0ad4e}.mb-empty,.mb-lock{text-align:center;background:var(--panel);border:1px solid #ffffff10;border-radius:15px;padding:25px 12px}.mb-empty span,.mb-empty b{display:block;font-size:9px;margin:5px}.mb-empty:first-letter,.mb-lock>span{font-size:34px}.mb-lock{margin-top:15px}.mb-lock h1{margin:4px}.mb-lock b{font-size:10px;color:var(--gold)}.mb-lock p{font-size:9px;color:var(--muted)}.mb-lock button{font-size:9px}`;document.head.appendChild(css);init();
})();