(()=>{
'use strict';
const A=window.Arcane=window.Arcane||{};
const EXTRA={
home:[
'Nutze die Taverne als sicheren Ausgangspunkt deiner Progression. Beginne mit überschaubaren Aufträgen, beobachte dabei Lebenspunkte, Abenteuerlust und Belohnungen und investiere Gold nicht sofort wahllos. Mit steigender Stufe werden neue Systeme freigeschaltet; jedes davon erhält später ein eigenes Tutorial, damit du nicht mit Regeln überladen wirst, die für deinen aktuellen Fortschritt noch keine Rolle spielen.',
'Abenteuerlust regeneriert deine Möglichkeit, Tavernenaktivitäten zu starten und ist deshalb eine Planungsressource außerhalb des Kampfes. Sie wird erst beim tatsächlichen Start abgezogen. Vergleiche die Kosten verschiedener Aktivitäten mit deinem verbleibenden Vorrat: Ein teurer Auftrag kann bessere Belohnungen bieten, aber mehrere günstige Quests können sinnvoller sein, wenn du gezielt Erfahrung, Gold oder neue Ausrüstung sammeln möchtest.',
'Öffne Questkarten und lies nicht nur den Titel. Achte auf Abenteuerlust-Kosten, Dauer, Basis-XP, Goldspanne und besondere Regeln. Ereignisse können von deinen Attributen beeinflusst werden, automatische Minibosse prüfen deinen Build ohne Entscheidungen während des Kampfes und Kopfgelder verlangen aktive taktische Entscheidungen. So lernst du früh, welche Aktivität zu deinem aktuellen Ziel passt.'
],
char:[
'Der Heldentab ist die zentrale Build-Ansicht. Hier sollen Ausrüstung, Kernwerte und deine vorbereitete Skillrotation gemeinsam lesbar sein. Schaden bestimmt deinen offensiven Grunddruck, Rüstung und Leben deine Stabilität; STR, AGI und INT wirken je nach Klasse unterschiedlich. Krit, Ausweichen und Block ergänzen diese Basis. Beurteile deinen Helden deshalb immer als Gesamtpaket und nicht nach einer einzelnen hohen Zahl.',
'Jeder Ausrüstungsslot trägt zum Build bei. Tippe einen Slot an, um passende Gegenstände zu vergleichen. Itemmacht ist eine schnelle Orientierung, aber Affixe und Attribute können für deine Klasse wichtiger sein. Achte außerdem auf schwach ausgerüstete oder leere Slots: Ein solides Upgrade an einer großen Lücke bringt häufig mehr als ein kleiner Machtgewinn auf einem bereits starken Gegenstand.',
'Die vier kompakten Skillplätze unter deiner Ausrüstung bilden deine aktive Kampfrotation und sind absichtlich auf der Hauptseite sichtbar. Ihre Reihenfolge wird von automatischen Kampfsystemen verwendet. Tippe einen Platz an, um eine freigeschaltete Fähigkeit einzusetzen oder zu ersetzen. Kombiniere Schaden, Verteidigung, Heilung oder Kontrolle so, dass die Rotation zu deiner Ausrüstung und zum gewünschten Spielstil passt.',
'Deine Klasse besitzt eine eigene Kampfressource, etwa Mana, Wut, Naturfokus oder Seelenfragmente. Sie ist keine dauerhafte Währung und wird deshalb nicht im globalen Header angezeigt. Jeder neue Kampf startet mit einem frischen Vorrat. Skills verbrauchen diesen Vorrat; reicht er nicht aus, nutzt dein Held eine schwächere Basisaktion und regeneriert Ressource. Eine gute Rotation berücksichtigt daher nicht nur starke Skills, sondern auch deren Kosten.'
],
dungeon:[
'Ein Katakombenrun ist kein einzelner Kampf, sondern eine fortlaufende Expedition über mehrere Räume. Kämpfe, Ereignisse, Schreine, Schatzräume, Elitegegner und der Endboss greifen ineinander. Dein Zustand und ungesicherte Beute begleiten dich durch den Run. Plane deshalb nicht nur den nächsten Raum, sondern überlege, ob dein Build genug Reserven für die tieferen Abschnitte besitzt.',
'Katakombenschlüssel sind die Eintrittsressource für neue Expeditionen und werden im Katakomben-Header angezeigt. Ein Schlüssel wird für den Start eines Runs benötigt. Der Bestand gehört zum aktuellen Lebenszyklus und wird bei einer Reinkarnation gelöscht. Verwende Schlüssel daher bevorzugt dann, wenn Ausrüstung und Skillrotation einen realistischen Fortschritt durch mehrere Räume erwarten lassen.',
'Beute aus der Tiefe ist zunächst Teil des Risikos des Runs. Weiterzugehen kann bessere Belohnungen ermöglichen, setzt aber bereits Erreichtes stärker aufs Spiel. Besonders wichtig: Sobald ein Kampf aktiv ist, kannst du die Katakomben nicht verlassen, um eine Niederlage zu umgehen. Heilung, defensive Werte und eine nachhaltige Skillrotation gewinnen dadurch deutlich an Bedeutung.'
],
arena:[
'Die Arena wird ab Stufe 5 zu einem kontrollierten Test deines gesamten Builds. Gegner skalieren mit deinem Fortschritt und besitzen unterschiedliche Archetypen. Ausrüstung, Kernwerte, Skillrotation und Haltung wirken gleichzeitig. Siege gewähren Ruhm und Arenawährung; Ruhm führt durch die Ligen. Arena-Ausdauer begrenzt außerdem die Zahl deiner täglichen Kämpfe, daher lohnt sich eine bewusste Gegnerwahl.',
'Deine Haltung ist eine taktische Anpassung vor dem Kampf. Aggressiv erhöht offensiven Druck, kostet aber Sicherheit. Defensiv hilft gegen gefährliche Burst-Phasen und zähe Schadensrennen. Konter belohnt Ausweichen und Gegenangriffe. Lies den gegnerischen Archetyp und seinen Hinweis: Bollwerk, Schatten, Arkan und Blutklinge besitzen unterschiedliche Schwächen, sodass dieselbe Haltung nicht gegen jeden Gegner optimal ist.',
'Jede Gegnerkarte zeigt Schwierigkeit, Kampfstil und Belohnung. Ein leichter Kampf eignet sich für verlässlichen Fortschritt, während ein Herausforderer mehr Ruhm bietet, aber einen schlechten Build deutlicher bestraft. Nutze Niederlagen als Diagnose: Prüfe danach Haltung, defensive Werte und Skillkosten, statt ausschließlich nach mehr Itemmacht zu suchen.'
],
merchant:['Der Händler schließt gezielt Ausrüstungslücken. Vergleiche Angebote mit dem tatsächlich getragenen Gegenstand und behalte deine Goldreserve im Blick, denn dieselbe Währung wird auch für andere Progressionssysteme benötigt. Ein Kauf ist besonders wertvoll, wenn er einen leeren oder deutlich schwächeren Slot verbessert.','Beim Verkauf wandelst du nicht mehr benötigte Beute direkt in Gold um. Prüfe vorher, ob ein Gegenstand für einen anderen Build, einen freien Slot oder spätere Schmiedesysteme interessant sein könnte. Beim Kauf zählt nicht nur Itemmacht: passende Attribute und Affixe können einen kleineren numerischen Sprung langfristig wertvoller machen.','Das Sortiment entwickelt sich mit deiner Stufe und kann erneuert werden. Du musst nicht bei jedem Besuch Gold ausgeben. Wenn kein Gegenstand eine echte Lücke schließt, ist Sparen eine valide Entscheidung; spätere Stufen bringen stärkere Angebote und erhöhen den Wert einer gut erhaltenen Goldreserve.'],
forge:['Die Ahnenschmiede ist dein langfristiger Item-Progressionsort. Investiere bevorzugt in Gegenstände, deren Slot, Seltenheit und Affixe bereits zu deinem Build passen. Übergangsausrüstung zu stark aufzuwerten kann Ressourcen binden, die später für ein deutlich besseres Item fehlen.','Aufwertungen erhöhen die Leistung eines Gegenstands, werden mit steigender Schmiedestufe aber kostspieliger. Prüfe vor jedem größeren Schritt, wie lange du das Item voraussichtlich tragen wirst. Ein hochwertiges Kernitem ist meist ein besseres Ziel als ein zufälliger Gegenstand, der nur kurzfristig mehr Itemmacht besitzt.','Verwerten macht schlechte Drops zu einem Teil der Progression. Nicht benötigte Gegenstände werden in Schmiedematerialien umgewandelt, die hochwertige Ausrüstung verbessern. Dadurch entsteht ein Kreislauf: Quests liefern Beute, du behältst passende Upgrades und wandelst den Rest in Ressourcen für deine stärksten Gegenstände um.','Veredelung und Ahnenwerk sind Systeme für gezielte Optimierung. Affixe können deinen Build stärker prägen als reine Itemmacht. Nutze teure Feinarbeit deshalb auf Gegenständen mit langfristigem Wert. Das Ahnenwerk ist eine Endgame-Investition und sollte nicht wie ein gewöhnliches kurzfristiges Upgrade behandelt werden.'],
shrine:['Stufe 50 beendet nicht das Spiel, sondern einen Lebenszyklus. Reinkarnation tauscht große Teile kurzfristiger Progression gegen dauerhafte Entwicklung. Vor diesem Schritt solltest du verstehen, welche Werte zurückgesetzt werden und welche permanent bleiben, denn der nächste Zyklus beginnt wieder auf niedriger Stufe, profitiert aber von deinem aufgebauten Vermächtnis.','Seelensteine sind die zentrale permanente Ressource der Reinkarnation. Der Vermächtnisbaum besitzt mehrere Zweige, deren Knoten strikt nacheinander gekauft werden. Macht stärkt den direkten Kampf, Überleben erhöht Stabilität und Arkana verbessert wirtschaftliche beziehungsweise progressionale Vorteile. Plane einen Pfad, statt Punkte nur nach dem aktuell günstigsten Knoten zu verteilen.','Reinkarnation setzt Level, XP, Gold, normale Ausrüstung, viele Materialien, aktive Aktivitäten und sämtliche Katakombenschlüssel zurück. Permanente Vermächtnisfortschritte und die Reinkarnationshistorie bleiben erhalten. Der Vorgang ist deshalb eine bewusste strategische Entscheidung: Du opferst den aktuellen Zyklus, um zukünftige Durchläufe dauerhaft effizienter und stärker zu machen.']};
function apply(){const chapters=A.onboarding?.chapters;if(!chapters)return false;for(const [id,texts] of Object.entries(EXTRA)){const steps=chapters[id]?.steps||[];texts.forEach((text,i)=>{if(steps[i])steps[i].text=text})}return true}
if(!apply()){A.on?.('bootReady',apply);queueMicrotask(apply)}
A.onboardingCopyV2={apply};
})();