(()=>{
function normalizeSlot(slot){return slot==='Ring 1'||slot==='Ring 2'?'Ring':slot}
function migrate(){S.eq=S.eq||{};S.items=S.items||[];let changed=false;
const candidates=[];
for(const key of ['Ring','Ring 1','Ring 2']){const it=S.eq[key];if(it)candidates.push(it);if(key!=='Ring'&&Object.prototype.hasOwnProperty.call(S.eq,key)){delete S.eq[key];changed=true}}
if(candidates.length){if(!S.eq.Ring){const keep=candidates.shift();keep.slot='Ring';S.eq.Ring=keep;changed=true}else candidates.splice(candidates.indexOf(S.eq.Ring),1);for(const it of candidates){if(it&&it!==S.eq.Ring){it.slot='Ring';S.items.push(it);changed=true}}}
const belt=S.eq['Gürtel'];if(belt){delete S.eq['Gürtel'];belt.slot='Beute';S.items.push(belt);changed=true}
for(const it of S.items){if(!it)continue;if(it.slot==='Ring 1'||it.slot==='Ring 2'){it.slot='Ring';changed=true}else if(it.slot==='Gürtel'){it.slot='Beute';changed=true}}
if(S.heroSlotFilter==='Ring 1'||S.heroSlotFilter==='Ring 2'){S.heroSlotFilter='Ring';changed=true}else if(S.heroSlotFilter==='Gürtel'){delete S.heroSlotFilter;changed=true}
if(changed){window.syncEquipmentStats?.();save?.()}return changed}
const oldEquip=window.heroEquip;if(typeof oldEquip==='function')window.heroEquip=function(id){const it=(S.items||[]).find(x=>x.id===id);if(!it||!['Ring','Ring 1','Ring 2'].includes(it.slot))return oldEquip.apply(this,arguments);S.eq=S.eq||{};const ix=S.items.findIndex(x=>x.id===id);if(ix<0)return;const old=S.eq.Ring||S.eq['Ring 1']||S.eq['Ring 2'];S.items.splice(ix,1);if(old&&old!==it){old.slot='Ring';S.items.push(old)}it.slot='Ring';S.eq.Ring=it;delete S.eq['Ring 1'];delete S.eq['Ring 2'];S.heroOpenItem=it.id;window.syncEquipmentStats?.();save?.();render?.()};
const oldSlotOpen=window.heroSlotOpen;if(typeof oldSlotOpen==='function')window.heroSlotOpen=function(slot){if(slot==='Gürtel')return;return oldSlotOpen.call(this,normalizeSlot(slot))};
function cleanHero(){if(S?.screen!=='char')return;migrate();const root=document.querySelector('.he4');if(!root)return;root.querySelectorAll('.he4-slot').forEach(btn=>{const label=btn.querySelector('small');const text=label?.textContent.trim();if(text==='Ring 2'||text==='Gürtel')btn.remove();else if(text==='Ring 1'&&label)label.textContent='Ring'});root.querySelectorAll('.he4-item small,.he4-detail small').forEach(el=>{el.textContent=el.textContent.replace(/^Ring 1\b/,'Ring').replace(/^Ring 2\b/,'Ring')});const lower=root.querySelector('.he4-lower');if(lower)lower.classList.add('sr1-lower');const title=[...root.querySelectorAll('.he4-title small')].find(x=>/Slots belegt/i.test(x.textContent));if(title){const occupied=Object.entries(S.eq||{}).filter(([k,v])=>v&&!['Ring 1','Ring 2','Gürtel'].includes(k)).length;title.textContent=`${occupied}/8 Slots belegt`}}
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);queueMicrotask(cleanHero);return r};
const oldChar=window.char;if(typeof oldChar==='function')window.char=function(){migrate();return oldChar.apply(this,arguments)};
const css=document.createElement('style');css.textContent=`.he4-lower.sr1-lower{grid-template-columns:repeat(3,1fr)!important;max-width:330px;margin-left:auto!important;margin-right:auto!important}.he4-lower.sr1-lower .he4-slot{min-width:0}@media(max-width:430px){.he4-lower.sr1-lower{max-width:none;gap:6px!important}.he4-lower.sr1-lower .he4-slot{height:58px!important}}`;document.head.appendChild(css);migrate();queueMicrotask(cleanHero)
})();