(()=>{
function normalizeSlot(slot){return slot==='Ring 1'||slot==='Ring 2'?'Ring':slot==='Schultern'?'Schulter':slot==='Nebenhand'?'Zweithand':slot}
const RETIRED=new Set(['Gürtel','Handschuhe']);
function migrate(){S.eq=S.eq||{};S.items=S.items||[];let changed=false;
const candidates=[];
for(const key of ['Ring','Ring 1','Ring 2']){const it=S.eq[key];if(it)candidates.push(it);if(key!=='Ring'&&Object.prototype.hasOwnProperty.call(S.eq,key)){delete S.eq[key];changed=true}}
if(candidates.length){if(!S.eq.Ring){const keep=candidates.shift();keep.slot='Ring';S.eq.Ring=keep;changed=true}else candidates.splice(candidates.indexOf(S.eq.Ring),1);for(const it of candidates){if(it&&it!==S.eq.Ring){it.slot='Ring';S.items.push(it);changed=true}}}
for(const [from,to] of [['Schultern','Schulter'],['Nebenhand','Zweithand']]){if(S.eq[from]){if(!S.eq[to]){S.eq[to]=S.eq[from];S.eq[to].slot=to}else{S.eq[from].slot=to;S.items.push(S.eq[from])}delete S.eq[from];changed=true}}
for(const key of RETIRED){const retired=S.eq[key];if(retired){delete S.eq[key];retired.slot='Beute';S.items.push(retired);changed=true}}
for(const it of S.items){if(!it)continue;const normalized=normalizeSlot(it.slot);if(normalized!==it.slot){it.slot=normalized;changed=true}else if(RETIRED.has(it.slot)){it.slot='Beute';changed=true}}
if(S.heroSlotFilter==='Ring 1'||S.heroSlotFilter==='Ring 2'){S.heroSlotFilter='Ring';changed=true}else if(S.heroSlotFilter==='Schultern'){S.heroSlotFilter='Schulter';changed=true}else if(S.heroSlotFilter==='Nebenhand'){S.heroSlotFilter='Zweithand';changed=true}else if(RETIRED.has(S.heroSlotFilter)){delete S.heroSlotFilter;changed=true}
if(changed){window.syncEquipmentStats?.();save?.()}return changed}
const oldEquip=window.heroEquip;if(typeof oldEquip==='function')window.heroEquip=function(id){const it=(S.items||[]).find(x=>x.id===id);if(!it)return oldEquip.apply(this,arguments);const slot=normalizeSlot(it.slot);if(slot==='Ring'){S.eq=S.eq||{};const ix=S.items.findIndex(x=>x.id===id);if(ix<0)return;const old=S.eq.Ring||S.eq['Ring 1']||S.eq['Ring 2'];S.items.splice(ix,1);if(old&&old!==it){old.slot='Ring';S.items.push(old)}it.slot='Ring';S.eq.Ring=it;delete S.eq['Ring 1'];delete S.eq['Ring 2'];S.heroOpenItem=it.id;window.syncEquipmentStats?.();save?.();render?.();return}if(slot!==it.slot)it.slot=slot;return oldEquip.apply(this,arguments)};
const oldSlotOpen=window.heroSlotOpen;if(typeof oldSlotOpen==='function')window.heroSlotOpen=function(slot){if(RETIRED.has(slot))return;return oldSlotOpen.call(this,normalizeSlot(slot))};
function findSlot(root,label){return [...root.querySelectorAll('.he4-slot')].find(btn=>btn.querySelector('small')?.textContent.trim()===label)||null}
function cleanHero(){if(S?.screen!=='char')return;migrate();const root=document.querySelector('.he4');if(!root)return;
root.querySelectorAll('.he4-slot').forEach(btn=>{const label=btn.querySelector('small'),text=label?.textContent.trim();if(text==='Ring 2'||RETIRED.has(text))btn.remove();else if(text==='Ring 1'&&label)label.textContent='Ring';else if(text==='Schultern'&&label)label.textContent='Schulter';else if(text==='Nebenhand'&&label)label.textContent='Zweithand'});
root.querySelectorAll('.he4-item small,.he4-detail small').forEach(el=>{el.textContent=el.textContent.replace(/^Ring [12]\b/,'Ring').replace(/^Schultern\b/,'Schulter').replace(/^Nebenhand\b/,'Zweithand')});
const paper=root.querySelector('.he4-paper');if(paper&&!paper.classList.contains('he4-balanced-layout')){
 const avatar=paper.querySelector('.avatar');const lower=root.querySelector('.he4-lower');
 const slots={head:findSlot(root,'Kopf'),shoulder:findSlot(root,'Schulter'),chest:findSlot(root,'Brust'),legs:findSlot(root,'Beine'),boots:findSlot(root,'Stiefel'),amulet:findSlot(root,'Amulett'),ring:findSlot(root,'Ring'),main:findSlot(root,'Haupthand'),off:findSlot(root,'Zweithand')};
 const left=document.createElement('div');left.className='he4-side he4-side-left';const right=document.createElement('div');right.className='he4-side he4-side-right';const center=document.createElement('div');center.className='he4-center';const weapons=document.createElement('div');weapons.className='he4-weapons';
 [slots.head,slots.shoulder,slots.chest,slots.legs,slots.boots].filter(Boolean).forEach(x=>left.appendChild(x));[slots.amulet,slots.ring].filter(Boolean).forEach(x=>right.appendChild(x));[slots.main,slots.off].filter(Boolean).forEach(x=>weapons.appendChild(x));
 center.appendChild(avatar);center.appendChild(weapons);paper.replaceChildren(left,center,right);paper.classList.add('he4-balanced-layout');if(lower)lower.remove();
 }
const title=[...root.querySelectorAll('.he4-title small')].find(x=>/Slots belegt/i.test(x.textContent));if(title){const valid=new Set(['Kopf','Schulter','Brust','Beine','Stiefel','Haupthand','Zweithand','Amulett','Ring']);const occupied=Object.entries(S.eq||{}).filter(([k,v])=>v&&valid.has(normalizeSlot(k))).length;title.textContent=`${occupied}/9 Slots belegt`}}
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);queueMicrotask(cleanHero);return r};
const oldChar=window.char;if(typeof oldChar==='function')window.char=function(){migrate();return oldChar.apply(this,arguments)};
const css=document.createElement('style');css.textContent=`.he4-paper.he4-balanced-layout{display:grid!important;grid-template-columns:72px minmax(130px,1fr) 72px!important;grid-template-areas:none!important;gap:8px!important;align-items:stretch!important}.he4-balanced-layout .he4-side-left{display:grid!important;grid-template-rows:repeat(5,1fr)!important;gap:5px!important}.he4-balanced-layout .he4-side-right{display:grid!important;grid-template-rows:repeat(2,64px)!important;align-content:center!important;gap:8px!important}.he4-balanced-layout .he4-center{display:grid!important;grid-template-rows:minmax(230px,1fr) auto!important;gap:7px!important;min-width:0}.he4-balanced-layout .avatar{grid-area:auto!important;min-height:230px!important}.he4-balanced-layout .he4-weapons{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:6px!important}.he4-balanced-layout .he4-slot{height:auto!important;min-height:52px!important}.he4-balanced-layout .he4-weapons .he4-slot{min-height:60px!important}.he4-lower{display:none!important}@media(max-width:430px){.he4-paper.he4-balanced-layout{grid-template-columns:64px minmax(106px,1fr) 64px!important;gap:5px!important}.he4-balanced-layout .he4-side-left{gap:4px!important}.he4-balanced-layout .he4-side-right{grid-template-rows:repeat(2,58px)!important;gap:6px!important}.he4-balanced-layout .he4-center{grid-template-rows:minmax(205px,1fr) auto!important;gap:5px!important}.he4-balanced-layout .avatar{min-height:205px!important}.he4-balanced-layout .he4-slot{min-height:47px!important}.he4-balanced-layout .he4-weapons .he4-slot{min-height:56px!important}.he4-balanced-layout .he4-slot>small{font-size:5.5px!important}}`;document.head.appendChild(css);migrate();queueMicrotask(cleanHero)
})();