(()=>{
function normalizeRingSlot(slot){return slot==='Ring 2'||slot==='Ring'?'Ring 1':slot}
function migrate(){S.eq=S.eq||{};S.items=S.items||[];let changed=false;const second=S.eq['Ring 2'];if(second){delete S.eq['Ring 2'];second.slot='Ring 1';S.items.push(second);changed=true}for(const it of S.items){if(it&&it.slot==='Ring 2'){it.slot='Ring 1';changed=true}}if(S.heroSlotFilter==='Ring 2'){S.heroSlotFilter='Ring 1';changed=true}if(changed){window.syncEquipmentStats?.();save?.()}return changed}
const oldEquip=window.heroEquip;if(typeof oldEquip==='function')window.heroEquip=function(id){const it=(S.items||[]).find(x=>x.id===id);if(!it||!['Ring','Ring 1','Ring 2'].includes(it.slot))return oldEquip.apply(this,arguments);S.eq=S.eq||{};const ix=S.items.findIndex(x=>x.id===id);if(ix<0)return;const old=S.eq['Ring 1'];S.items.splice(ix,1);if(old){old.slot='Ring 1';S.items.push(old)}it.slot='Ring 1';S.eq['Ring 1']=it;delete S.eq['Ring 2'];S.heroOpenItem=it.id;window.syncEquipmentStats?.();save?.();render?.()};
const oldSlotOpen=window.heroSlotOpen;if(typeof oldSlotOpen==='function')window.heroSlotOpen=function(slot){return oldSlotOpen.call(this,normalizeRingSlot(slot))};
function cleanHero(){if(S?.screen!=='char')return;migrate();const root=document.querySelector('.he4');if(!root)return;root.querySelectorAll('.he4-slot').forEach(btn=>{if(btn.querySelector('small')?.textContent.trim()==='Ring 2')btn.remove()});const lower=root.querySelector('.he4-lower');if(lower)lower.classList.add('sr1-lower');const title=[...root.querySelectorAll('.he4-title small')].find(x=>/Slots belegt/i.test(x.textContent));if(title){const occupied=Object.entries(S.eq||{}).filter(([k,v])=>v&&k!=='Ring 2').length;title.textContent=`${occupied}/10 Slots belegt`}}
const oldRender=window.render;if(typeof oldRender==='function')window.render=function(){const r=oldRender.apply(this,arguments);queueMicrotask(cleanHero);return r};
const oldChar=window.char;if(typeof oldChar==='function')window.char=function(){migrate();return oldChar.apply(this,arguments)};
const css=document.createElement('style');css.textContent=`.he4-lower.sr1-lower{grid-template-columns:repeat(4,1fr)!important;max-width:420px;margin-left:auto!important;margin-right:auto!important}.he4-lower.sr1-lower .he4-slot{min-width:0}@media(max-width:430px){.he4-lower.sr1-lower{max-width:none;gap:6px!important}.he4-lower.sr1-lower .he4-slot{height:58px!important}}`;document.head.appendChild(css);migrate();queueMicrotask(cleanHero)
})();