(()=>{
let miniOpen=false;
const baseHome=window.home;
const rawCost={raid:12,event:18,bounty:24,risk:28,mini:16};
const titleToId={'Schatten im alten Forst':'raid','Das flüsternde Siegel':'event','Der Knochenhauer':'bounty','Die versunkene Krypta':'risk','Knochenwache':'mini'};
const eff=(id)=>window.getEffectiveQuestCost?getEffectiveQuestCost(id,rawCost[id]):rawCost[id];
const miniXP=()=>window.ARCANE_BALANCE?.xpAward?ARCANE_BALANCE.xpAward(38+(S.lvl||1)*2,'mini'):38+(S.lvl||1)*2;
function miniMarkup(){const cost=eff('mini'),saved=rawCost.mini-cost;return `<article class="quest-card tv5-card tv5-mini ${miniOpen?'open':''}" data-qid="mini" onclick="tv5MiniToggle()"><div class="quest-summary"><div class="q-icon">⚔️</div><div class="q-main"><div class="q-title"><b>Knochenwache</b><span class="q-cat">MINIBOSS · AUTO</span><span class="tv5-risk">Auto</span></div><div class="q-meta"><span>⏱ kurz</span><span>⚡ ${cost}${saved?` <small>statt ${rawCost.mini}</small>`:''}</span><span>✦ ~${miniXP()} XP</span></div></div><span class="chev">${miniOpen?'⌃':'⌄'}</span></div>${miniOpen?`<div class="quest-expand"><p>Kurzer automatischer Kampf mit geringerem Risiko und weniger Beute als der Knochenhauer.</p><div class="detail-grid"><span><b>kurz</b><small>Dauer</small></span><span><b>${cost}</b><small>AL${saved?` · statt ${rawCost.mini}`:''}</small></span><span><b>45–90</b><small>Gold</small></span><span><b>niedriger</b><small>Loot</small></span></div><button class="start-q" onclick="startAutoMiniBoss();event.stopPropagation()">Automatischen Kampf starten · ⚡ ${cost}${saved?` (${saved} gespart)`:''}</button></div>`:''}</article>`}
function questId(card){const preset=card.dataset.qid;if(preset&&rawCost[preset])return preset;const title=card.querySelector('.q-title b')?.textContent?.trim();if(titleToId[title])return titleToId[title];const start=card.querySelector('.start-q');const oc=start?.getAttribute('onclick')||'';const m=oc.match(/qStart\('([^']+)'/);return m?.[1]||null}
function decorateCard(card){const id=questId(card);if(!id||!rawCost[id])return;card.classList.add('tv5-card');card.dataset.qid=id;const open=card.classList.contains('open');const desc=card.querySelector('.q-main>p');if(desc)desc.style.display=open?'block':'none';const ex=card.querySelector('.quest-expand');if(ex)ex.style.display=open?'block':'none';const c=eff(id),saved=rawCost[id]-c;card.querySelectorAll('.q-meta span').forEach(s=>{if((s.textContent||'').trim().startsWith('⚡'))s.innerHTML=`⚡ ${c}${saved?` <small>statt ${rawCost[id]}</small>`:''}`});if(ex){ex.querySelectorAll('.detail-grid span').forEach(x=>{const sm=x.querySelector('small');if(sm&&sm.textContent.trim().startsWith('AL')){const b=x.querySelector('b');if(b)b.textContent=c;sm.textContent=saved?`AL · statt ${rawCost[id]}`:'AL'}});const btn=ex.querySelector('.start-q');if(btn){const label=id==='bounty'?'Kopfgeld starten':'Quest starten';btn.textContent=`${label} · ⚡ ${c}${saved?` (${saved} gespart)`:''}`}}}
function clean(html){if(S.autoMiniBattle)return html;const box=document.createElement('div');box.innerHTML=html;box.querySelectorAll('.d1-home,.d-beta-back').forEach(x=>x.remove());box.querySelectorAll('a,button').forEach(x=>{if((x.textContent||'').trim()==='Katakomben'&&!x.closest('.tabs'))x.remove()});const list=box.querySelector('.quest-list');if(!list)return box.innerHTML;[...list.querySelectorAll('article.quest-card')].forEach(c=>{if(c.querySelector('.q-title b')?.textContent.trim()==='Knochenwache')c.remove()});list.insertAdjacentHTML('afterbegin',miniMarkup());[...list.querySelectorAll('article.quest-card')].forEach(decorateCard);const oldNote=box.querySelector('.tv5-passive');oldNote?.remove();if(S.bg==='Tavernen-Stammgast'){const sec=box.querySelector('.quest-section');if(sec)sec.insertAdjacentHTML('afterbegin','<div class="tv5-passive">🍺 Tavernen-Stammgast aktiv · 15 % weniger Abenteuerlust</div>')}return box.innerHTML}
window.tv5MiniToggle=function(){if(!miniOpen){const open=document.querySelector('.quest-card.open[data-qid]:not([data-qid="mini"])');if(open&&window.qSelect)window.qSelect(open.dataset.qid)}miniOpen=!miniOpen;render()};
const baseSelect=window.qSelect;if(baseSelect)window.qSelect=function(id){miniOpen=false;return baseSelect(id)};
window.home=function(){return clean(baseHome())};
const css=document.createElement('style');css.textContent=`.tv5-passive{margin:0 0 8px;padding:7px 9px;border-radius:9px;background:#f4c15d0c;border:1px solid #f4c15d2d;color:var(--gold);font-size:10px;font-weight:800}.tv5-card{overflow:hidden;border-radius:14px!important}.tv5-card:not(.open) .q-main>p,.tv5-card:not(.open) .quest-expand{display:none!important}.tv5-card .quest-summary{min-height:68px}.tv5-card .q-meta small{font-size:8px;color:var(--gold)}.tv5-risk{font-size:8px;padding:2px 5px;border-radius:999px;background:#a875ff1c;color:#c9a9ff;font-weight:800}.tv5-card .quest-expand{border-top:1px solid #ffffff0b}.tv5-card .start-q{width:100%}.active-quest>.active-title{display:grid!important;grid-template-columns:auto minmax(0,1fr);align-items:center;gap:12px;margin:8px 0 12px}.active-quest>.active-title>.q-icon{margin:0!important}.active-quest>.active-title>div{min-width:0;display:flex;align-items:baseline;gap:8px;flex-wrap:wrap}.active-quest>.active-title b{font-size:18px;line-height:1.15;white-space:normal}.active-quest>.active-title small{font-size:10px;line-height:1;color:#b98cff;font-weight:900;letter-spacing:.08em;white-space:nowrap}.active-quest .event-box{padding:14px 14px 12px!important;border-radius:16px}.active-quest .event-box>.eyebrow{margin-bottom:5px}.active-quest .event-box h3{margin:0 0 6px!important;font-size:20px;line-height:1.15}.active-quest .event-box>p{margin:0 0 10px!important;font-size:13px;line-height:1.38}.active-quest .event-choices{display:grid;gap:8px}.active-quest .event-choices button{min-height:0!important;padding:9px 10px!important;border-radius:13px;display:grid!important;grid-template-columns:52px minmax(0,1fr);align-items:center;gap:8px;text-align:left}.active-quest .event-choices button>span{width:52px;height:52px;display:grid;place-items:center;font-size:32px;line-height:1}.active-quest .event-choices button>div{min-width:0}.active-quest .event-choices b{display:block;font-size:15px;line-height:1.1;margin-bottom:2px}.active-quest .event-choices small{display:block;font-size:11px;line-height:1.25;margin:0 0 2px}.active-quest .event-choices em{display:block;font-size:10px;line-height:1.1}.active-quest .event-hint{margin-top:8px!important;padding:0!important;font-size:9px;line-height:1.25}.active-quest{padding-bottom:12px!important}@media(max-width:420px){.active-quest>.active-title{gap:9px}.active-quest>.active-title b{font-size:17px}.active-quest .event-box{padding:12px!important}.active-quest .event-choices button{grid-template-columns:48px minmax(0,1fr);padding:8px 9px!important}.active-quest .event-choices button>span{width:48px;height:48px;font-size:29px}}`;document.head.appendChild(css);if(S.screen==='home')render();
})();